### ISSUE TITLE
freeRTOS Scheduling policy

### ISSUE THREAD

**Issue by gustavomassa** [espressif/ESP8266_RTOS_SDK#101]
Hello,

I realized that the current freeRTOS config is using a Pre-emptive scheduler policy:
```
Pre-emptive scheduling algorithms will immediately ‘pre-empt’ the Running
state task if a task that has a priority higher than the Running state task
enters the Ready state. Being pre-empted means being involuntarily (without
explicitly yielding or blocking) moved out of the Running state and into the
Ready state to allow a different task to enter the Running state.
```

But in my opinion it would be better to use a Time Slicing scheduler policy:
```
Time slicing is used to share processing time between tasks of equal priority,
even when the tasks do not explicitly yield or enter the Blocked state.
Scheduling algorithms described as using ‘Time Slicing’ will select a new task
to enter the Running state at the end of each time slice if there are other
Ready state tasks that have the same priority as the Running task. A time
slice is equal to the time between two RTOS tick interrupts.
```

The configTICK_RATE_HZ has a value of 100hz, resulting in a time slice of 10ms.
To activate the Time Slicing scheduler policy, the definition "configUSE_TIME_SLICING 1" must be set inside the FreeRTOSConfig.h.
@espressif I would like to have your opinion about it.

Thank you,
Regards

**Comment by FayeY** [comment]
Hi, this issue should have been solved in the latest SDK, if it is not please feel free to reopen it.
