### ISSUE TITLE
c++ support (GIT8266O-611)

### ISSUE THREAD

**Issue by PranavD10** [espressif/ESP8266_RTOS_SDK#1034]
Hi,
does esp8266 rtos supports cpp code. I am not able to compile the code.
Thank you,

**Comment by PranavD10** [comment]
resolved by putting configurations in component.mk.

**Comment by grepson** [comment]
Can you share what flags were put into component.mk? I cannot resolve this problem myself.

**Comment by PranavD10** [comment]
Hello @grepson,

I am not able to recall since I was working on it long time back. But It did compiled and worked fine.

I suggest you to put the main function call within extern. Also please share the error that you are getting while compiling if above method does not work.

Thank you,
