### ISSUE TITLE
cJSON_print() is not working for Numbers (GIT8266O-622)

### ISSUE THREAD

**Issue by PranavD10** [espressif/ESP8266_RTOS_SDK#1045]
Hi,
I want to report an issue related to cJson lib, By using cJSON_AddNumberToObject and then cJSON_Print or cJSON_printUnformatted I have been getting null string.
I have tested the same code with esp32 and its working fine, what could be the issue working with esp8266?

**Comment by berkutta** [comment]
try this https://github.com/espressif/ESP8266_RTOS_SDK/issues/936#issuecomment-739075075

**Comment by PranavD10** [comment]
Working...!!!
