### ISSUE TITLE
bug in wifi_set_event_handler_cb

### ISSUE THREAD

**Issue by mmmmar** [espressif/ESP8266_RTOS_SDK#106]
I find other also have the same issue.
if there is a user task that does not have any block and delay, the function is registered in  **wifi_set_event_handler_cb** will never be callback.
I think priority of it is lower than user task, so if user task runs, it has no change to callback.

**Comment by curiousmuch** [comment]
I've also commented on their forum regarding this issue and have yet to receive a response.

**Comment by curiousmuch** [comment]
Opps. I just checked the forum. It looks like Espressif has asked for example code. I'll provide it now.

**Comment by curiousmuch** [comment]
http://bbs.espressif.com/viewtopic.php?f=66&t=4248&p=13174#p13174

**Comment by curiousmuch** [comment]
Espressif is much more responsive on the forums. Please see the following:

http://bbs.espressif.com/viewtopic.php?f=66&t=4248

**Comment by mmmmar** [comment]
@curiousmuch Thanks. I have saw it.
