### ISSUE TITLE
 implicit declaration of function '__fbufsize' [-Werror=implicit-function-declaration] (GIT8266O-657)

### ISSUE THREAD

**Issue by vyacheslav-shubin** [espressif/ESP8266_RTOS_SDK#1079]
clone repository
./install.sh
./add_path.sh
cd examples/get-started/hello_world/
make

error: implicit declaration of function '__fbufsize' [-Werror=implicit-function-declaration]
         if (__fbufsize(stdout) > 0) {
         ^

How to fix it?

**Comment by vyacheslav-shubin** [comment]
solved

**Comment by h1aji** [comment]
@vyacheslav-shubin how did you solve it? can you share please

**Comment by vyacheslav-shubin** [comment]
Change toolchain

**Comment by h1aji** [comment]
true. new sdk requires new toolchain - https://dl.espressif.com/dl/xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz
