### ISSUE TITLE
esp8266 libmain.a error: (.text+0x4): multiple definition of `_malloc_r'

### ISSUE THREAD

**Issue by xiangjiangnan** [espressif/ESP8266_RTOS_SDK#110]
Lately I try to transplant mqtt into ESP8266_RTOS_SDK,but at my first step,I encounter a problem.I want to use freertos,I use esp8266 uart0 to get data for test.So I create a task for uart . I modified Makefile and built it .The error is as follow:
make[2]: Leaving directory '/cygdrive/e/gitshell/esp8266-mqtt-rtos/app/driver'
xtensa-lx106-elf-gcc  -L ../lib -nostdlib -T../ld/eagle.app.v6.ld -Wl,--no-check-sections -Wl,--gc-sections -u call_user_start -Wl,-static -Wl,--start-group -lgcc -lc -lhal -lphy -lpp -lnet80211 -llwip -lwpa -lcrypto -lmain -lpwm -lfreertos -lspiffs user/.output/eagle/debug/lib/libuser.a driver/.output/eagle/debug/lib/libdriver.a -Wl,--end-group -o .output/eagle/debug/image/eagle.app.v6.out 
../lib/libmain.a(libc.o): In function `_malloc_r':
(.text+0x4): multiple definition of `_malloc_r'
/opt/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/libc.a(mallocr.o):\build\tree\RC-2010.1_kuma\p4root\Xtensa\Target-libs\newlib\newlib\libc\stdlib/mallocr.c:2335: first defined here
../lib/libmain.a(libc.o): In function `_realloc_r':
(.text+0x1c): multiple definition of `_realloc_r'
/opt/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/libc.a(reallocr.o):\build\tree\RC-2010.1_kuma\p4root\Xtensa\Target-libs\newlib\newlib\libc\stdlib/mallocr.c:2759: first defined here
../lib/libmain.a(libc.o): In function `_calloc_r':
(.text+0x38): multiple definition of `_calloc_r'
/opt/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/libc.a(callocr.o):\build\tree\RC-2010.1_kuma\p4root\Xtensa\Target-libs\newlib\newlib\libc\stdlib/mallocr.c:3194: first defined here
../lib/libmain.a(libc.o): In function `_free_r':
(.text+0x54): multiple definition of `_free_r'
...
How can I solve it?
Thank you.

**Comment by donghengqaz** [comment]
You can use newer(v3.0 and master) version and it support better newlib.
