### ISSUE TITLE
AES PN Error (GIT8266O-696)

### ISSUE THREAD

**Issue by berkutta** [espressif/ESP8266_RTOS_SDK#1118]
I often get Errors like these in the Log. Is this a known issue? Also Network Traffic has extreme packet loss as soon as these Messages appear.

E (2630603) wifi: AES PN: 000000000000029e <= 00000000000002a3
E (2631028) wifi: AES PN: 000000000000029f <= 00000000000002a3
[...]
E (2631318) wifi: AES PN: 00000000000002a0 <= 00000000000002a5
E (2632391) wifi: AES PN: 00000000000002a9 <= 00000000000002ad

**Comment by oleszczyk** [comment]
@berkutta Have you found out what was the reason? Any fix/solution?

**Comment by berkutta** [comment]
@oleszczyk The issue was a very bad occupied RF environment, not an issue of the ESP.

**Comment by shaniprogrammer** [comment]
i have also same issue in  esp8266 If someone has resolved it, then tell me. Thanks in advance.

**Comment by Hruthik0x** [comment]
I have the same issue..
