### ISSUE TITLE
ShowCritical crash

### ISSUE THREAD

**Issue by gustavomassa** [espressif/ESP8266_RTOS_SDK#112]
Hello,

http://bbs.espressif.com/viewtopic.php?f=66&t=4830

After the lastest commit #46cf8c3  the "ShowCritical" bug that was occurring during the wifi scan was partially fixed, sometimes it is still hapenning.

```
231,694 (gdb) 
231,713 @"(user_init) 124189383 - SDK vers"
231,717 @"ion: 1.5.0-dev(1aafc07)\n"
231,723 @"(user_init) 124190051 - Free hea"
231,727 @"p size: 38920\n"
231,732 @"mode : sta(5c:cf:7f:0f:08:eb)\n"
231,734 @"add if0\n"
235,310 @"ShowCritical:0\n"
```
Also sometimes while debugging the code using gdbstub, I face the ShowCritical: 0 and ShowCritical: 1 messages, something related to the freeRTOS scheduler, probably during the context switch/vPortMalloc/vPortEnterCritical/vPortExitCritical. 
Please update the port.c file with the ShowCritical function to include the entire stack on the print.

**Comment by FayeY** [comment]
Sorry that we cannot reproduce your problem. Could you provide your test code and test steps? 
port.c is open source, you can update it if needed.
