### ISSUE TITLE
GPIO numbering wrong (GIT8266O-717)

### ISSUE THREAD

**Issue by bertmelis** [espressif/ESP8266_RTOS_SDK#1139]
I've installed the latest SDK on Windows 10. Firmware is running on a Wemos D1 Mini.
I tried to run a simple blink but the pin numbering is completely wrong.

With
```
#define GPIO_OUTPUT_IO GPIO_Pin_4
```
a LED blinks on D0 which imho should map to GPIO16.
Output is
```
pin: 16
pin bitmask: 65536
```

With 
```
#define GPIO_OUTPUT_IO GPIO_Pin_2
```
a LED blinks on D2 which should map to GPIO4
Output is
```
pin: 4
pin bitmask: 16
```

It becomes worse when using GPIO_Pin_5:
```
C:/msys32/home/Bert/esp/pmsensor02/main/main.c:15:21: warning: conversion from 'long long unsigned int' to 'unsigned int' changes value from '4294967296' to '0' [-Woverflow]
     .pin_bit_mask = (1ULL<<GPIO_OUTPUT_IO),
```

```
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"

#define GPIO_OUTPUT_IO GPIO_Pin_4

void blink() {
  gpio_config_t io_conf = {
    .intr_type = GPIO_INTR_DISABLE,
    .mode = GPIO_MODE_OUTPUT,
    .pin_bit_mask = (1ULL<<GPIO_OUTPUT_IO),
    .pull_down_en = 0,
    .pull_up_en = 0,
  };
  gpio_config(&io_conf);

  printf("pin: %lu\n", GPIO_OUTPUT_IO);
  printf("pin bitmask: %u\n", io_conf.pin_bit_mask);

  int cnt = 0;
  while (true) {
    vTaskDelay(1000 / portTICK_RATE_MS);
    gpio_set_level(GPIO_OUTPUT_IO, cnt % 2);
  }
}

TaskHandle_t xHandle = NULL;

void app_main() {
  printf("Starting blink task\n");
  BaseType_t xReturned = xTaskCreate(blink,
                                     "BLINK",
                                     2048,
                                     (void*)1,
                                     1,
                                     &xHandle);
  if (xReturned != pdPASS) {
    printf("Error creating BLINK task\n");
  }
}
```

**Comment by dsptech** [comment]
Hi, 
D0, D1 ... etc is the Arduino numbering. In this sdk you have to use directly the chip GPIO numbering instead. Google for "Wemos D1 Mini pinout" to see the mapping.

It also should be noted that GPIO_Pin_4 is already a mask :
    from gpio.h: #define GPIO_Pin_4 (BIT(4)) 
    fron eagle_soc.h #define BIT(nr)     (1UL << (nr))

so you must use it "as is".
Example: "....  .pin_bit_mask = GPIO_Pin_4 |  GPIO_Pin_5" etc. 

You might also be interested in this sdk bug (still open):
https://github.com/espressif/ESP8266_RTOS_SDK/pull/1071

Regards.

**Comment by bertmelis** [comment]
OK, so the example is terribly wrong but the SDK is right (luckily)

**Comment by dsptech** [comment]
Hi,
the example is right because GPIO_OUTPUT_IO_0 and GPIO_OUTPUT_IO_1 are not masks. 

#define GPIO_OUTPUT_IO_0    15
#define GPIO_OUTPUT_IO_1    16
#define GPIO_OUTPUT_PIN_SEL  ((1ULL<<GPIO_OUTPUT_IO_0) | (1ULL<<GPIO_OUTPUT_IO_1))

it is the same of
#define GPIO_OUTPUT_PIN_SEL   (GPIO_Pin_15|GPIO_Pin_16)

by the way, I think the the proper definitions of D0 and D1 are:
#define D0 16
#define D1 5

because the gpio functions (other than the configuration) require a "pure" pin number instead.
Regards.
