### ISSUE TITLE
Multi thread lwip bug?

### ISSUE THREAD

**Issue by knergy** [espressif/ESP8266_RTOS_SDK#115]
# Symptom
Opened socket never released even though calling socket_close()  function.
So free socket dry up and all tcp/ip communication stops.
( socket_close() internally defined as lwip_close_mt() )

# Fix
  Add a line shown below just behind line number 349 in ESP8266_RTOS_SDK/third_party/lwip/api/multi-threads/socket_mt.c  
`SOCK_MT_SET_SHUTDOWN(s, SOCK_MT_SHUTDOWN_OK);`

# Background
ESP8266_IOT_PLATFORM needs this SDK.
I wrote compiled software to my ESP-WROOM-02 module.
During SmartConfig through web browser, top web page implemented in ESP8266_IOT_PLATFORM/html/plug/index.html never appears.
At that time, logs out from serial port shows  
```
index  1, sockfd 4, dummy ?
index  2, sockfd 5, dummy ?
....
```

**Comment by knergy** [comment]
Move to pull request.

**Comment by llymaximus** [comment]
@knergy Hi, i have used single-thread task and multiple-thread task to open and close sockets, and the test result looks fine. If the problem still appears on your side, could you please provide some test code for us to debug this?

**Comment by knergy** [comment]
Hi, llymaximus.
Thank you for your confirmation about my pull request.
I can send my source code which based on  ESP8266_IOT_PLATFORM and includes a little my own change.
I don't know how to send. Do you have any good idea?

**Comment by llymaximus** [comment]
@knergy Hi, you can just compress your code and select them as an attachment while writing a comment for this issue.

**Comment by knergy** [comment]
You can test multi thread library in ESP_IOT_PLATFORM which provided Espressif as SDK.
My source code is almost same with it.
I just started to confirm configuring my ESP-WROOM-02 and found this problem.

**Comment by FayeY** [comment]
Sorry that we cannot reproduce this problem, is there any update about this issue? Does it persist with the latest SDK?
