### ISSUE TITLE
libfreertos.a problem when generated in1.4

### ISSUE THREAD

**Issue by karawin** [espressif/ESP8266_RTOS_SDK#119]
Strange problem. My application works very well with the libfreertos.a from ESP8266_RTOS_SDK-1.4.x
But when it is generated in third_party (the size is bigger) the application crashs.
gcc 4.8.2

connected with karawin2, channel 1
ip:192.168.1.41,mask:255.255.255.0,gw:192.168.1.254
saveDeviceSettings
set1 startaddr: 0, size:100, maxsize: 1000, sector: 3e0000, eebuf: 3fffb638
Fatal exception (0): 
epc1=0x4024c2a4
epc2=0x00000000
epc3=0x400043df
epcvaddr=0x00000000
depc=0x00000000
rtn_add=0x401032b9

With
4024c2a4 <vPortEnterCritical>:
**4024c2a4:	fdc521        	l32r	a2, 4024b9b8 <base64_encode_blockend+0xa8>**
4024c2a7:	000222        	l8ui	a2, a2, 0
4024c2aa:	01f256        	bnez	a2, 4024c2cd <vPortEnterCritical+0x29>
4024c2ad:	fffa21        	l32r	a2, 4024c298 <xPortStartScheduler+0x34>
4024c2b0:	000232        	l8ui	a3, a2, 0
4024c2b3:	0d1326        	beqi	a3, 1, 4024c2c4 <vPortEnterCritical+0x20>
4024c2b6:	006340        	rsil	a4, 3
4024c2b9:	fff831        	l32r	a3, 4024c29c <xPortStartScheduler+0x38>

401032ac <ppEnqueueRxq>:
401032ac:	f0c112        	addi	a1, a1, -16
401032af:	0129      	s32i.n	a2, a1, 0
401032b1:	1109      	s32i.n	a0, a1, 4
401032b3:	f45001        	l32r	a0, 401003f4 <Cache_Read_Enable_New+0x178>
401032b6:	0000c0        	callx0	a0
**401032b9:	050c      	movi.n	a5, 0**
401032bb:	ff6a21        	l32r	a2, 40103064 <lmacRxDone+0x1d4>
401032be:	0138      	l32i.n	a3, a1, 0
401032c0:	3228      	l32i.n	a2, a2, 12

The problem appears at some random time.
What is the difference between the libfreertos.a from the github delivery and the one generated?

**Comment by 27-301** [comment]
That version put some critical code into flash by default, need to put iRAM by default, please try the latest version.
