### ISSUE TITLE
[SDK8266-81] espconn source code missing mdns functions

### ISSUE THREAD

**Issue by HomeACcessoryKid** [espressif/ESP8266_RTOS_SDK#127]
In august the source code of espconn has been added a third party source code
The header file refers to the mdns routines.
However, the source code files are missing these mdns functions.

Can you also indicate what is the reason of offering the espconn code of the nonos branch (is it??)

Please add the missing files to the repository and verify it all works?
Thanks

**Comment by donghengqaz** [comment]
This Function may be supported at later version, to be waiting please.

**Comment by FayeY** [comment]
It is recommended to use the new ESP8266 RTOS SDK V3.0 or later versions which is in ESP-IDF style.  We just provide the mdns function on GitHub recently, please have a try. Thanks.
