### ISSUE TITLE
conflicts between libmain.a and libcirom.a (multiple definitions)

### ISSUE THREAD

**Issue by seixasb** [espressif/ESP8266_RTOS_SDK#129]
I have a problem while using the function assert defined in assert.h in my code.
When compiling I receive the following error:

> .../ESP8266_RTOS_SDK//lib/libmain.a(routines.o): In function 'abort':
(.text+0x70): multiple definition of 'abort'
.../ESP8266_RTOS_SDK//lib/libcirom.a(lib_a-abort.o):home/wjg/Repo/esp-open-sdk/crosstool-NG/.build/src/newlib-2.0.0/newlib/libc/stdlib/abort.c:55: first defined here
collect2: error: ld returned 1 exit status
.../ESP8266_RTOS_SDK//Makefile:403: recipe for target '.output/eagle/debug/image/eagle.app.v6.out' failed
make: *** [.output/eagle/debug/image/eagle.app.v6.out] Error 1

I have noticed that others have also found confilcts between both libraries here:
https://github.com/espressif/ESP8266_RTOS_SDK/issues/54

**Comment by donghengqaz** [comment]
On newer banrch(v3.0 or master), using the better newlib supporting.
