### ISSUE TITLE
FreeRTOS 10.0.0

### ISSUE THREAD

**Issue by Zaltora** [espressif/ESP8266_RTOS_SDK#134]
It possible to update freertos to the last api ?
This version since 7.5.2 get great features.

**Comment by 27-301** [comment]
Great advice, will do it after SDK v2.0.0 released.

**Comment by 27-301** [comment]
@Zaltora FreeRTOS is upgraded to v10 in master branch, but please note that the SDK frame is changed to idf style, for use, please read README firstly. Thanks

**Comment by Zaltora** [comment]
Great, I will wait a stable release to port my program (SDK 3.0). Nice work
