### ISSUE TITLE
use the MQTT demo ，that cannot connect to service

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_RTOS_SDK#137]
自从你们更新了MQTT的demo，之后 我就无法连接至服务器了，报错如下：连接不需要SSL或TLS

your ESP SSL/TLS configuration is -1536300.[0:NO_TLS	1:TLS_WITHOUT_AUTHENTICATION	2ONE_WAY_ANTHENTICATION	3TWO_WAY_ANTHENTICATION]
TCP: Connect to ip  127.0.0.1:1883

**Comment by FayeY** [comment]
你好，请问，具体是哪个 MQTT demo，能否提供一下链接？

**Comment by xuhongv** [comment]
@FayeY 问题已经解决，谢谢回应
