### ISSUE TITLE
restart while dhcp 

### ISSUE THREAD

**Issue by g-gabber** [espressif/ESP8266_RTOS_SDK#14]
ApiMsgMutex created
idle_task_hdl : 3fff3f98
tim_task_hdl : 3fff41f0
xPortStartScheduler

OS SDK ver: 0.0.5 compiled @ Dec 25 2014 17:57:07
phy ver: 273, pp ver: 6

SDK version:0.0.5
mode : sta(18:fe:34:99:99:58) + softAP(1a:fe:34:99:99:58)
add if0
add if1
bcn 100
Hello, welcome to client!
C > socket ok!
S > create socket: 2
S > bind port: 80
b
b
b
scandone
add 0
aid 6
aid end
cnt

connected with edgy&di, channel 9
dhcp client start...
Fatal exception (28):
epc1=0x4025ba60
epc2=0x00000000
epc3=0x402430bd
epcvaddr=0x00000098
depc=0x00000000

**Comment by wizhippo** [comment]
When I compile and third_party libs and use them I get the same behaviour

**Comment by wizhippo** [comment]
I have tried this with the latest libmain with the larger stackand still have this issue.  It only happens for me when using my own compiled lwip.
