### ISSUE TITLE
[SDK8266-76] espconn_mdns_init() does not compile on the RTOS SDK 

### ISSUE THREAD

**Issue by snicolasss** [espressif/ESP8266_RTOS_SDK#149]
I've been using the RTOS SDK for a while and used other APIs, and now I got the requirement of making my devices discoverable over mDNS.

I tried with the following code:

`void user_init(void)
{
    printf("SDK version:%s\n", system_get_sdk_version());

    mdns_init();
}

static void mdns_init(void)
{
  struct ip_info ipConfig;
  struct mdns_info info;

  wifi_get_ip_info(STATION_IF, &ipConfig);
  if (!(wifi_station_get_connect_status() == STATION_GOT_IP && ipConfig.ip.addr != 0)) {
    printf("Cannot read station configuration\n");
    return;
  }

  info.host_name = "espmodule";
  info.ipAddr = ipConfig.ip.addr; //ESP8266 station IP
  info.server_name = "module01";
  info.server_port = 8080;
  info.txt_data[0] = "version = now";
  info.txt_data[1] = "user1 = data1";
  info.txt_data[2] = "user2 = data2";
  // info->txt_data[3] = "vendor = me";
  espconn_mdns_init(&info);
  // espconn_mdns_server_register();
  espconn_mdns_enable();
`}``

But the compilation process fails in the liker saying that espconn_mdns_init and espconn_mdns_enable are undefined references.

Are those function available in espconn.a? or not?

If they are. Do you have an example of how to use them?

Thanks in advance.

**Comment by FayeY** [comment]
It is recommended to use the new ESP8266 RTOS SDK V3.0 or later versions which is in ESP-IDF style.  We just provide the mdns function on GitHub recently, please have a try. Thanks.
