### ISSUE TITLE
lwIP sys_now() function bug

### ISSUE THREAD

**Issue by westmere** [espressif/ESP8266_RTOS_SDK#150]
lwip implement arch/sys_arch.c

`u32_t sys_now(void)
{
   return xTaskGetTickCount();
}`
It returns the number of ticks from startup, not the number of milliseconds!

It should be:
`return xTaskGetTickCount() * portTICK_PERIOD_MS;`

**Comment by Junhao-Espressif** [comment]
Hi @westmere 

We know that it returns the number of ten milliseconds, not the number of milliseconds.
You can use this function as defined in timers.c: 
```
/*return the current system time(ms)*/
#define GET_SYS_TIME_NOW (sys_now() * portTICK_RATE_MS)
```
We might modify and test in the next version of SDK.

Thanks for your attention!
