### ISSUE TITLE
EVENT_SOFTAPMODE_PROBEREQRECVED

### ISSUE THREAD

**Issue by qrsrjm** [espressif/ESP8266_RTOS_SDK#152]
最新SDK 在STA+AP模式下启动TCP server， 当客户端连上后发送数据传输后一段时间就会一直出现打印
“send EVENT_SOFTAPMODE_PROBEREQRECVED error”

**Comment by 27-301** [comment]
Which commit do you use? Since the SDK is always update. BTW, can you share the demo code and the detailed re-produce steps?

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details.

**Comment by philar** [comment]
遇到同样的问题，请问最好怎么解决的？

**Comment by ustbzm** [comment]
遇到同样问题，哪位有解决方案呀
