### ISSUE TITLE
[SDK8266-75] UDP getting error or not able to send the packet

### ISSUE THREAD

**Issue by Rajkumar181** [espressif/ESP8266_RTOS_SDK#156]
I have enabled both Station mode and AP mode with UDP protocol, it was working fine i.e getting the packets on both (i.e. station mode as well as AP mode). If i disconnect my mobile from AP mode abruptly,  afterwards i am not getting data from both sides. UDP protocol API sento() is returning (-1).

**Comment by 27-301** [comment]
Can you provide demo code to reproduce this issue? also log. Otherwise, others need to write the code and try, this will cost time.

And if you disconnect your mobile normally? is it OK? How you disconnect your mobile from AP? power off the phone?

**Comment by Rajkumar181** [comment]
yes i disconnected mobile normally , i just switch off my mobile wifi so it disconnected from ESP AP.

just now i found the reason  of this i trying to send the data to this IP 192.168.4.2.

**Comment by Rajkumar181** [comment]
I written a sample code for testing purpose. 


This is console print --



connected with Manas, channel 11                                                
dhcp client start...                                                            
sta connected                                                                   
ip:192.168.2.31,mask:255.255.255.0,gw:192.168.2.1                               
sta got ip ,create task and free heap size is 48360                             
add 1                                                                           
aid 1                                                                           
station: c4:0b:cb:d6:09:55 join, AID = 1                                        
EVENT_SOFTAPMODE_STACONNECTED                                                   
station: c4:0b:cb:d6:09:55 leave, AID = 1                                       
rm 1                                                                            
EVENT_SOFTAPMODE_STADISCONNECTED                                                
Sending error on DHCP broadcast[1073705526]                                     
Sending error on DHCP broadcast[1073705526]                                     
Sending error on DHCP broadcast[1073705526]                                     
Sending error on DHCP broadcast[1073705526]                                     
Sending error on DHCP broadcast[1073705526]                                     
Sending error on DHCP broadcast[1073705526]                                     
Sending error on DHCP broadcast[1073705526]                                     
Sending error on DHCP broadcast[1073705526]


Testing code ----



/******************************************************************************
 * Copyright 2013-2014 Espressif Systems (Wuxi)
 *
 * FileName: user_main.c
 *
 * Description: entry file of user application
 *
 * Modification history:
 *     2015/7/3, v1.0 create this file.
*******************************************************************************/

#include "esp_common.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "esp_wps.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include "user_config.h"


#include "lwip/sockets.h"
#include "lwip/dns.h"
#include "lwip/netdb.h"
#include "espressif/espconn.h"
#include "espressif/airkiss.h"

//#include "BoardConfig.h"
//#include "Relaycontrol.h"
#include "gpio.h"
//#include "eeprom.h"

#include "esp_wifi.h"
/*********** Global Declaration *********************/

bool wifiConnStatus = false;

bool  wiFiAPConnStatus = false;
void wifi_event_handler_cb(System_Event_t *event)
{
   
    if (event == NULL) {
        return;
    } 

    switch (event->event_id) {
        case EVENT_STAMODE_GOT_IP:
            os_printf("sta got ip ,create task and free heap size is %d\n", system_get_free_heap_size());  
	    wifiConnStatus = true;
            break;
        case EVENT_STAMODE_CONNECTED:
            os_printf("sta connected\n");
            break;

      case EVENT_STAMODE_DISCONNECTED:
            wifi_station_connect();
	    wifiConnStatus = false;
	    //os_printf("EVENT_STAMODE_DISCONNECTED\n");
            break;
	case EVENT_STAMODE_DHCP_TIMEOUT:
	    os_printf("EVENT_STAMODE_DHCP_TIMEOUT\n");
	     break;
 	case EVENT_SOFTAPMODE_STACONNECTED:
	    // if any device connected with AP 
	    wiFiAPConnStatus = true;           
	    os_printf("EVENT_SOFTAPMODE_STACONNECTED\n");
	     break;
	case EVENT_SOFTAPMODE_STADISCONNECTED:
	  //  wifi_station_disconnect();
	   // wifi_station_connect();
	   // wifi_station_get_auto_connect();
		wiFiAPConnStatus = false;
	    os_printf("EVENT_SOFTAPMODE_STADISCONNECTED\n");
	     break;
	case EVENT_SOFTAPMODE_PROBEREQRECVED:
	  //  os_printf("EVENT_SOFTAPMODE_PROBEREQRECVED\n");
	     break;
        default:
            break;
    }
}


void wifi_station_config(char *sta_ssid, char *sta_pass)
{
	os_printf("Config SSID [%s] PASS [%s]\n",sta_ssid, sta_pass);
	wifi_station_disconnect();
	struct station_config config;
	bzero(&config, sizeof(struct station_config));
   	sprintf(config.ssid, sta_ssid);
    	sprintf(config.password, sta_pass);
    	wifi_station_set_config(&config);
	wifi_station_connect();
}
void wifi_ap_config(char *ap_ssid, char *Ap_pass)
{        
	struct softap_config ap_config;
	bzero(&ap_config, sizeof(struct softap_config));
	sprintf(ap_config.ssid, ap_ssid);
	sprintf(ap_config.password, Ap_pass);
	ap_config.authmode = AUTH_WPA_WPA2_PSK;
	ap_config.ssid_len = 0; // or its actual SSID length
	ap_config.max_connection = 4;
	wifi_softap_set_config(&ap_config);   
}
void UDP_Receive(void *pvParameter)
{
	int udpSocket, nBytes,k=0;
	char TempRxpacket[100];
	struct sockaddr_in serverAddr, clientAddr;
	
	socklen_t addr_size;
	int i=0;

	/*Create UDP socket*/
	udpSocket = socket(PF_INET, SOCK_DGRAM, 0);

	/*Configure settings in address struct*/
	serverAddr.sin_family = AF_INET;
	serverAddr.sin_port = htons(23822);
	serverAddr.sin_addr.s_addr = INADDR_ANY;
	memset(serverAddr.sin_zero, '\0', sizeof serverAddr.sin_zero);  

	/*Bind socket with address struct*/
	if(bind(udpSocket, (struct sockaddr *) &serverAddr, sizeof(serverAddr)) <0)
	{
		close(udpSocket);
       		os_printf("Failed to bind socket\r\n");
	}

	/*Initialize size variable to be used later on*/
	//addr_size = sizeof serverStorage;
	addr_size = sizeof clientAddr;
	memset(TempRxpacket, 0, 100);
	
	for(;;)
	{
		os_printf("Trying To Receive New Packet\n");
		memset(TempRxpacket, '\0', sizeof(TempRxpacket));
		nBytes = recvfrom(udpSocket,TempRxpacket,100,0,(struct sockaddr *)&clientAddr, &addr_size);
		if(nBytes>0)
		{
			printf("Received New Packet[%d]  [%s]\n",nBytes,TempRxpacket);			
			
		/******* end code **********************/ 
		}
	}
	vTaskDelete(NULL);
}


void UDP_Send(void *pvParameter)
{
	 int udpSendSocket,i,j;
	 struct sockaddr_in SendserverAddr;
	 socklen_t Sendaddr_size;
         memset(&SendserverAddr,0,sizeof(SendserverAddr));
	/*Create UDP socket*/
	udpSendSocket = socket(PF_INET, SOCK_DGRAM, 0);

	/*Configure settings in address struct*/
	SendserverAddr.sin_family = AF_INET;
	SendserverAddr.sin_port = htons(23577);
	SendserverAddr.sin_addr.s_addr = inet_addr("192.168.2.255");
	Sendaddr_size = sizeof( struct sockaddr_in);

	char Sendmsg[50];
	memset(Sendmsg,0,sizeof(Sendmsg));
	os_printf("UDP_Send thread is running\n");
	
	
	Sendmsg[0] = 'a'; Sendmsg[1] = 'b'; Sendmsg[2] = 'c'; Sendmsg[3] = 'd'; Sendmsg[4] = 'e'; Sendmsg[5] = 'f'; Sendmsg[6] = 'g';
	Sendmsg[7] = 'h'; Sendmsg[8] = 'i'; Sendmsg[9] = 'j'; Sendmsg[10] = 'k'; Sendmsg[11] = 'l'; Sendmsg[12] = 'm'; Sendmsg[13] = 'n'; 		Sendmsg[14] = 'a'; Sendmsg[15] = 'a'; Sendmsg[16] = 'a'; Sendmsg[17] = 'a'; Sendmsg[18] = 'a'; Sendmsg[19] = 'a'; Sendmsg[20] = 'a'; 		Sendmsg[21] = 'a'; Sendmsg[22] = 'a'; Sendmsg[23] = 'a'; Sendmsg[24] = 'a'; Sendmsg[25] = 'a'; Sendmsg[26] = 'a'; Sendmsg[27] = 'a'; 		Sendmsg[28] = '1'; Sendmsg[29] = '2'; Sendmsg[30] = '3'; Sendmsg[31] = '4'; Sendmsg[32] = '5'; Sendmsg[33] = '\0';
	for(;;)
	{
	    if(wifiConnStatus == true)
	    {
		SendserverAddr.sin_addr.s_addr = inet_addr("192.168.2.255");
		if(sendto(udpSendSocket,(void *)&Sendmsg[0],strlen(Sendmsg),0, (struct sockaddr *)&SendserverAddr,Sendaddr_size)<0)
		{
			os_printf("Sending error on DHCP broadcast[%d]\n",&SendserverAddr.sin_port);
			
		}
		SendserverAddr.sin_addr.s_addr = inet_addr("192.168.4.2");
		if(sendto(udpSendSocket,(void *)&Sendmsg[0],strlen(Sendmsg),0, (struct sockaddr *)&SendserverAddr,Sendaddr_size)<0)
		{
			os_printf("Sending error on DHCP broadcast[%d]\n",&SendserverAddr.sin_port);
			
		}
	    }
	    if(wiFiAPConnStatus == true)
	     {				
		SendserverAddr.sin_addr.s_addr = inet_addr("192.168.4.255");            
		
		if(sendto(udpSendSocket,(void *)&Sendmsg[0],strlen(Sendmsg),0, (struct sockaddr *)&SendserverAddr,Sendaddr_size)<0)
		{
			os_printf("Sending error on AP broadcast[%d]\n",&SendserverAddr.sin_port);
		}
		
	     }	     
		vTaskDelay(450 / portTICK_RATE_MS); 
		 
	}
	vTaskDelete(NULL);
}

/******************************************************************************
 * FunctionName : user_rf_cal_sector_set
 * Description  : SDK just reversed 4 sectors, used for rf init data and paramters.
 *                We add this function to force users to set rf cal sector, since
 *                we don't know which sector is free in user's application.
 *                sector map for last several sectors : ABCCC
 *                A : rf cal
 *                B : rf init data
 *                C : sdk parameters
 * Parameters   : none
 * Returns      : rf cal sector
*******************************************************************************/
uint32 user_rf_cal_sector_set(void)
{
    flash_size_map size_map = system_get_flash_size_map();
    uint32 rf_cal_sec = 0;

    switch (size_map) {
        case FLASH_SIZE_4M_MAP_256_256:
            rf_cal_sec = 128 - 5;
            break;

        case FLASH_SIZE_8M_MAP_512_512:
            rf_cal_sec = 256 - 5;
            break;

        case FLASH_SIZE_16M_MAP_512_512:
        case FLASH_SIZE_16M_MAP_1024_1024:
            rf_cal_sec = 512 - 5;
            break;

        case FLASH_SIZE_32M_MAP_512_512:
        case FLASH_SIZE_32M_MAP_1024_1024:
            rf_cal_sec = 1024 - 5;
            break;
        case FLASH_SIZE_64M_MAP_1024_1024:
            rf_cal_sec = 2048 - 5;
            break;
        case FLASH_SIZE_128M_MAP_1024_1024:
            rf_cal_sec = 4096 - 5;
            break;
        default:
            rf_cal_sec = 0;
            break;
    }

    return rf_cal_sec;
}


void user_init(void)
{
	uint8_t newmac[6];

	uart_div_modify(0, UART_CLK_FREQ / 115200);
	os_delay_us(1000);
	os_printf("SDK version:%s %d\n", system_get_sdk_version(), system_get_free_heap_size());
	wifi_station_config("Manas", "iramtech123");
	wifi_set_opmode(STATIONAP_MODE);

	//wifi_set_opmode(STATION_MODE);
	wifi_set_event_handler_cb(wifi_event_handler_cb); 
	wifi_station_connect();
	wifi_station_get_auto_connect();

	os_delay_us(1000);
	os_delay_us(1000);

	wifi_ap_config("ESP8266", "esp1234567");	

	
	xTaskCreate(UDP_Receive, "UDP_Receive", 2048, NULL, 2, NULL);
	xTaskCreate(UDP_Send, "UDP_Send", 2217,NULL,5,NULL );

	
    
}

**Comment by Rajkumar181** [comment]
I written a sample code for testing purpose.

This is console print --

connected with Manas, channel 11
dhcp client start...
sta connected
ip:192.168.2.31,mask:255.255.255.0,gw:192.168.2.1
sta got ip ,create task and free heap size is 48360
add 1
aid 1
station: c4:0b:cb:d6:09:55 join, AID = 1
EVENT_SOFTAPMODE_STACONNECTED
station: c4:0b:cb:d6:09:55 leave, AID = 1
rm 1
EVENT_SOFTAPMODE_STADISCONNECTED
Sending error on DHCP broadcast[1073705526]
Sending error on DHCP broadcast[1073705526]
Sending error on DHCP broadcast[1073705526]
Sending error on DHCP broadcast[1073705526]
Sending error on DHCP broadcast[1073705526]
Sending error on DHCP broadcast[1073705526]
Sending error on DHCP broadcast[1073705526]
Sending error on DHCP broadcast[1073705526]

**Comment by Rajkumar181** [comment]
Find the zip file.
[esp8266.tar.gz](https://github.com/espressif/ESP8266_RTOS_SDK/files/1818333/esp8266.tar.gz)

**Comment by Rajkumar181** [comment]
Any update why it is happening , how we can fix the bug.

**Comment by fafactx** [comment]
sta and ap mode is not full duplex，so you can use only one mode to test you demo at a time。

**Comment by fafactx** [comment]
void user_init(void)
{
	uint8_t newmac[6];

	uart_div_modify(0, UART_CLK_FREQ / 115200);
	os_delay_us(1000);
	os_printf("SDK version:%s %d\n", system_get_sdk_version(), system_get_free_heap_size());
	wifi_station_config("Manas", "iramtech123");
	wifi_set_opmode(STATIONAP_MODE);

	//wifi_set_opmode(STATION_MODE);
	wifi_set_event_handler_cb(wifi_event_handler_cb); 
	wifi_station_connect();
	wifi_station_get_auto_connect();

	os_delay_us(1000);
	os_delay_us(1000);

	wifi_ap_config("ESP8266", "esp1234567");	

	
	xTaskCreate(UDP_Receive, "UDP_Receive", 2048, NULL, 2, NULL);
	xTaskCreate(UDP_Send, "UDP_Send", 2217,NULL,5,NULL );

	
    
}


in this pdf 20a-esp8266_rtos_sdk_programming_guide_en.pdf

tell us task stack should from 176 to 512 ，this not BYTE for a calc，reference freertos readme。
you can try this。

**Comment by FayeY** [comment]
Sorry that we have refactored the SDK to be ESP-IDF style, would you like to have a try with our latest SDK? If the issue persists, please feel free to reopen or submit a new one. Thanks.
