### ISSUE TITLE
MQTT: Cannot subscribe more than 5 topics

### ISSUE THREAD

**Issue by MohammadAhmad1990** [espressif/ESP8266_RTOS_SDK#157]
even after changing  
`"#define MAX_MESSAGE_HANDLERS 5" to "#define MAX_MESSAGE_HANDLERS 8"
`

I am still not able to subscribe more than 5 topics 
I get the following error 
Return code from MQTT subscribe is -1

kindly help

**Comment by Governa** [comment]
Have you recompiled the MQTT library?

```
cd <SDK>/third_party
./make_lib.sh mqtt
```

**Comment by MohammadAhmad1990** [comment]
No I have not. I will give it a try next time. Thanks

**Comment by FayeY** [comment]
Any update? Is this issue solved now?

**Comment by MohammadAhmad1990** [comment]
I am sorry I did not get time to verify it.
