### ISSUE TITLE
有人知道RTOS_SDK 的 boot 源代码开源了吗？想修改下默认波特率。

### ISSUE THREAD

**Issue by fafactx** [espressif/ESP8266_RTOS_SDK#159]
I'd like to revise the baud rate for the next boot. I don't know where the source code is？
Thanks for reply

**Comment by 27-301** [comment]
Not release now, which baud rate do you want to use?

**Comment by dupeige** [comment]
yes,i gree

**Comment by dupeige** [comment]
I want to use of arduino

**Comment by dupeige** [comment]
我也想改变其比特率。想用它与arduino通信

**Comment by Derekxiong** [comment]
I think the easy way is too change the baud rate in the arduino.

**Comment by fafactx** [comment]
becasue of the ocs = 26M ,then defautl the boot v1.6 or bootv1.7 will run as baud rate = 74880，
My question is if the boot can open source for me to change the default baud rate.
板卡时钟是26M情况下，boot版本对应默认波特率是74880，这个是否可以开源，我需要一个更通用波特率。

**Comment by FayeY** [comment]
Hi, so sorry that the boot is not open source, and the startup baud rate cannot be changed. You can only change the baudrate in user_init. Sorry for the inconvenience.
