### ISSUE TITLE
Unable to make pull down work

### ISSUE THREAD

**Issue by riban-bw** [espressif/ESP8266_RTOS_SDK#16]
I have been unable to enable the internal pull down resistor for any pin. It looks like the following macro should work:

<code>
SET_PERI_REG_MASK(PIN_NAME, PERIPHS_IO_MUX_PULLDWN)
</code>

but it does not.

**Comment by riban-bw** [comment]
Why close this issue without any comment on what the resolution is?

**Comment by xiongyumail** [comment]
Hi @riban-bw ,
I'm sorry to close the question.

Only RTC_IO(IO16) can internal pull down.
You can choose external pull down.
The new SDK GPIO driver can avoid this problem very well.
