### ISSUE TITLE
master code err

### ISSUE THREAD

**Issue by donny681** [espressif/ESP8266_RTOS_SDK#163]
I'm so glad to see that ESP8266 rtos sdk modify the framework to esp-idf style.Althought I compile the example , the programme can't run in the esp8266.
`ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x40100000, len 2592, room 16 
0x40100000: _stext at ??:?

tail 0
chksum 0xf3
load 0x3ffe8000, len 764, room 8 
tail 4
chksum 0x92
load 0x3ffe82fc, len 676, room 4 
tail 0
chksum 0x22
csum 0x22

2nd boot version : 1.7(5d6f877)
SPI Speed : 40MHz
SPI Mode : DIO
SPI Flash Size & Map: 32Mbit(512KB+512KB)
jump to run user1 @ 1000
` 
Can you tell me how to compile the new sdk?

**Comment by wujiangang** [comment]
hi, @donny681 Thank you for your try, and very sorry that the documents is limited now.

You can use `make erase_flash` to erase all flash. It's an option, just want to make the environment clean.

Some steps like these:
`make defconfig`  or `make menuconfig` to configure your project, choose your serial port, etc.
`make` --- compile your project
`make flash` --- program bootloader, user1.bin, init_data.bin, (for first time program, use it)
`make app_flash` --- program user1.bin, (if already programed bootloader and init data bin, then just use this command)
`make monitor`

Here is my log:
```
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 2592, room 16 
0x40100000: _stext at ??:?

tail 0
chksum 0xf3
load 0x3ffe8000, len 764, room 8 
tail 4
chksum 0x92
load 0x3ffe82fc, len 676, room 4 
tail 0
chksum 0x22
csum 0x22

2nd boot version : 1.7(5d6f877)
SPI Speed : 40MHz
SPI Mode : QIO
SPI Flash Size & Map: 16Mbit(512KB+512KB)
jump to run user1 @ 1000

OS SDK ver: 2.0.0(21b4121) compiled @ Apr 17 2018 20:33:30
phy ver: 1055_1, pp ver: 10.7

rf cal sector: 507
SDK version:2.0.0(21b4121)
mode : softAP(a2:20:a6:04:0d:74)
tcpip_adapter_wifi.c line: 96 start netif[1]
tcpip_adapter_wifi.c line: 134 Malloc netif:1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
add if1
bcn 100
```
