### ISSUE TITLE
字符集转换

### ISSUE THREAD

**Issue by JeremyHe-cn** [espressif/ESP8266_RTOS_SDK#166]
请问 这个 sdk 有字符集转换相关的api吗？如 utf-8 转 gbk

**Comment by 27-301** [comment]
maybe no, you can contribute it :)

**Comment by FayeY** [comment]
非常抱歉，我们当前没有此项相关的开发计划。建议您可以自行实现相关功能。
感谢您对 ESP8266 的关注！
