### ISSUE TITLE
[TW#22831] Can't connect to AP

### ISSUE THREAD

**Issue by frenzox** [espressif/ESP8266_RTOS_SDK#168]
Hi,
I'm having a hard time trying to connect the ESP8266 to the PACE V5471 AP when it's working on 11g and 11g+n mode.

Through Wireshark I can see the association fails with status code 0x0019 (Association denied due to requesting STA not supporting the Short Slot Time option).

**Comment by Junhao-Espressif** [comment]
Hi @frenzox 

0x19 means "TDLS direct-link teardown due to TDLS peer STA unreachable via the TDLS direct link".

Our current code does not support DTLS. Thanks!
