### ISSUE TITLE
Configurable configTICK_RATE_HZ ?

### ISSUE THREAD

**Issue by Mr-Techtron** [espressif/ESP8266_RTOS_SDK#176]
Is there other way to configure the tick of FreeRTOS, since the change made in the FreeRTOSConfig.h doesn't make a difference?

**Comment by 27-301** [comment]
If you use the master branch, you can modify configTICK_RATE_HZ in FreeRTOSConfig.h, then recompile your code.

**Comment by FayeY** [comment]
Closing this, please feel free to reopen if this is still an issue.

**Comment by Mr-Techtron** [comment]
Sorry for late reply, as you've told I've tried it in my linux environment but still there is no effect after changing configTICK_RATE_HZ and recompiling. I've been waiting for months for the developers at ESPRESSIF to make it configurable. Or I've miss something here?
