### ISSUE TITLE
[TW#22589] mqtt运行出错

### ISSUE THREAD

**Issue by donny681** [espressif/ESP8266_RTOS_SDK#178]
我尝试你们master-> mqtt项目，程序逻辑是每一秒上传一次数据，但是发现上传一次之后就停止发送了，程序就卡死在线程里面，我使用服务器是demo iot.eclipse.org服务器

**Comment by donny681** [comment]
终于找到原因，请查看ESP8266_RTOS_SDK/components/mqtt/source/library/MQTTClient.c 第621行由于在发送过程中，信号量被锁住，导致程序一直在等待发出信号量。

**Comment by donny681** [comment]
终于找到原因，请查看ESP8266_RTOS_SDK/components/mqtt/source/library/MQTTClient.c 第621行由于在发送过程中，信号量被锁住，导致程序一直在等待发出信号量。

**Comment by xcguang** [comment]
这个锁一直退不出吗？MQTTClientInit 时，设置的 timeout 时多少？

**Comment by 27-301** [comment]
Can you try the master branch? just update mqtt and have some fixes.
