### ISSUE TITLE
[TW#22591] Error occured during compile for i2c using esp8266-freeRTOS v2.0

### ISSUE THREAD

**Issue by LangleyJack** [espressif/ESP8266_RTOS_SDK#181]
#include "esp_common.h"
//#include "driver/gpio.h"
//#include "i2c_master.h"
#include "gpio.h"
#include "driver/i2c_master.h"

uint32 user_rf_cal_sector_set(void) {
    .......
    return rf_cal_sec;
}

void user_init(void)
{
  i2c_master_gpio_init();
}     

I just test for esp8266 using freeRTOS to use i2c device, but I am met the following error. 
I searched for ETS_GPIO_INTR_DISABLE in gpio.h, but I could not find it. 

Am I using it wrong?

----- Error -----------------------------------------------------------------------------------------------------------------------
WARNING: Toolchain version is not supported: 1.22.0-60-g37b07f6
Expected to see version: 1.22.0-80-g6c4433a
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
WARNING: Compiler version is not supported: 
Expected to see version(s): 5.2.0
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
LD build/i2c.elf
/home/jack/test/esp8266/i2c/build/esp8266/libesp8266.a(i2c_master.o):(.irom0.literal+0x1c): undefined reference to `ETS_GPIO_INTR_DISABLE'
/home/jack/test/esp8266/i2c/build/esp8266/libesp8266.a(i2c_master.o):(.irom0.literal+0x20): undefined reference to `ETS_GPIO_INTR_ENABLE'
/home/jack/test/esp8266/i2c/build/esp8266/libesp8266.a(i2c_master.o): In function `i2c_master_init':
/home/jack/esp8266/ESP8266_RTOS_SDK/components/esp8266/driver/i2c_master.c:90: undefined reference to `ETS_GPIO_INTR_DISABLE'
/home/jack/test/esp8266/i2c/build/esp8266/libesp8266.a(i2c_master.o): In function `i2c_master_gpio_init':
/home/jack/esp8266/ESP8266_RTOS_SDK/components/esp8266/driver/i2c_master.c:116: undefined reference to `ETS_GPIO_INTR_ENABLE'
collect2: error: ld returned 1 exit status
/home/jack/esp8266/ESP8266_RTOS_SDK/make/project.mk:405: recipe for target '/home/jack/test/esp8266/i2c/build/i2c.elf' failed
make: *** [/home/jack/test/esp8266/i2c/build/i2c.elf] Error 1

**Comment by 27-301** [comment]
fixed in f82e9be7
