### ISSUE TITLE
编译get_start工程不通过

### ISSUE THREAD

**Issue by yellowway** [espressif/ESP8266_RTOS_SDK#182]
下载最新版本的SDK（与ESP32的结构一样，ESP32能正常编译，但ESP8266不能正常编译）。
执行make all

     ^
AR build/tcpip_adapter/libtcpip_adapter.a
LD build/project_template.elf
。。。
/home/huangwei/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld:/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/lib/libcrypto.a(aes-internal-enc.o): warning: incompatible Xtensa configuration (ABI does not match)
/home/huangwei/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld:/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/lib/libcrypto.a(aes-internal.o): warning: incompatible Xtensa configuration (ABI does not match)
/home/huangwei/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld:/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/lib/libgcc.a(_cmpdf2.o): warning: incompatible Xtensa configuration (ABI does not match)
/home/huangwei/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld:/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/lib/libhal.a(clock.o): warning: incompatible Xtensa configuration (ABI does not match)
/home/huangwei/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld:/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/lib/libhal.a(int_asm--set_intset.o): warning: incompatible Xtensa configuration (ABI does not match)
/home/huangwei/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld:/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/lib/libcore.a(libc.o): warning: incompatible Xtensa configuration (ABI does not match)
/home/huangwei/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld:/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/lib/libnet80211.a(ieee80211_crypto_tkip.o): warning: incompatible Xtensa configuration (ABI does not match)
/home/huangwei/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld:/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/lib/libnet80211.a(ieee80211_crypto_wep.o): warning: incompatible Xtensa configuration (ABI does not match)
/home/Esp8266WorkLib/get-started/project_template/build/esp8266/libesp8266.a(xtensa_vectors.o):(.literal+0x48): undefined reference to `NMI_Handler'
/home/Esp8266WorkLib/get-started/project_template/build/esp8266/libesp8266.a(os_cpu_a.o): In function `_xt_timer_int':
/home/Esp8266WorkLib/ESP8266_RTOS_SDK/components/esp8266/source/os_cpu_a.S:229:(.text+0x79): dangerous relocation: call4: call target out of range: xTaskIncrementTick
collect2: error: ld returned 1 exit status
/home/Esp8266WorkLib/ESP8266_RTOS_SDK/make/project.mk:405: recipe for target '/home/Esp8266WorkLib/get-started/project_template/build/project_template.elf' failed
make: *** [/home/Esp8266WorkLib/get-started/project_template/build/project_template.elf] Error 1

root@hw-linuxPC:/home/Esp8266WorkLib/get-started/project_template#

**Comment by 27-301** [comment]
You use the cross tool for esp32, please use cross tool for esp8266. Please rm sdkconfig & sdkconfig.old in your project folder, then `make defconfig`, `make`.

**Comment by 27-301** [comment]
Toolchain, you can get from Arduino firstly:
{
              "host": "x86_64-pc-linux-gnu",
              "url": "https://github.com/esp8266/Arduino/releases/download/2.3.0/linux64-xtensa-lx106-elf-gb404fb9.tgz",
            },
            {
              "host": "i686-pc-linux-gnu",
              "url": "https://github.com/esp8266/Arduino/releases/download/2.3.0/linux32-xtensa-lx106-elf.tar.gz",
            },

**Comment by yellowway** [comment]
@27-301 thinks a lot!  your suggestion do works!

but ,i find an other question.
the compiler can not use float number.
eg.   my code is below:
float Pi=3.141592654;
printf("pi=%f\n",Pi);

after make flash,make monitor.

the printf shows 

pi=

that's all

**Comment by 27-301** [comment]
@yellowway You can post new issue for the float printf issue, close this issue firstly.
