### ISSUE TITLE
FreeRTOS allocating task stack in IRAM

### ISSUE THREAD

**Issue by FlavioBayer** [espressif/ESP8266_RTOS_SDK#183]
As per commit 2e899832829b16fd90a462ed9a2b1bb1070b1ea3 (which introduced iram as the second heap region): "Don't malloc task stack in iram;", which is currently not being enforced (it is just a regular malloc that allocate wherever it can), most likely due to changes after the recent FreeRTOS update:
https://github.com/espressif/ESP8266_RTOS_SDK/blob/f9b16e65b530e3c96a4cbde6d522363cc8745a0f/components/freertos/freertos/tasks.c#L775
This can be fixed by forcing the allocation of task stack to ignore iram, which can be achieve by replacing the line with:
```c
pxStack = ( StackType_t * ) pvPortMalloc( ( ( ( size_t ) usStackDepth ) * sizeof( StackType_t ) ) , __FILE__, __LINE__, false);
```

This may lead to problems like the one reported in https://github.com/espressif/ESP8266_RTOS_SDK/issues/180 where scanf/printf would not behave as expected.

I'll leave for the developers at Espressif to come up with a final solution, since I'm not an expert when dealing with memory regions of this MCU.
As of now, anyone facing this problem should be able to fix it by doing the change above.

By the way, looks like `MEMLEAK_DEBUG` is defined by default, which add some overhead when using the heap. This may cause issues when `pvPortMalloc` is called with only the allocation size as parameters (which seems to be the case in FreeRTOS, WolfSSL and others, including some precompiled libs in components/esp8266/lib/*.a), since other parameters like `use_iram` would not be defined and may lead to allocation in a random heap region. Shouldn't it be disabled by default, since almost anyone would really use it?

**Comment by 27-301** [comment]
@FlavioBayer Could you please help to do a test.

unzip this file to components/esp8266/source, and have a try. If test OK, we will merge this fix into master.

Thanks

[xtensa_vectors.S.zip](https://github.com/espressif/ESP8266_RTOS_SDK/files/2015958/xtensa_vectors.S.zip)

**Comment by 27-301** [comment]
@FlavioBayer The new SDK has a lot of changes, and will be improved continued. If you meet any issues, please report to us. Thanks
