### ISSUE TITLE
Soft reset after flash  (GIT8266O-6)

### ISSUE THREAD

**Issue by r315** [espressif/ESP8266_RTOS_SDK#191]
I'm using the version 2.0.0 of sdk on dev board without hw reset and found that on project configuration there is no option to select "soft_reset" after flashing: I manually add this feature on Kconfig.projbuild file but I think it wold be nice to have this option by default on the sdk.

**Comment by 27-301** [comment]
@r315 Thanks to point this. Can you raise a PR? So we can accept and merge it into master.

**Comment by FayeY** [comment]
Hi, is there any update about this issue?
