### ISSUE TITLE
请问能否开放串口升级协议

### ISSUE THREAD

**Issue by yellowway** [espressif/ESP8266_RTOS_SDK#193]
我司现在使用ESP8266做一个网络传输模块。esp8266作为从机。内部固件为非官方固件，用SDK编译后生成的自定义固件。出于保密，安全性和可靠性问题，板卡上还有一个MCU，一个FLASH，我们希望通过8266网络下载外挂MCU的固件以及8266自身固件到一个外挂flash中（非8266的FLASH）.然后通过MCU将固件烧写到ESP8266中。

我知道可以用烧录软件直接串口烧录，但是这种方式我们不能接受，因为不可能让用户这么做。另外我们不希望通过OTA的方式升级，因为这样只适合升级8266自身。因为8266和外面的MCU相当于是一个捆绑通信的关系。单独升级其中一个会导致整个系统不能使用。

所以我希望通过将MCU文件和8266文件首先下载到外部FLAH里面。然后通过MCU的BOOT将文件分别写入MCU的APP区域和ESP8266的FLAH,从而保证系统的可靠升级，以及代码的配套关系。

请问有没有相关的文档和协议？谢谢？

实在不行只能用串口抓码工具破解码流了。但是这个比较耗时。请帮忙回答。谢谢！

**Comment by 27-301** [comment]
@yellowway 
1. You can contact sales@espressif.com to get this protocol and documents;
2. Here is a reference for you: https://github.com/igrr/esptool-ck
