### ISSUE TITLE
migrate application from ESP32 to ESP8266

### ISSUE THREAD

**Issue by ammaree** [espressif/ESP8266_RTOS_SDK#198]
HI @igrr @Spritetm @projectgus , I need some help and advice.

In order to leverage the huge range of 8266 based device available in the IoT/Home automation space we have decided to try migrate our firmware from the  ESP32 to ESP8266 platform.
The current FW runs happily on 1 or 2 cores, even at 80Mhz so speed is not an issue.
The FW is ~750Kb in size and we have 3 OTA images to enable regression.

Our design goals for the 8266 FW are as follows:
1) Must fit within 1MB flash.
2) Support OTA, 2 versions of application
3) Support SSL, preferably Mbed.

The roadmap states that the next version (v3.0) of esp8266_rtos_sdk will migrate to esp_idf style. Other than the 5 actions identified in the readme, do you have any more details on:
a) The timescale for the date of first release candidate?
b) sequence/priority of components and modules to be adapted/migrated?

We have to create an ESP8266 version of our ESP32 Platform Abstraction Layer (PAL).
Since most (but not all) of the work done to create a new PAL would be come redundant once the RTOS SDK v3.0 is available, we would like to focus on the modules we require that would be lowest on your list of priorities.

All help and guidance appreciated.

Andre

**Comment by projectgus** [comment]
Hi Andre,

I think at this stage there is no ETA for this release or a detailed breakdown of a migration plan. @wujiangang may have more information. If you need any particular timeframe then writing a new platform abstraction layer for the current ESP8266 API is the most viable approach.

Angus

**Comment by donghengqaz** [comment]
Hi, main goal is gone, and some features are doing now,

1. fit within 1MB flash is doing, and this may support on v3.2
2. support OTA, 2 versions of application is down
3 support SSL, preferably Mbed is done

**Comment by ammaree** [comment]
Thanks for the feedback @donghengqaz but just to clarify.

Are you saying all 3 items listed will be part of ESP-IDF v3.2?
Is there any documentation comparing the APIs between ESP32 and ESP8266?
If not, is anything planned and for when?

Thanks

@wujiangang

**Comment by FayeY** [comment]
Hi, please have a try with the latest SDK, the 3 items above should have been supported. We are doing our best to make ESP8266 APIs be the same as the ESP32, the first draft of documents are in [ESP8266_RTOS_SDK/docs](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/docs/en). So sorry that we may need more time to finish those documentations. If you met any problem about the new SDK, please feel free to let us know. Thanks.
