### ISSUE TITLE
急～问下ESP8266 的Chipid可以修改或者定制吗？

### ISSUE THREAD

**Issue by fafactx** [espressif/ESP8266_RTOS_SDK#205]
我们需要用这个ID，但是出货时候不能保证这个ID的顺序。
我想知道这个ID能不能修改。怎么改？
还有这个ID最大支持21亿的数据。将来乐鑫流片如果大与21亿怎么办？
谢谢！！！

**Comment by CaineLew** [comment]
咦，不是42亿吗

**Comment by 27-301** [comment]
1. 你为什么要保证这个 ID 的顺序？如果你要 ID，你可以自己写到 flash 中吗？这样你自己可控。
2. 这个 ID 其实是读取的 efuse 中的 MAC，不能修改。
3. 这个 ID 当前其实不是完全准确的，采用了 mac 的低 4 字节。高 3 字节是从 WiFi 联盟买的，除非第 3 字节重复，才有可能会重复。我们已购买若干 mac 头，暂时没有出现第 3 字节重复的情况。
比如我们有 12:34:56:78:90:ab 的 mac，也有 11:22:56:78:90:ab 的 mac，这样才可能重复。

**Comment by fafactx** [comment]
谢谢回复，不是要保证顺序，只要要保证知道就行。现在我们已经和模组供应商取得了结果了。
ESP8266 他们疯的模组会给提供chipid 和MAC的编号。这个对我们已经够了。我的需求就是芯片在不告诉别人情况下，外接通过文本也知道那些id是合法的。
