### ISSUE TITLE
Build System Documentation Missing

### ISSUE THREAD

**Issue by GaryHendrick** [espressif/ESP8266_RTOS_SDK#206]
make/project.mk assets 
"# See docs/build-system.rst for more details."

There is no such document.  It is unclear how to set up a project to include "include" directories.  The project structure is under-documented.
I am a new ESP8266 user, but a long time embedded system developer with extensive experience using C.  I find the RTOS SDK project almost unapproachable difficult to get started on beyond the most trivial examples.

**Comment by 27-301** [comment]
hi, @GaryHendrick the documents are lack in this project, but since the project structure is same as [esp-idf](https://github.com/espressif/esp-idf), for documents, you can refer to esp-idf, and also https://esp-idf.readthedocs.io/en/latest/index.html. Finally, esp8266 support will be in esp-idf.

**Comment by GaryHendrick** [comment]
Thanks for the info.  That does help me personally, however perhaps the project.mk file should be updated to provide readers with an accurate reference to the documentation.

**Comment by 27-301** [comment]
Yes, will do. Thanks.
