### ISSUE TITLE
您好～有谁遇到过给指点下？esp8266 udp client and Server 用同一个IP和PORT是否可行？

### ISSUE THREAD

**Issue by fafactx** [espressif/ESP8266_RTOS_SDK#217]
```c
int on=1;
if((setsockopt(fdsocket_udp_client2,SOL_SOCKET,SO_REUSEADDR,&on,sizeof(on)))<0)
{
    os_printf("socket udp2 reuse addr error errno = %d!\n",errno);
}

if((setsockopt(fdsocket_udp_client2,SOL_SOCKET,SO_REUSEPORT,&on,sizeof(on)))<0)
{
    os_printf("socket udp2 reuse port error errno = %d!\n",errno);
}
```

我遇到会打印errno = 92 协议不存在？

**Comment by 27-301** [comment]
hi, guess you use v2.x.x version or older version. In these versions, please try this: modify lwipopt.h in SDK/include/lwip folder, find `SO_REUSE`, and define to 1. Then in third_party folder, you can rebuild lwip with `./make_lib.sh lwip`. Recompile your application again and test.

BTW, i advise you to try master branch, master branch changes a lot, and will be more easy to use, we will continue to improve it. Thanks.
