### ISSUE TITLE
串口使用低波特率bug

### ISSUE THREAD

**Issue by shinhwalin** [espressif/ESP8266_RTOS_SDK#218]
初始化低于4800波特率就会出现乱码，当设置成1200的时候打印定义好的字符串使用的是默认74880，但是打印反现串口接收的数据就是乱码。

**Comment by shinhwalin** [comment]
这个bug在NONOS_SDK不会出现，是不是RTOS_SDK在设置低波特率还需要设置其他东西？

**Comment by shinhwalin** [comment]
程序很简单，先初始化串口，波特率设置成1200，然后打印出来设置ESP工作模式是否正确这个状态，再打印一些简单信息，之后就进行串口收发，ESP将串口接收到的数据原封不动发送给发送放，也就是PC，这时候就出现，打印状态和信息，串口助手设置成74880波特率就能显示正常，但是进行串口通信的时候，任何波特率都是乱码了

**Comment by 27-301** [comment]
which branch or which commit do you use?

**Comment by shinhwalin** [comment]
SDK版本为：ESP8266_RTOS_SDK Release 2.0.0，就是最新的SDK，以前的版本也是这样。

**Comment by FayeY** [comment]
最新的 RTOS 应该已经解决了这个问题，烦请进行测试。如果问题仍未解决，请再告知。谢谢!
