### ISSUE TITLE
unknown type name 'pthread_mutex_t'

### ISSUE THREAD

**Issue by xiangjiangnan** [espressif/ESP8266_RTOS_SDK#220]
我在使用pthread.h头文件时，有如下代码
#include <pthread.h>
#define BY_mutex_t pthread_mutex_t
BY_mutex_t* BY_linux_mutex_create();
#define BY_mutex_create BY_linux_mutex_create
#define BY_mutex_lock pthread_mutex_lock
#define BY_mutex_unlock pthread_mutex_unlock

在Makefie中加入了-lpthread，但是在编译中总是出现如下错误：
../include/core/common_def.h:27:20: error: unknown type name 'pthread_mutex_t'
 #define BY_mutex_t pthread_mutex_t
如果我只定义
#define BY_mutex_lock pthread_mutex_lock
#define BY_mutex_unlock pthread_mutex_unlock
会显示错误undefined pthread_mutex_lock。
请问是什么原因以及该如何解决？
谢谢

**Comment by 27-301** [comment]
hi, @xiangjiangnan pthread is not supported now.
