### ISSUE TITLE
Difference SDK 1.5.0 and SDK 2.0.0

### ISSUE THREAD

**Issue by jdullaert** [espressif/ESP8266_RTOS_SDK#223]
I've created firmware with the SDK 1.5.0 and works for quite some time now. When changing to SDK 2.0.0 for getting more heap memory the same code crashes continuously when connecting to a STATION. No debug information is seen, when I  add multiple printf's the same code works!
This is the continous crash report:
09:13:45.278: RTOS SDK version:2.0.0(e271380)
09:13:45.281: ESP8266 chip ID:0x21ecd0
09:13:45.284: ESP8266 freq: 160
09:13:45.285: Max TCP connection:5
09:13:45.287: Heap size free : 68528
09:13:45.289: data  : 0x3ffe8000 ~ 0x3ffe8364, len: 868
09:13:45.293: rodata: 0x3ffe8370 ~ 0x3ffe8abc, len: 1868
09:13:45.297: bss   : 0x3ffe8ac0 ~ 0x3fff0330, len: 30832
09:13:45.301: heap  : 0x3fff0330 ~ 0x40000000, len: 64720
09:13:45.305: Heap size free: 59800
09:13:45.307: --- BUILD May 28 2018 13:48:48 ---
09:13:45.310: mode : sta(5c:cf:7f:21:ec:d0) + softAP(5e:cf:7f:21:ec:d0)
09:13:45.315: add if0
09:13:45.316: dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
09:13:45.322: add if1
09:13:45.322: bcn 100
09:13:45.323: [+] SPI task running (56680)
09:13:45.326: init_completed
09:13:45.327: [+] Wifi task running (56912)
09:13:45.330: [i] Wifi task init begin
09:13:45.332: SOFTAP begin
09:13:45.333: Random= 1232
09:13:45.335: UUID: 8cac99ba-98e6-1000-0000-5ecf7f21ecd0
09:13:45.338: AP SSID: ICON-21ecd0
09:13:45.340: AUTH: 0, Channel: 1, beacon: 100, max_con: 4
09:13:45.344: Hostname: ICON-21ecd0
09:13:45.346: AP no PWD needed
09:13:45.348: 0x0104A8C0
09:13:45.349: IPv6 create
09:13:45.350: 0x80FE::0x0000::0xFF7FCF5C::0xD0EC21FE
09:13:45.354: 0x0000::0x0000::0x0000::0x0000
09:13:45.356: 0x0000::0x0000::0x0000::0x0000
09:13:45.359: 0x00000000
09:13:45.360: 0x0000::0x0000::0x0000::0x0000
09:13:45.363: 0x0000::0x0000::0x0000::0x0000
09:13:45.366: 0x0000::0x0000::0x0000::0x0000
09:13:45.368: SOFTAP end
09:13:45.370: STATION begin
09:13:45.371: 10 STA SSID: Test_network
09:13:45.373: 14 PWD: xxxx-xxxx-xxxx
09:13:45.375: STATION end
09:13:45.376: IPP init
09:13:45.377: wdb info request: 0x00000019, 256, 0
09:13:45.380: HTTP socket created
09:13:45.382: [+] MDNS socket created 1
09:13:45.385: HTTP socket bind
09:13:45.386: [+] DNS socket created 2
09:13:45.388: HTTP SERVER listening max 2
09:13:45.391: IPP socket created
09:13:45.393: [+] NBNS socket created 4
09:13:45.395: IPP socket bind
09:13:45.396: IPP SERVER listening max 2
09:13:45.399: PDL socket created
09:13:45.401: PDL socket bind
09:13:45.402: PDL SERVER listening max 2
09:13:45.756: add 1
09:13:45.756: aid 1
09:13:45.757: station: 18:5e:0f:59:51:41 join, AID = 1
09:13:45.760: [+] SA client connect
09:13:48.160: scandone
09:13:48.460: switch to channel 11
09:13:52.404: ShowCritical:0
09:13:52.405: HdlMacSig:0
09:13:52.407: SWReq:0
09:13:52.454: 
09:13:52.455:  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
09:13:52.459: 
09:13:52.462: load 0x40100000, len 29832, room 16 
09:13:52.479: tail 8
09:13:52.480: chksum 0x69
09:13:52.481: load 0x3ffe8000, len 868, room 0 
09:13:52.484: tail 4
09:13:52.485: chksum 0x69
09:13:52.486: load 0x3ffe8370, len 1868, room 4 
09:13:52.490: tail 8
09:13:52.490: chksum 0xfd
09:13:52.492: csum 0xfd

**Comment by 27-301** [comment]
@jdullaert Can you share the code to reproduce this issue? Thanks
