### ISSUE TITLE
Missing gpio_config from gpio.h?

### ISSUE THREAD

**Issue by cranphin** [espressif/ESP8266_RTOS_SDK#226]
I would expect the gpio_config method from here:
https://github.com/espressif/ESP8266_RTOS_SDK/blob/108a59ff8d73b39e577aecffff9bc2e24a08ea1d/components/esp8266/driver/gpio.c#L26
to also be in gpio.h, but it is not?

I get the feeling RTOS is still underused by people? Shame, ESP32 rtos addicted me to FreeRTOS :)

**Comment by 27-301** [comment]
@cranphin RTOS SDK is still under refactoring, it will be finally compatible to IDF. Thanks
