### ISSUE TITLE
[SDK8266-73] Lost NetworkDisconnect() function in MQTT?

### ISSUE THREAD

**Issue by DongBH** [espressif/ESP8266_RTOS_SDK#229]
There is NetworkConnect()  function in MQTT, but Cannot find NetworkDiscconect(). btw, There should be a return value for MQTTYield for network disconnected.

**Comment by 27-301** [comment]
In current paho mqtt, there are no such NetworkDisconnect, or NetworkDeInit pattern, so we don't implement these. Need to consider about these.

For MQTTYield, what do you mean? In current master branch, it has return value.
https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/mqtt/paho/MQTTClient-C/src/MQTTClient.c#L341-L359

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue. Thanks.
