### ISSUE TITLE
SDK 2.0 SPI Master issue

### ISSUE THREAD

**Issue by berkutta** [espressif/ESP8266_RTOS_SDK#231]
I'm using the newest 2.0 SDK and facing issues with the SPI Master example from https://github.com/espressif/esp8266-rtos-sample-code/blob/master/02Peripheral/HSPI_Master/user/user_main.c

Cyan/Blue is the CLK Line (GPIO14). The signal is very unstable and noisy. My Slave SPI Device (SSD1331 Display) can't handle a such noisy clock signal. Is there a solution for that?

(FYI: I don't face any of those issues with the ESP32)

![ds1z_quickprint3](https://user-images.githubusercontent.com/11159719/51278372-b6167200-19da-11e9-8b8f-df2899b01c52.png)

**Comment by xiongyumail** [comment]
Hi @berkutta 
Maybe you need an external pull-up resistor?

**Comment by berkutta** [comment]
I have now tried with a 10k Pullup Resistor on HSPI CLK but it's still nearly unusuable.

**Comment by berkutta** [comment]
Looks like it got fixed with the new SPI driver. Thank you Espressif!

![ds1z_quickprint1](https://user-images.githubusercontent.com/11159719/51278399-c6c6e800-19da-11e9-8b57-57a46fceec6a.png)

**Comment by xiongyumail** [comment]
Thank you!
I think it might be related to this option.
`CLEAR_PERI_REG_MASK(PERIPHS_IO_MUX_CONF_U, SPI1_CLK_EQU_SYS_CLK);`
