### ISSUE TITLE
[TW#24152] HSPI 求使用历程，一配置就不断中断死机

### ISSUE THREAD

**Issue by Yvan623048750** [espressif/ESP8266_RTOS_SDK#239]
SpiAttr hspi;
			
	hspi.mode		= SpiMode_Slave;
	hspi.speed		= SpiSpeed_10MHz;
	hspi.subMode	= SpiSubMode_1;
	hspi.bitOrder	= SpiBitOrder_LSBFirst;
	
	
	SPIInit(SpiNum_HSPI,&hspi);
	SPISlaveRecvData(SpiNum_HSPI,hspi_rece_callback);

**Comment by xiongyumail** [comment]
@Yvan623048750 
您可以参考一下[NONOS的SPI例程](https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/examples/peripheral_test/user/spi_test.c)
