### ISSUE TITLE
Non OTA vesion works But OTA version crash or reboot again and agin

### ISSUE THREAD

**Issue by aeris-ming** [espressif/ESP8266_RTOS_SDK#247]
Please read issue 246
https://github.com/espressif/ESP8266_RTOS_SDK/issues/246

I closed it unexpected.

**Comment by aeris-ming** [comment]
https://github.com/espressif/ESP8266_RTOS_SDK/blob/v2.0.0/ld/eagle.app.v6.ld
I think the parameter address is wrong.Please check it.

**Comment by aeris-ming** [comment]
Very interesting,I think this device it 512KByte or Parameter address is wrong.
It works when flash system parameter to 0x7C000.
I think an ESP8266 with 512KB do not have enough room for OTA.
![39035085-af1b3124-4470-11e8-93f3-2fb36a30333d](https://user-images.githubusercontent.com/28724248/42135989-2d02dba2-7d86-11e8-9ac4-b771a0368284.jpg)
![c](https://user-images.githubusercontent.com/28724248/42135991-391dc8fc-7d86-11e8-9107-2727b5ceb9d8.png)
![d](https://user-images.githubusercontent.com/28724248/42136000-54c2003c-7d86-11e8-9641-792b0866d6bf.png)

**Comment by 27-301** [comment]
hi, for 512KB flash, if the binary(user.bin) is larger than 256KB-4KB*6, it can not support OTA. The 6 sectors reversed as 3 system parameter sectors, 1 bootloader, 1 init data bin sector, 1 cal data sector. For eagle.app.v6.ld, it's only used for non OTA mode.

**Comment by aeris-ming** [comment]
Change spi flash configure to DIO fix this issue
