### ISSUE TITLE
请问mbedtls支持ec算法吗

### ISSUE THREAD

**Issue by donny681** [espressif/ESP8266_RTOS_SDK#250]
我发现sdk提供mbedtls静态库只支持rsa算法，不支持ec算法,我上网搜了相关资料，都是说没有把ec算法加到mbedtls库。你们有计划解决这个问题吗？

**Comment by donny681** [comment]
好的，我稍后联系贵司David，我们之后私聊

**Comment by donny681** [comment]
您好，我联系贵司FAE David,他无法确认您的身份，你能发一封邮件给我sky@aithinker.com,按照我的需求提供libwolfssl.a 库

**Comment by 27-301** [comment]
稍候联系你，今天机房调整，邮箱系统还没恢复。

**Comment by donny681** [comment]
您好，我看到你们有一个项目esp8266-wolfssl（https://github.com/espressif/esp8266-wolfssl/tree/master/wolfssl ）把源码开源，2.xx wolfssl是基于3.15.3开发吗,还是基于3.12.2？

**Comment by 27-301** [comment]
release/v2.x.x 上的是 3.14.0 的。你可以在 esp8266-wolfssl 上自己更新到 3.15.3。如果有问题，我再安排更新 esp8266-wolfssl。
