### ISSUE TITLE
xTaskNotify in Version 2.0.0

### ISSUE THREAD

**Issue by wakille** [espressif/ESP8266_RTOS_SDK#256]
Is there any possibility to use xTaskNotify in Version 2.0.0? The FreeRTOS Kernel Version ist still 7.5.2 and xTaskNotfy is not included. Or is there a plan, at which version it will be included ? Would be quite useful, to use all of the freeRTOS functions.

**Comment by 27-301** [comment]
hi, it's a new feature of FreeRTOS, currently we don't have plan to update FreeRTOS in v2.x.x, if you need this, please use master branch. In master branch, FreeRTOS is update to v10. But, master branch has done a lot of refactor, it's very different to v2.0.0. You can refer to some examples to port your old application to the new SDK.
