### ISSUE TITLE
[TW#24228] fatal error: esp_sta.h: No such file or directory

### ISSUE THREAD

**Issue by qrsrjm** [espressif/ESP8266_RTOS_SDK#257]
ESP8266_RTOS_SDK/examples/wifi/wps/main/user_main.c:14:21: fatal error: esp_sta.h: No such file or directory
 #include "esp_sta.h"
                     ^
compilation terminated.

**Comment by 27-301** [comment]
This examples need to be fixed, thanks to point out. Please try the examples in protocols firstly.

**Comment by Junhao-Espressif** [comment]
Hi @qrsrjm 

We reconstructed the WiFi interface on the new version. 

WPS is not supported now.
