### ISSUE TITLE
esp8266 pbuf_alloc函数申请内存出错

### ISSUE THREAD

**Issue by BalrogMithrandir** [espressif/ESP8266_RTOS_SDK#258]
使用最新官网的2.0RTOPS版本sdk，进行tcp发送时，send函数一直阻塞，查看源码后，发现调用关系：lwip_send->netconn_write_partly->TCPIP_APIMSG->tcpip_apimsg ->lwip_netconn_do_writemore->tcp_write->tcp_pbuf_prealloc->pbuf_alloc.

在pbuf_alloc函数中，传入的入参layer=PBUF_TRANSPORT， length=1300， type= PBUF_RAM。函数pbuf_alloc运行到case PBUF_RAM后，调用mem_malloc申请了内存并且成功，但是申请的内存地址大于0x40000000，在函数结尾处判断申请的内存地址是否大于0x40000000时被释放了。
这个时候我调用system_get_free_heap_size函数看，heap还有十多k的空间，请问这个是什么原因？

**Comment by 27-301** [comment]
1. 用的是 2.0.0 release 版本，非 master 版本？
2. 因为 2.0.0 做了内存优化，将 iram (0x40000000) 后的部分空间做了 heap 区，但是该区域的数据不允许作为 WiFi 的 Tx buffer，所以在 pbuf_alloc 的时候判断该地址大于 0x40000000 会释放；
3. heap 还有 10KB+，但有可能都是在 iram 中了；
4. 可以看下系统的内存分配情况，作分析：
在 user_main.c 里加入：
```c
#include "esp_libc.h"

bool ICACHE_FLASH_ATTR check_memleak_debug_enable(void)
{
    return MEMLEAK_DEBUG_ENABLE;
}
```
然后在 pbuf_alloc 中判断分配地址大于 0x40000000 的地方加入 system_show_malloc();
4. 能否将 *.dump 文件中的 Sections 段信息提供上来，可以看下你是否将字符串默认置于 flash 中；

**Comment by BalrogMithrandir** [comment]
还有，应用程序三个任务用了2048的栈空间

**Comment by 27-301** [comment]
@BalrogMithrandir 你看下 https://blog.csdn.net/espressif/article/details/78563826 这个文档。你可以把你应用里的所有字符串放在 flash 中。当前你 .rodata 段占用了太多 dram 空间，这当中可以有很大一部分放到 flash 中。我不知道你项目的具体结构，你需要修改 ld 文件，参考一下这个文档，相信你可以搞定。修改后，你应该可以多出 24KB 的内存。

**Comment by BalrogMithrandir** [comment]
好的，谢谢您！按照您发的帖子，问题已经解决，谢谢了！
