### ISSUE TITLE
关于在分支3.0上使用 CJSON报错的问题！

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_RTOS_SDK#260]
- 在微信公众号看到分支3.0的内存节省了30KB，于是乎我就打算用这个分支的SDK，但是添加 cjson库之后，报错如下~

`/cygdrive/E/Espressif/Esp8266/Study/ESP8266_RTOS_SDK_release_v2//lib/libjson.a(cJSON.o):(.text.parse_value+0x18): undefined reference to `pow'
/cygdrive/E/Espressif/Esp8266/Study/ESP8266_RTOS_SDK_release_v2//lib/libjson.a(cJSON.o):(.text.parse_value+0x274): undefined reference to `pow'`

**Comment by 27-301** [comment]
@xuhongv 看上去你这是 2.0，如果需要用 pow，需要在 Makefile 中增加 -lm。强烈建议你直接用 master 分支。

**Comment by xuhongv** [comment]
贵方的3.0分支不是节省了 30k内存么？主分支节省了么

**Comment by 27-301** [comment]
现在主要有两个分支，release/v2.x.x 分支是基于老的 SDK 架构，有内存优化。master 分支是新的 SDK 架构，也有内存优化，但由于架构调整，总体内存当前比 release/v2.x.x 上的少约 5KB。
