### ISSUE TITLE
[TW#24604] idf_size.py is missing

### ISSUE THREAD

**Issue by garthk** [espressif/ESP8266_RTOS_SDK#261]
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 765754f 
- Development Env:      other
- Operating System:     macOS
- Power Supply:        USB

## Problem Description

`make size` requires `idf_size.py`, which is not present.

### Expected Behavior

```
$ make help
Welcome to Espressif IDF build system. Some useful make targets:
…
make size - Display the static memory footprint of the app
make size-components, size-files - Finer-grained memory footprints
make size-symbols - Per symbol memory footprint. Requires COMPONENT=<component>

$ make size
… some useful output…
```

### Actual Behavior

```
$ make help
Welcome to Espressif IDF build system. Some useful make targets:
…
make size - Display the static memory footprint of the app
make size-components, size-files - Finer-grained memory footprints
make size-symbols - Per symbol memory footprint. Requires COMPONENT=<component>

$ make size
/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/garth/src/ESP8266/ESP8266_RTOS_SDK/tools/idf_size.py': [Errno 2] No such file or directory
make: *** [size] Error 2
```

### Steps to ~~repropduce~~ reproduce

`make size`

**Comment by FayeY** [comment]
Hi, so sorry that we may not add this feature now, but we may think about it in future. Sorry for the inconvenience.
