### ISSUE TITLE
使用MQTT的demo，发现payload较大的时候,，数据发不出去了！bug？？

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_RTOS_SDK#263]
- 您好！我发现使用这个```rtos```的MQTT，发现```payload ```较大的时候，会出现发送数据不成功的！这是为啥？下面是我的代码。。```payload ```的字符串字节是76。返回的永远是 -1 。如果我把。```payload ```的内容为```hello world```，就可以成功发送了，这个是什么问题呢？

```
char payload[2048] ={"{\"mode\":0,\"time\":0,\"rgb\":{\"red\":1,\"green\":1,\"blue\":0,\"cwhite\":0,\"wwhite\":0}}"};

			
	MQTTMessage message;
	message.qos = QOS2;
	message.retained = 0;
	message.payload = payload;
	message.payloadlen = strlen(payload);

	printf("client.isconnected is %d\n", client.isconnected);
	printf("payload is %s\n", payload);
	printf("strlen(payload)  is %d\n", strlen(payload) );


	if (strlen(payload) != 0)
	    if ((rc = MQTTPublish(&client, pubTopic, &message)) != 0) {
		    printf("Return code from MQTT publish is %d\n", rc);
		} else {
			printf("MQTT publish topic %s, message: %s\n", pubTopic,
			 message.payload);
		}

	if (rc != 0) {
		break;
	}
```
- 下面是串口打印的截图：

![hg3d kmlu ert fu qktcwi](https://user-images.githubusercontent.com/25237870/43070499-9011a458-8ea2-11e8-8ecb-d228f55dd305.png)

**Comment by xuhongv** [comment]
- 几经翻读源码发现，这个 ```payload``` 的大小是在初始化的时候规定的，也就是```MQTTClientInit()```方法里面，修改为如下 1024 即可就可以了：

```
        Network network;
	unsigned char sendbuf[1024], readbuf[1024] = { 0 }; // this can be 1024 or more or less
	int rc = 0, count = 0;
	MQTTPacket_connectData connectData = MQTTPacket_connectData_initializer;
	pvParameters = 0;
	NetworkInit(&network);

      MQTTClientInit(&client, &network, 30000, sendbuf, sizeof(sendbuf), readbuf,
			sizeof(readbuf));
```

**Comment by Clairehou111** [comment]
@xuhongv  把buffersize增大之后，可以发送当发送大小到128的还可以，但140+的时候也会显示发送成功，但是会导致MQTTClient的isconnected    @@@变为0，进而掉线。看了下你发送的数据是96byte，再加上协议的格式，也就105以内。能不能试下payload超过140的情况呢，看是不是也有问题，谢谢。
  esp_write, len=117, sentLen=117; 
  esp_write, len=128, sentLen=128;
 esp_write, len=140, sentLen=140; //cause isconnected = 0

**Comment by xuhongv** [comment]
@Clairehou111 你翻读下源码？

**Comment by Clairehou111** [comment]
@xuhongv 跟MQTT有关的逻辑，我读了很多遍，想找出是不是哪儿有大小限制，始终没找到。你能不能测下发送比较大140+的有没有问题，如果你的没有，我再换其它思路。谢谢。
