### ISSUE TITLE
When will the esp-idf style esp8266 RTOS SDK release ?

### ISSUE THREAD

**Issue by kmalloc8** [espressif/ESP8266_RTOS_SDK#264]
When will the esp-idf style esp8266 RTOS SDK release ?

**Comment by 27-301** [comment]
It's under test now, will release ASAP.

**Comment by luvocean1** [comment]
Cant wait for this release...I am trying to compile exmaple wifi project with 2.0 RTOS_SDK and latest toolchain: xtensa-lx106-elf-win32-1.22.0-88-gde0bdc1-4.8.5.tar and it will not compile on eclipse....lots of errors. I think the toolchain is broken.

**Comment by kmalloc8** [comment]
@luvocean1 ,it seems the toolchain is for SDK 3.0
