### ISSUE TITLE
where can i find gen_misc.h?

### ISSUE THREAD

**Issue by xyG67** [espressif/ESP8266_RTOS_SDK#265]
Does anyone know how to compile the latest version?(the RTOS_SDK from master branch) I got an error when using command "make menuconfig"

Error message: "No rule to make target `menuconfig'.  Stop."

Any advise will be appreciated. Thank you so much!

**Comment by kmalloc8** [comment]
@xyG67 , Have you done this?
`export IDF_PATH=~/esp/ESP8266_RTOS_SDK`
