### ISSUE TITLE
PWM导致软件看门口触发

### ISSUE THREAD

**Issue by CaineLew** [espressif/ESP8266_RTOS_SDK#270]
## Environment

- Development Kit: RTOS
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    ea34c2a
- Development Env:      Make
- Operating System:     MacOS
- Power Supply:         USB

## Problem Description
使用PWM功能，导致软件看门狗触发。

pwm version:1.0.2

Soft watch dog triggle:

ShowCritical:0
HdlMacSig:0
SWReq:0

### Steps to repropduce

1. step1
2. ...

// It helps if you attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"
#include <driver/gpio.h>
#include <pwm.h>

void app_main()
{
    uint32_t io_info[2][3]={
        {GPIO_PIN_REG_12, FUNC_GPIO12,12}, 
        {GPIO_PIN_REG_14, FUNC_GPIO14,14} 
        };
    uint32_t duty[2]={0, 0};

    pwm_init(1000, duty, 2, io_info); // 1khz
    pwm_start();
}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

I (22) boot: ESP-IDF v2.0.0-699-gea34c2a 2nd stage bootloader
I (23) boot: compile time 18:45:18
I (23) boot: SPI Speed      : 40MHz
I (27) boot: SPI Mode       : QIO
I (31) boot: SPI Flash Size : 2MB
I (34) boot: Partition Table:
I (38) boot: ## Label            Usage          Type ST Offset   Length
I (45) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (53) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (60) boot:  2 factory          factory app      00 00 00010000 00100000
I (67) boot: End of partition table
I (71) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x38460 (230496) map
I (126) esp_image: segment 1: paddr=0x00048478 vaddr=0x3ffe8000 size=0x00ea8 (  3752) load
I (127) esp_image: segment 2: paddr=0x00049328 vaddr=0x3ffe8ea8 size=0x00110 (   272) load
I (133) esp_image: segment 3: paddr=0x00049440 vaddr=0x40100000 size=0x07558 ( 30040) load
0x40100000: _stext at ??:?

I (147) boot: Loaded app from partition at offset 0x10000
E (154) chip_boot: SPI flash read result 65553

ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x40100000, len 4324, room 16
0x40100000: _stext at ??:?

tail 4
chksum 0xc4
load 0x3ffe8008, len 3420, room 4
tail 8
chksum 0x07
csum 0x07

**Comment by 27-301** [comment]
@CaineLew We will follow up #287, close this issue.
