### ISSUE TITLE
[TW#25132] smartconfig crash,v2.0

### ISSUE THREAD

**Issue by aeris-ming** [espressif/ESP8266_RTOS_SDK#271]
1.esp8266 is successfully connected to router
2.call wifi disconnect api and disable reconnect
3.start smartconfig task
4.serial port output "sandone sane error state-->1 sane error state-->4..."
5.then reboot

**Comment by xuhongv** [comment]
this is a problem ,  when the Esp8266 is successfully connected to router , then I start smartconfig task again. But is not successfully . 

Now I creat new way to solve the problem , restart the system to into smartconfig task .

Hope the can help you.

**Comment by aeris-ming** [comment]
@xuhongv How to fingure out if smartconfig should be start after reset?

**Comment by xuhongv** [comment]
when you into smartconfig , set flag number and save on flash . then restart system and read the flag ,if is the smartconfig  flag , we current into smartconfig  mode ,how?

**Comment by Junhao-Espressif** [comment]
Hi @aeris-ming 

Could you give me your example?

Thanks!

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details. Thanks.
