### ISSUE TITLE
自搭mosquitto带ssl的服务器可以连上，但亚马逊aws iot平台无法连上。可能是什么问题？

### ISSUE THREAD

**Issue by 9crk** [espressif/ESP8266_RTOS_SDK#273]
自搭mosquitto带ssl的服务器可以连上，但亚马逊aws iot平台无法连上。可能是什么问题？
两个都用MQTT.fx 软件可以连上。

**Comment by 9crk** [comment]
代码一丝没改，就改了服务器地址和ca cert key三个头文件。

**Comment by 9crk** [comment]
亚马逊的堵在SSL_Connect函数，返回0

**Comment by 9crk** [comment]
@27-301  2.0.0 Release

**Comment by 9crk** [comment]
@xcguang  
NetworkConnectSSL(&network, address, MQTT_PORT, &ssl_cck, SSLv23_client_method(), SSL_VERIFY_PEER, 8192);

这个8192应该就是你说的buffer吧？

另外，SSLv23_client_method()这个换过了多个，也不行。

**Comment by xcguang** [comment]
如果有条件的话，建议使用无线抓包网卡抓取一下，如果是 ssl 层的错误，应该能看出来点什么的

**Comment by kmalloc8** [comment]
mark, I want the answer too.

**Comment by kmalloc8** [comment]
@9crk ,可以连上了吗？

**Comment by 27-301** [comment]
建议用 3.0，直接拉 master，有如下例子：examples/protocol/aws_iot。

**Comment by kmalloc8** [comment]
@27-301 ，前些天用3.0才写的一些外设驱动，比如Key，今天就更新gpio了，以前的接口也没有了，后面会不会哪天又大改一次?

**Comment by xiongyumail** [comment]
@kmalloc8 
3.0版本外设驱动大部分兼容 ESP32 外设驱动，而且接口简单了很多．可以尝试一下example中的例程．

**Comment by kmalloc8** [comment]
@xiongyumail ，OK，我研究一下，thx.

**Comment by kmalloc8** [comment]
@9crk ,呵，因为一定要搞aws，感觉3.0移植了官方aws-sdk，应该靠谱些吧，不管那么多了，现在开始折腾3.0，，，
