### ISSUE TITLE
Modifying Baseband Processing, Radio Blocks, and MAC Blocks in ESP8266EX

### ISSUE THREAD

**Issue by hirzallah** [espressif/ESP8266_RTOS_SDK#274]
I have a general question about the possibility to modify the software for Wi-Fi blocks, especially for the baseband signal processing and MAC blocks (lower MAC). The main purpose of these modifications is for an academic research. I appreciate your response! Thank you!

**Comment by 27-301** [comment]
It's not in our plan now, thanks for your understanding.
