### ISSUE TITLE
[TW#25133] smartconfig demo 不能配网成功

### ISSUE THREAD

**Issue by zhouwei890610** [espressif/ESP8266_RTOS_SDK#276]
![image](https://user-images.githubusercontent.com/8242047/43628921-34fa28f8-972e-11e8-801a-c93d68a44c09.png)

**Comment by zhouwei890610** [comment]
APP 是ISO 版本Esptouch

**Comment by zhouwei890610** [comment]
![image](https://user-images.githubusercontent.com/8242047/43629425-cc0e0c36-972f-11e8-93fb-e4f32f58a94d.png)

**Comment by xuhongv** [comment]
您可以尝试下 android端的。或者保证您的 ios 包是最新的版本。

**Comment by jerrywoodz** [comment]
Android Esptool v0.3.6.2是最新板？，smartconfig也配網不成功。

**Comment by 27-301** [comment]
Is this dual band router?

**Comment by qianxilin** [comment]
我也尝试了3.0的SDK。smartconfig无法配网成功。。同样的环境2.0的SDK是正常的。。有谁使用3.0的SDK配网成功过？

**Comment by Junhao-Espressif** [comment]
Hi @qianxilin,

Please use the new apk here: https://github.com/EspressifApp/EsptouchForAndroid/tree/master/releases/apk .


And select Broadcast in EspTouch app.

**Comment by zhanghuichina** [comment]
有些路由器可以，有些很难成功，都没有5g的路由器

**Comment by IanXxu** [comment]
用EspTouch app，smartconfig偶尔会成功，成功率很低啊。airkiss也是偶尔成功

**Comment by zhanghuichina** [comment]
同样的网络环境 使用esp32时esptouch和airkiss都能成功,而且速度很快, 应该是libsmartconfig.a的问题, 有没有其他版本可以提供v3.0测试的?

**Comment by yefunbox** [comment]
v3.0确实用不了，很奇怪

**Comment by qianxilin** [comment]
重新用Ubuntu把环境搭建了下。EspTouch ap可以连接成功了。。把linux的SDK重新拷贝到windows下，再编译，也可以连接了。-_-||

**Comment by 1XiaSheng** [comment]
我在安卓端也碰到了配置不成功.
I have the same err in esptouch on android

**Comment by FayeY** [comment]
使用的是最新的安卓 apk 和固件吗？可以参考上面的帖子更新。
