### ISSUE TITLE
lost time functions in time.h, which lib should be included?

### ISSUE THREAD

**Issue by iamzgr** [espressif/ESP8266_RTOS_SDK#279]
I'm writing an alarm program with esp8266_rtos_sdk v2.0.0 ,
include "time.h" and use some functions.  I get these after building failed:
undefined reference to `time' ;        
undefined reference to `localtime_r' ;            
undefined reference to `mktime'        

Dose these functions be implemented in v2.0.0 ? Or some libs should be add to the LINKFLAGS in Makefile ?

**Comment by 27-301** [comment]
the time functions are not supported in 2.0.0. please try the latest master branch.
