### ISSUE TITLE
printf sprintf snprintf都不支持float

### ISSUE THREAD

**Issue by puppies** [espressif/ESP8266_RTOS_SDK#281]
最近调试AWS IOT发现里面的snprintf对float变量的支持有问题，后面就试了printf和sprintf都是这样。

%f最终出来都是空的。

用的是Linux(64)的toolchain，这应该是toolchain有问题吧？

**Comment by ustccw** [comment]
@puppies please try to configurate your `newlib` to normal mode. 

`make menuconfig` -> `Component config` -> `Newlib` -> `newlib level` , and try the normal item.

**Comment by puppies** [comment]
@ustccw Thx. It works!
