### ISSUE TITLE
[TW#25137] Unable to install custom GPIO ISR service

### ISSUE THREAD

**Issue by THKDev** [espressif/ESP8266_RTOS_SDK#282]
Method `gpio_isr_register` has hard coded to register `gpio_intr_service` only.

https://github.com/espressif/ESP8266_RTOS_SDK/blob/fd63b5e561d76415d70fd9d1dea0a744e86ea66a/components/esp8266/driver/gpio.c#L421-L427

**Comment by xiongyumail** [comment]
HI ,
Thank you very much for discovering this problem.
This interface should not be open, and the parameters seem useless. (in order to be compatible with ESP32)
You can add user interrupt handlers using the 'gpio_isr_handler_add' function.
