### ISSUE TITLE
light sleep : how to get it?

### ISSUE THREAD

**Issue by shw19791031** [espressif/ESP8266_RTOS_SDK#290]
## Environment

esp8266ex (ESP-12S)

## Application

- Waiting for incoming MQTT packet to boot the master device, use battery.
- So deep-sleep is useless, I have to use light-sleep keeping MQTT connection.

## Problem Description
- forced light sleep: ok!, 0.7~0.8mA current, but WIFI have to be disconnected. It is worse than deep-sleep.
- automatic light sleep: never success!, because I cannot manually halt (control) the CPU while DTIM period.

### Dear Espressif!

Please help me!

**Comment by THKDev** [comment]
If your really want to run at low power consumption you may have a look at this [Aggressively Low Power with the ESP8266](https://www.youtube.com/watch?v=I3lJWcRSlUA)

**Comment by donghengqaz** [comment]
You should do following stops:
1. include "esp_wifi.h"
2. call `esp_wifi_set_ps(WIFI_PS_MAX_MODEM)` and system will enter light sleep mode automatically

**Comment by shw19791031** [comment]
Hi, @donghengqaz , @ustccw 

I have tested` esp_wifi_set_ps(WIFI_PS_MAX_MODEM)`, it seems final solution currently.

The result:
- The device(ESP8266EX, ESP-12S) is constantly waiting for MQTT incoming packet.
- Measured current : 18.25mA(65% of working time), 0.76mA(30% of working time), 30mA(5% of working time)  Please see https://pan.baidu.com/s/1MXsRT91ZtZ2MYuYMXHV-Bw

My router's DTIM is 10, 
My MQTT loop has 2000ms delay like this:
`   while (1)   {	vTaskDelay(2000 / portTICK_RATE_MS);
TimerCountdownMS(&timer, 2000);
cycle(c, &timer);   }`
This is my device (= bare ESP-12S) : https://pan.baidu.com/s/1E994sg_Bz9A7fXWLAuLmTQ

My question:
- Is this final solution, really?

Thanks!

**Comment by Junhao-Espressif** [comment]
Hi @shw19791031 

It is the final solution for now. 

We will optimize the power consumption in the future and add API to print the percentage of sleep status.

“Measured current : 18.25mA(65% of working time), 0.76mA(30% of working time), 30mA(5% of working time)” 

How did you get the percentage data? Could you measure it with other instruments?

This is a current waveforms that we have tested before:
![image](https://user-images.githubusercontent.com/33280035/44720735-4ae70480-aafa-11e8-94ce-b05ec6c57417.png)

**Comment by shw19791031** [comment]
OK, I'm looking forward to future improvement, thank you.
