### ISSUE TITLE
[TW#25862] softAP模式下，持续发送udp，过一段时间（不到两个小时），wifi就连接不上

### ISSUE THREAD

**Issue by tianhuanz** [espressif/ESP8266_RTOS_SDK#291]
处于这种状态下，看门狗也不会自己复位，udp也不能继续发送，wifi连接列表可以看到接入点名称，但是连接不上。

**Comment by 27-301** [comment]
which commit do you use? can you share the sample code and test flow?

**Comment by tianhuanz** [comment]
i have try the lastest commit.

**Comment by tianhuanz** [comment]
i just redirect ESP_LOG to a UDP port. so i can use the uart0.

**Comment by xiongyumail** [comment]
建议周期打印当前heap大小，观察heap的变化．可能内存空间没有释放．

**Comment by tianhuanz** [comment]
应用代码并没有使用malloc，如果不使用UDP，能够正常运行。

**Comment by donghengqaz** [comment]
你把你的工程发给我门看看，不方便发源码，发个lib也可以。

**Comment by xuhongv** [comment]
估计内存出问题吧？ 频繁调用```system_get_free_heap_size()```看看吧？

**Comment by tianhuanz** [comment]
[simple_wifi.zip](https://github.com/espressif/ESP8266_RTOS_SDK/files/2327875/simple_wifi.zip)

我写了个测试代码。
[udplogger.zip](https://github.com/espressif/ESP8266_RTOS_SDK/files/2327885/udplogger.zip)

**Comment by tianhuanz** [comment]
[simple_wifi.zip](https://github.com/espressif/ESP8266_RTOS_SDK/files/2330283/simple_wifi.zip)
更新一下测试代码，前面那个版本被文档管理系统加密了。

**Comment by Junhao-Espressif** [comment]
Hi @tianhuanz 

Sorry to tell you that I can not download your code.
```
This site can’t be reached
github-production-repository-file-5c1aeb.s3.amazonaws.com refused to connect.
```
Please send your code to my email:  zhangjunhao@espressif.com

Could you change ```#define DHCPS_LEASE_TIME_DEF (120)``` to ```#define DHCPS_LEASE_TIME_DEF (360)``` and test again?

Please give us the error log.

**Comment by tianhuanz** [comment]
DHCPS_LEASE_TIME_DEF (360) 问题依然存在

**Comment by tianhuanz** [comment]
@Junhao-Espressif 已经给你们发了测试代码，请问有什么进展？

**Comment by Junhao-Espressif** [comment]
Hi @tianhuanz 

Please do not call sendto in udp sentto callback function.

It does not take two hours. Just use another station connect to softap, and disconnect with softap. The softap will hang.

You should refactor udpLoggerPutc function. Write data to a send buffer and send it in another task.

**Comment by FayeY** [comment]
Is there any update?
