### ISSUE TITLE
[TW#25863] bug in driver_lib/include/spi_interface.h

### ISSUE THREAD

**Issue by philar** [espressif/ESP8266_RTOS_SDK#293]
in the file" driver_lib/include/spi_interface.h" ,there use "#pragma pack (1)" to make  structure SpiAttr and SpiData  align by one byte, and "#pragma upack (1)" to cancel the alignment ,but it can not work . As we know ,"#pragma pack()" can cancel the alignment.

**Comment by xiongyumail** [comment]
Hi @philar 
Which branch version do you use?Whether it can provide more information.

**Comment by philar** [comment]
branch release-v2.x.x，the link as follows 
https://github.com/espressif/ESP8266_RTOS_SDK/blob/release/v2.x.x/driver_lib/include/spi_interface.h

**Comment by xiongyumail** [comment]
Hi @philar 
Thank you for your work. How did you find out that it was not aligned?
