### ISSUE TITLE
[SDK8266-68] Write flash stuck and content not match

### ISSUE THREAD

**Issue by hainguyen8y** [espressif/ESP8266_RTOS_SDK#294]
## Environment

- Development Kit: Sonoff 4CH (ESP8285)
- IDF version: 2c72ce9
- Development Env:     Make
- Operating System:    Ubuntu
- Power Supply:         external 3.3V

## Problem Description
Sometimes esp_partitions_write() blocking and stuck then system reset due to the watchdog
The flash address to write is above 0x080000.
And some write and read back not match

### Expected Behavior
No reset and stuck
### Actual Behavior
Sometimes stuck then reset
### Steps to repropduce

1. Connect the wifi rouer
2. Firmware download the firmware and burn to the OTA_1 partition 

### Code to reproduce this issue
Use the the upgrade example in SDK
## Other items if possible
It seems to conflict between WiFi and SPI flash, Caching. I think it maybe FlashIsOnGoing not protect

**Comment by 27-301** [comment]
@hainguyen8y current SDK only supports 2MB Flash, 1MB + 1MB flash map. ESP8285 only has 1MB, and it will be supported later. Please try some other module with 2MB Flash.

**Comment by hainguyen8y** [comment]
Can you tell me when it's supported? I have a project using the ESP8285

**Comment by 27-301** [comment]
Sorry, it's not in the plan of v3.1 which we want to release by the end of Oct. We will add it into the plan for v3.2.

**Comment by hainguyen8y** [comment]
Thanks

**Comment by FayeY** [comment]
This issue should have been solved with the latest master, please have a try. Thanks.
