### ISSUE TITLE
esp8266 RTOS_SDK2.0.0链接的问题

### ISSUE THREAD

**Issue by xiebadegg** [espressif/ESP8266_RTOS_SDK#302]
## 问题描述
- 我想要在我的程序中使用cJSON.c,但是在编译的时候，会提示找不到'pow'，于是我发现cJSON.c中定义了头文件：
```
#incude <math.h>
```
- 根据我查到的资料，我需要在链接的时候加上‘-m’的选项，我应该在哪里添加这个链接选项呢？

**Comment by ichenxing** [comment]
在makefile文件中添加-ljson的链接就行，不知道能不能给你帮助

**Comment by xiebadegg** [comment]
不行，我之前在Makefile里添加过这个静态库，然后引用了头文件cJSON.h,但是编译报错，提示找不到函数的实现

**Comment by ichenxing** [comment]
你要把错误贴出来，会不会是SDK的路径不对？

**Comment by ichenxing** [comment]
会不会和你的编译工具有关？

**Comment by 27-301** [comment]
hi，如果使用 2.x 版本的 SDK。pow 在 newlib 的 math 库里，你需要在 Makefile 里加上 -lmirom。

另外，建议你切到 3.0 的 SDK，就不会有这些问题。

**Comment by xiebadegg** [comment]
hi,多谢你
