### ISSUE TITLE
SDK v3.0-rc1 float doesnt work in printf/sprintf

### ISSUE THREAD

**Issue by temmka** [espressif/ESP8266_RTOS_SDK#304]
In SDK v3.0-rc1 can't handle any of float values with printf/sprintf methods.
It worked in SDK v2.0

**Comment by 27-301** [comment]
hi, in 3.0 SDK, newlib is in nano mode by default, if you want to have full feature of newlib, you can try normal mode. configure in menuconfig, Component config > Newlib > newlib level, choose normal. Please have a try.

For more details about "nano" formatting option, please see newlib readme file,                                                                                           search for '--enable-newlib-nano-formatted-io':
https://sourceware.org/newlib/README

**Comment by temmka** [comment]
Oh thanks a lot!
It works now)
