### ISSUE TITLE
8266 IDF SDK webserver application (GIT8266O-71)

### ISSUE THREAD

**Issue by invention88** [espressif/ESP8266_RTOS_SDK#306]
As the title, 8266 works in AP mode, when the webserver application demo can be provided.
For example, in 8266, a html page is burned, and after the PC is connected to 8266, you can access this page.

**Comment by 27-301** [comment]
@invention88 Yes, it will be available in v3.1. And the code will be merged in this month. Thanks.

**Comment by invention88** [comment]
hi, 
When is the release of V3.1 expected?
