### ISSUE TITLE
What improvements does the IDF-style SDK have in terms of flash usage?

### ISSUE THREAD

**Issue by invention88** [espressif/ESP8266_RTOS_SDK#307]
What improvements does the IDF-style SDK have in terms of flash usage?
I want to know more about the default configuration of the flash space.
In addition to the configuration options in menuconfig, can our developers modify the flash configuration in more detail and flexibly configure the flash application.
I hope to have detailed development documentation for the flash part of the application.

**Comment by 27-301** [comment]
@invention88 You can refer to https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/docs/en/api-guides/partition-tables.rst. Hope it's useful for you.

**Comment by invention88** [comment]
OK, thanks
