### ISSUE TITLE
wifi_pkt_rx_ctrl_t NO HAVE sig_len

### ISSUE THREAD

**Issue by zhsyourai** [espressif/ESP8266_RTOS_SDK#311]
https://github.com/espressif/ESP8266_RTOS_SDK/blob/36dbc137ffc68166d6dba172e1b1701cff9e3912/components/esp8266/include/esp_wifi_types.h#L332

**Comment by Junhao-Espressif** [comment]
Hi @zhsyourai 

Please use ```len = pkt->rx_ctrl.sig_mode ? pkt->rx_ctrl.HT_length : pkt->rx_ctrl.legacy_length``` instead of rx_ctrl.sig_len.

We will modify this note in the next version.

Thanks!

**Comment by zhsyourai** [comment]
Thanks very much!
