### ISSUE TITLE
建议打印log选择uart1, 且配置SDK时候打印口语烧写口可选择不同串口

### ISSUE THREAD

**Issue by wanghui0574xs** [espressif/ESP8266_RTOS_SDK#313]
建议打印log选择uart1, 且配置SDK时候打印口语烧写口可选择不同串口

**Comment by xiongyumail** [comment]
Hi @wanghui0574xs 

首先感谢你的建议。
默认uart0打印log是因为开发板只需要使用一颗USB转UART芯片即可实现下载和调试的功能。
如果客户有uart1打印log的需求可以自行在代码中重定向系统打印到uart1
后续SDK版本可以在menuconfig中选择log输出口。
