### ISSUE TITLE
SDK 3.0 I2C

### ISSUE THREAD

**Issue by weswitt** [espressif/ESP8266_RTOS_SDK#316]
I know the guidance is to post question on the espressif site, but I've tried that in the past and nothing happens so I'm trying here.

What is the recommended method for using I2C with the 3.0 SDK given that there is no I2C driver included in the SDK?

**Comment by xiongyumail** [comment]
Hi @weswitt 
This month I2C will be integrated into SDK V3.1

sorry for keeping you waiting.

**Comment by Mr-Pi** [comment]
Is there any known working workaround around?

**Comment by 27-301** [comment]
It's already in the master branch, please have a try.
