### ISSUE TITLE
Config_LWIP_MAX_SOCKETS not used

### ISSUE THREAD

**Issue by jhinklejr** [espressif/ESP8266_RTOS_SDK#328]
Config_LWIP_MAX_SOCKETS from sdkconfig.h is not used

I suspect you wanted to make ESP_SOCKET_MAX defined in esp_socket.c be assigned that value

**Comment by donghengqaz** [comment]
`CONFIG_LWIP_MAX_SOCKETS` has add to `sdkconfig.h`.

**Comment by kurta999** [comment]
With ESP WROVER it's possible to increase this to 16? Does somebody already tried it?
