### ISSUE TITLE
Malloc/Free enhancement - are you interested

### ISSUE THREAD

**Issue by jhinklejr** [espressif/ESP8266_RTOS_SDK#336]
The current malloc/free management process does not detect buffer over/under runs and does not detect trying to free a pointer that was not acquired by malloc.

I have removed trace from my malloc/free until I see what you folks are going to do based on my last post.

I have added a 4 byte buffer header and a 4 byte buffer trailer surrounding the memory acquired by malloc.

So - the enhancement costs 8 bytes per malloc request -- this does not change your current malloc code -- it amends the buffer after acquired by malloc by adjusting the malloc request size by 8 bytes.

The Free changes as follows:

1.  Since I have made my TRACE fixed at build -- not dynamic run-time action, I know how large the HEAD struct is (your 8 bytes for pointer plus my 4 for detection).  Free now adjusts the free ptr value by the HEAD size and then uses that information to validate my buffer over/under run detecting values.

If my start header detection is bad -- it either means the pointer passed into FREE was bad or an under-run of the buffer occurred.  Either way, Free does nothing but report the error and returns.

If the end header detection is bad - FREE again does nothing and returns.

I also added the capability that when FREE actually releases memory back to the available heap -- all the memory associated with that memory (my 8 byte detection headers and possibly your HEAD structure) are set to a known value -- currently I set to zero.

I also have a heap walk function that walks and reports all the structures in the heap for debug purposes.

If this sounds like something you are interested in, I would be pleased to provide it to you.

**Comment by donghengqaz** [comment]
At first I may not use an extra flag(4 bytes) the mark if the memory block is used or if it is traced, I just use a bit to add it to the prev or next memory block pointer data, because I want to save memory as much as possible.

**Comment by jhinklejr** [comment]
Please close
