### ISSUE TITLE
Explain your use of Socket_MT

### ISSUE THREAD

**Issue by jhinklejr** [espressif/ESP8266_RTOS_SDK#342]
lwip and your documentation is vague on multithreading.

From my reading - the use of a socket in lwip is restricted to a single thread but multiple threads can create and use a socket as long as socket activity is restricted to that thread.

If THAT is true - then what is the purpose of your socket_mt implementation?

Is your implementation ONLY required is a specific socket is to be used by multiple threads and your lock/unlock of that socket makes sure one thread's request is returned before another thread can have access?

Here is why I ask ... I have a thread that only works with a single TCP socket.  I have another thread that works with multiple UDP sockets.

Do I really need to use your socket_mt or an I thread safe without it?

Thanks

**Comment by donghengqaz** [comment]
I think you can use "socket_mt" to make socket mutil-thread safe, because we internal testcases have cover some multi-thread case, it may reduce some cpu usage, but a little safer.

**Comment by donghengqaz** [comment]
If your function will not make these tasks using sockets competition and synchronization， you can drop this "mt" function.

**Comment by jhinklejr** [comment]
Please close
