### ISSUE TITLE
Release/v3.0 hardware timer driver missing

### ISSUE THREAD

**Issue by Bennji94** [espressif/ESP8266_RTOS_SDK#347]
In the release/v3.0 there is no driver for the hardware timer and the espos_timer only works with at least 1ms period. Is it possible to use the timer for 200 microseconds or will the driver for the hardware timer be added?

**Comment by donghengqaz** [comment]
The plan to add hardware timer at v3.1 as soon as possible. Could you tell me why you need 200 microseconds timer?

**Comment by FayeY** [comment]
@Bennji94 Could you share more information with us? So we can provide more advice for your usage scenario. Thanks.
