### ISSUE TITLE
The "ESP8266_RTOS_SDK_Programming_Guide" link is broken

### ISSUE THREAD

**Issue by crdev** [espressif/ESP8266_RTOS_SDK#348]
Clicking [ESP8266_RTOS_SDK_Programming_Guide] (linked to http://bbs.espressif.com/viewtopic.php?f=51&t=1023) at https://github.com/espressif/ESP8266_RTOS_SDK/wiki results in "The requested topic does not exist."

**Comment by FayeY** [comment]
Hi @crdev , we refactored the RTOS SDK to be ESP-IDF style, the programming guide is for the old versions, please refer to the [ESP8266_RTOS_SDK/examples](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples) to implement your applications. 
And if you met any question in developing, please feel free to let us know.
Thanks.
