### ISSUE TITLE
1M 的Flash，OTA的第二分区必须起始于0x80000？

### ISSUE THREAD

**Issue by Tangle-1990** [espressif/ESP8266_RTOS_SDK#352]
如题，因为公司的完整功能代码会超过500k，所以想采用不对称分区来进行固件升级。目前的想分配一个不大于300K的OTA分区来负责固件升级。但我发现只要第二个分区起始地址不是0x80000，app2.bin就无法运行。下面是第二分区的加载信息：
`I (51) boot: ESP-IDF v3.1-dev-259-g4c8e045-dirty 2nd stage bootloader`
`I (52) boot: compile time 21:04:12`
`I (52) boot: SPI Speed      : 26.7MHz`
`I (56) boot: SPI Mode       : QIO`
`I (60) boot: SPI Flash Size : 1MB`
`I (64) boot: Partition Table:`
`I (68) boot: ## Label            Usage          Type ST Offset   Length`
`I (75) boot:  0 nvs              WiFi data        01 02 00009000 00004000`
`I (82) boot:  1 otadata          OTA data         01 00 0000d000 00002000`
`I (90) boot:  2 phy_init         RF data          01 01 0000f000 00001000`
`I (97) boot:  3 ota_0            OTA app          00 10 00010000 00050000`
`I (104) boot:  4 ota_1            OTA app          00 11 00060000 00050000`
`I (112) boot: End of partition table`
`I (116) esp_image: segment 0: paddr=0x00060010 vaddr=0x40280010 size=0x32df0 (208368) map`
`I (179) esp_image: segment 1: paddr=0x00092e08 vaddr=0x3ffe8000 size=0x0052c (  1324) load`
`I (180) esp_image: segment 2: paddr=0x0009333c vaddr=0x3ffe852c size=0x0012c (   300) load`
`I (187) esp_image: segment 3: paddr=0x00093470 vaddr=0x40100000 size=0x062a0 ( 25248) load`
`0x40100000: _stext at ??:?`

`I (202) boot: Loaded app from partition at offset 0x60000`

我个人推测程序在运行时，是使用vaddr取获取指令，但我的code实际起始地址是paddr。请问修改哪部分代码，可以让map的vaddr=0x40200000 + paddr。

**Comment by Tangle-1990** [comment]
额，我已经找到方法了。需要修改ESP8266_RTOS_SDK/components/esp8266/ld/esp8266.ld。esp8266.ld中计算第二分区的len字段为何还需要减去APP_OFFSET? 这儿会产生溢出，不知道有没有什么影响

**Comment by donghengqaz** [comment]
你在 Makefile 里面指定以下参数就可以了
‘’‘
APP1_OFFSET ：= 0x10000
APP1_SIZE ：= 0x70000
APP2_OFFSET ：= 0x80000
APP2_SIZE ：= 0x70000

include $(IDF_PATH)/make/project.mk
’‘’
这个你可以再试下这个方法
