### ISSUE TITLE
为什么espconn_recv 没有引出来让用户用呢？

### ISSUE THREAD

**Issue by philar** [espressif/ESP8266_RTOS_SDK#354]
使用的SDK ：https://github.com/espressif/ESP8266_RTOS_SDK/tree/release/v2.x.x
在写tcp server的时候一开始使用espconn_regist_reconcb 注册的接收回调函数处理接收到的数据，但是因为回调函数里面会有阻塞的情况，导致在接收的时候无法发送数据，后来发现有espconn_recv这个API ，发现但是没有引出，让用户使用，不知道是不是这个API还没有完善，还是其他原因呢？

**Comment by 27-301** [comment]
espconn 原来是在 NonOS 平台开发的，在 RTOS 平台未做很好的测试，我们也不推荐用户使用。在 RTOS 平台，建议使用 socket 来开发网络应用。
