### ISSUE TITLE
how to set bin path in makefile?

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/ESP8266_RTOS_SDK#360]
how to set bin path in makefile?

**Comment by 1XiaSheng** [comment]
怎么设置bin文件输出路径?

**Comment by donghengqaz** [comment]
你用的哪个版本，如果是 V2.x 和 之前的，可以通过环境变量设置: export BIN_PATH=.... ，如果是之后的（v3.0 等等）， export BUILD_DIR_BASE=...

**Comment by 1XiaSheng** [comment]
3.0的SDK,

**Comment by FayeY** [comment]
@1XiaSheng 请问，以上建议 “ export BUILD_DIR_BASE=...” 是否解决了你的问题？
