### ISSUE TITLE
[GIT8266O-40] 在AP配网后切换到STA模式，不会连接AP

### ISSUE THREAD

**Issue by ChampOnBon** [espressif/ESP8266_RTOS_SDK#362]
我参考simple_wifi的代码实现了自定义的AP+TCP服务器配网，在切换到STA模式后，串口打印了以下内容
station: f8:da:0c:36:13:9b leave, AID = 1
rm 1
bcn 0
del if1
usl
sul 0 0
mode : sta(5c:cf:7f:88:ea:ca)
add if0
[0;32mI (17232) chp iot: station:f8:da:0c:36:13:9bleave, AID=1[0m
但是没有打印scandone，不会连接AP，按下rst按键重启模块后能够正常连接AP。而如果在app_main函数中使用和配网时相同的代码直接连接AP则没有问题。

**Comment by Junhao-Espressif** [comment]
Hi @ChampOnBon  请提供切换到sta模式之后连接AP的代码。

**Comment by ChampOnBon** [comment]
代码如下：
bool chp_iot_wifi_set_station_mode(uint8_t * ssid, uint8_t * password)
{
    wifi_config_t wifi_config;
    memset(&wifi_config, 0, sizeof(wifi_config_t));
    strncpy((char *)wifi_config.sta.ssid, (char *)ssid, 32);
    strncpy((char *)wifi_config.sta.password, (char *)password, 64);

    if (esp_wifi_set_mode(WIFI_MODE_STA) != ESP_OK
        || esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config) != ESP_OK
        || esp_wifi_start() != ESP_OK)
    {
        return false;
    }
	return true;
}

**Comment by Junhao-Espressif** [comment]
调用下esp_wifi_connect()
