### ISSUE TITLE
Error in hw_timer_init function

### ISSUE THREAD

**Issue by irvinvp** [espressif/ESP8266_RTOS_SDK#37]
hw_timer.c:79:5: error: passing argument 2 of '_xt_isr_attach' from incompatible pointer type [-Werror]

**Comment by baoshi** [comment]
There is a change to _xt_isr_attach prototype. The ISR now expects one additional parameter void *arg. I think espressif did not update the sample code.

**Comment by Orgmar** [comment]
https://github.com/espressif/ESP8266_RTOS_SDK/pull/42
plz try
