### ISSUE TITLE
配网成功，但是没有回调？

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_RTOS_SDK#372]
- 最近遇到奇怪的事情，在`smartConfig`配网成功后，在回调函数并没有提示`SC_STATUS_LINK_OVER`状态：

- 手机也没有提示配网成功？我使用的是 `SDK version:2.0.0(7408579) ` 

![qeeop y 5 z a0i 6 tot](https://user-images.githubusercontent.com/25237870/48041774-b95ed780-e1b9-11e8-8f19-5f1ab55e0b68.png)

**Comment by FayeY** [comment]
想请问，是否考虑使用我们最新版本的 SDK v3.0?

**Comment by FayeY** [comment]
由于长时间无更新，此问题暂时关闭。如果问题仍未解决，欢迎 reopen issue，再与我们联系。谢谢！
