### ISSUE TITLE
[GIT8266O-47] Remove from console msgs like (station: XX, add 1, rm 1)

### ISSUE THREAD

**Issue by skiller2** [espressif/ESP8266_RTOS_SDK#375]
## Environment

- Development Kit:
- IDF version: 14d8307 
- Development Env:      Eclipse
- Operating System:     Windows
- Power Supply:         USB

## Problem Description

Is there any way to disable console messages like: 
   station: XX:XX
   add 1
   rm 1

### Expected Behavior
   Disable showing in the console WIFI msgs.

### Actual Behavior
   Show messages 
   station: XX:XX
   add 1
   rm 1

### Steps to repropduce

In make menuconfig 
   Default log verbosity (No output)

[sdkconfig.txt](https://github.com/espressif/ESP8266_RTOS_SDK/files/2558404/sdkconfig.txt)

**Comment by FayeY** [comment]
Please have a try with the latest master, it should have added the log tag level. Thanks.
