### ISSUE TITLE
WIFI Radio MAC

### ISSUE THREAD

**Issue by jhinklejr** [espressif/ESP8266_RTOS_SDK#381]
Does your radio drive input into a typical Ethernet type MAC?

If you have an Ethernet type hardware MAC, does it do automatic checking of network header checksums?

Thanks

**Comment by donghengqaz** [comment]
You can check if the LwIP software checksum is used. If it is not used, hardware di this.

**Comment by jhinklejr** [comment]
Thanks.

Don't know why I didn't think of that.

Please close.
