### ISSUE TITLE
Configurable configTICK_RATE_HZ ?

### ISSUE THREAD

**Issue by Mr-Techtron** [espressif/ESP8266_RTOS_SDK#383]
_Originally posted by @Mr-Techtron in https://github.com/espressif/ESP8266_RTOS_SDK/issues/176#issuecomment-391780759_

**Comment by xiongyumail** [comment]
Please re-pull RTOS 2.x.x and compile freertos

**Comment by Mr-Techtron** [comment]
I've re-pull RTOS 2.x.x and compile freertos but still there is no effect. FreeRTOS tick is still 10ms

**Comment by Mr-Techtron** [comment]
can someone please guide me here?

**Comment by donghengqaz** [comment]
You must change the macro "XT_TICK_DIVISOR", it will change the CPU tick cycle. config_TICK_RATE_HZ just affect the FreeRTOS not hardware.

**Comment by Mr-Techtron** [comment]
@donghengqaz, I did what you said and recompile freertos but still, I can't change my CPU tick cycle. Have you tried this out by yourself? Is there something that I'm missing here?

**Comment by FayeY** [comment]
Hi, sorry that RTOS 2.x.x does not support this feature, but RTOS 3.1 does. Would you like to have a try with the RTOS 3.1 branch? It is the new IDF style SDK that we will focus on.

**Comment by FayeY** [comment]
Closing for now due to lack of response, please feel free to reopen if this is still an issue with the latest SDK. Thanks.
