### ISSUE TITLE
How do I implement spi?

### ISSUE THREAD

**Issue by NickAABB** [espressif/ESP8266_RTOS_SDK#384]
I need to use spi. There are no routines. How can I implement it?

**Comment by xiongyumail** [comment]
Hi @NickAABB 
The spi driver will be released in version 3.1.

**Comment by NickAABB** [comment]
When will version 3.1 be updated? We are in a hurry.

**Comment by FayeY** [comment]
[V3.1 release candidate](https://github.com/espressif/ESP8266_RTOS_SDK/releases) is on GitHub now, please have a try. Thanks.
