### ISSUE TITLE
smart config 配置问题

### ISSUE THREAD

**Issue by zhubinghan** [espressif/ESP8266_RTOS_SDK#387]
我用乐鑫新发布的 esp8266 sdk3.0，用自带的例子，但是smartconfig成功率很低。10次里不一定会有一次成功。手机是安卓7.0的小米5手机，esptouch版本是v0.3.7.0  。不知道有没有办法提高配置成功率。

 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x40100000, len 4364, room 16
0x40100000: _stext at ??:?

tail 12
chksum 0x0d
ho 0 tail 12 room 4
load 0x3ffe8008, len 3428, room 12
tail 8
chksum 0x77
I (34) boot: ESP-IDF v3.1-dev-190-g93e9b1c-dirty 2nd stage bootloader
I (34) boot: compile time 16:21:02
I (34) boot: SPI Speed      : 40MHz
I (39) boot: SPI Mode       : QIO
I (42) boot: SPI Flash Size : 2MB
I (46) boot: Partition Table:
I (50) boot: ## Label            Usage          Type ST Offset   Length
I (57) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (64) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (72) boot:  2 factory          factory app      00 00 00010000 000f0000
I (79) boot: End of partition table
I (83) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x50788 (329608) map
I (157) esp_image: segment 1: paddr=0x000607a0 vaddr=0x3ffe8000 size=0x00550 (  1360) load
I (158) esp_image: segment 2: paddr=0x00060cf8 vaddr=0x3ffe8550 size=0x0012c (   300) load
I (165) esp_image: segment 3: paddr=0x00060e2c vaddr=0x40100000 size=0x06cf0 ( 27888) load
0x40100000: _stext at ??:?

I (179) boot: Loaded app from partition at offset 0x10000
I (15) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (10) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
mode : sta(cc:50:e3:09:5b:f9)
add if0
SC version: V2.5.4
scandone
scandone
I (5070) sc: SC_STATUS_FINDING_CHANNEL

TYPE: ESPTOUCH
T|PHONE MAC: 78 02 f8 21 3a 4f
T|AP MAC   : c4 36 55 ea be 04
I (72932) sc: SC_STATUS_GETTING_SSID_PSWD

每次就死在获取ssid和密码这里。

**Comment by hvritual** [comment]
😳 一样遇上的这个问题_ 我用的是ios12.1  EspTouch 0.3.7 现在在抓手机发送的udp报文

**Comment by Werner42** [comment]
上面用iOS的。我之前试的时候也是，基本不会成功。但我看到前两天espressif esptouch这个app更新了。写着修复了iOS12下的wifi info问题。我还没试过，你可以试一下。

**Comment by hvritual** [comment]
> 上面用iOS的。我之前试的时候也是，基本不会成功。但我看到前两天espressif esptouch这个app更新了。写着修复了iOS12下的wifi info问题。我还没试过，你可以试一下。

我这边就是使用最新版本的ios 还是不能正常工作 现在准备是用Android 来进行测试一下

**Comment by ustccw** [comment]
可以基于最近的 master 测试一下, 看看问题是否还存在.

**Comment by Werner42** [comment]
> 可以基于最近的 master 测试一下, 看看问题是否还存在.
我刚才pull一下新的，用的ios 下的 espressif esptouch，现在没有卡死可以配置成功了。

**Comment by hvritual** [comment]
最新的固件可以正常使用smartconfig了 配置不是esptouch的原因 是固件的问题 后面8266的固件重新升级了

**Comment by 27-301** [comment]
非常感谢 @Werner42 @hvritual 两位同步的信息，最近对 smartconfig 做了较大的优化。

**Comment by 27-301** [comment]
谢谢各位的反馈，先关闭该问题，如需要新问题，请再提出。
