### ISSUE TITLE
Meaning of esp_aio_sendto() CB error

### ISSUE THREAD

**Issue by jhinklejr** [espressif/ESP8266_RTOS_SDK#388]
esp_aio_sendto() return an error code via it's CB function -- low_level_send_cb().

The CB function return aio->ret as an error code.

What does a return of 2 mean?

What does a return of 4 mean?

Are these error codes documented someplace?

Thanks

**Comment by jhinklejr** [comment]
I think I may have found the enum for the replies - esp_wifi_types.h

What does TX_STATUS_SRC_EXCEED mean?

What does TX_STATUS_LRC_EXCEED mean?

**Comment by jhinklejr** [comment]
Here is a line of code from LWIP -- 
        LWIP_DEBUGF(PBUF_CACHE_DEBUG, ("Send packet fail: result:%d, LRC:%d, SRC:%d, RATE:%d",
                                       status->wifi_tx_result, status->wifi_tx_lrc, status->wifi_tx_src, status->wifi_tx_rate));

What is wifi_tx_lrc?

What is wifi_tx_src?

Thanks

**Comment by donghengqaz** [comment]
@Junhao-Espressif

**Comment by jhinklejr** [comment]
Hi

 

I don’t understand your reply – just a user name.

 

I had asked what These variables were:

 

What is wifi_tx_lrc?

What is wifi_tx_src?

 

They are part of the argument returned to the Transmit CBV function:

 

esp_aio_sendto() return an error code via it's CB function -- low_level_send_cb().

 

Thanks

**Comment by donghengqaz** [comment]
Hi, I am sorry that i don't master at the field of Wi-Fi, but JunHao he is the one.

**Comment by Junhao-Espressif** [comment]
Hi @jhinklejr ,

src means the number of times rts was send before AP send cts to us.

lrc means the number of times unicast data was send before AP send ack to us.
