### ISSUE TITLE
how to use api in esp_socket.h,can we get an example?

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/ESP8266_RTOS_SDK#389]
in the file esp_socket.h,these are many good apis,
int esp_socket(int domain, int type, int protocol);
int esp_aio_sendto(esp_aio_t *aio, const struct sockaddr_ll *to, socklen_t len);
int esp_aio_event(int fd, unsigned int event, esp_aio_cb_t cb, void *arg);
int esp_upload_event(void *index, esp_socket_info_t *info, unsigned int event, esp_aio_data_t *aio_data);
int esp_free_pbuf(int fd, void *pbuf);
int esp_ioctl(int fd, unsigned int cmd, ...);
int esp_close(int fd);

hwo to config the struct esp_socket_method_t; and use those api upon?
can wen get an example for test?
thsanks.

**Comment by donghengqaz** [comment]
These apis are just for TCP-IP stack conmunicate with Wi-Fi stack. And you can see how to use the component at "tcpip_adapter".
