### ISSUE TITLE
espos_task_create(task, name, arg, prio, ticks, stack_size, entry, opt); what's that means?

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/ESP8266_RTOS_SDK#395]
what those par means?
espos_task_create(task, name, arg, prio, ticks, stack_size, entry, opt)

**Comment by 1XiaSheng** [comment]
int esp_aio_event(int fd, unsigned int event, esp_aio_cb_t cb, void *arg)

**Comment by donghengqaz** [comment]
These are platform abstract APIs for internal or paltform development, not for application. You should not watch these if you are not CPU/OS developor.
