### ISSUE TITLE
wifi APSTA mode - will not connect to AP

### ISSUE THREAD

**Issue by jhinklejr** [espressif/ESP8266_RTOS_SDK#397]
Task that runs WIFI Event Handler has priority 5.

I have a web server running in AP mode that presents the user with the results of scanning APs.

User selects AP to connect to -- I capture SSID, BSSID and password.

I configure STA to connect .. but 30% of the time -- A connection is not made.

When I scan for APs, the signal strength of the chosen AP is around -55 to -65.  

When a connection is attempted (STA connect to AP) is the signal strength associated with the connection process different from that acquired during the scan?

Any ideas WHY -- I can acquire AP info in AP scan but can not connect via STA.

If signal strength around -35 (This is what I get using a AP close to my development platform) - connection always made.  Same code at customer site with scan signal strength of -65 , I don't always get a connection.

As I am typing this - I need to clarify -- I use the term connection which is different from connection but not acquire an IP (which is a DHCP process after connection).  I don't know right now which of the two is failing:

#1 - no connection.
#2 - connect but no IP acquired.

I will instrument my customers device to answer that question, but in the mean-time -- any ideas?

Thanks.

**Comment by Dipendra77** [comment]
Hey i am facing the similar issue. When I try to run the device in APSTA mode it is making connection but it disconnects every few seconds and restarts. Here is a snippet of my wifi_init() code in APSTA mode.
 
void wifi_init()
{

  wifi_event_group = xEventGroupCreate();
  tcpip_adapter_init();
  ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL) );

  wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
  ESP_ERROR_CHECK(esp_wifi_init(&cfg));

  strncpy((char*)sta_config.sta.ssid, WIFI_SSID, 32);
  strncpy((char*)sta_config.sta.password, WIFI_PASS, 64);

  wifi_config_t ap_config = {
    .ap = {
      .ssid = AP_SSID,
      .ssid_len = strlen(AP_SSID),
      .max_connection = 3,
      .authmode = WIFI_AUTH_OPEN,
      .beacon_interval = 0;
    
    },
  };

  ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_APSTA));
  ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_STA, &sta_config));
  ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_AP, &ap_config));
  ESP_ERROR_CHECK(esp_wifi_start());
    ESP_LOGI(WIFI_TAG, "wifi_init finished.SSID:%s password:%s",WIFI_SSID, WIFI_PASS);

}

Can you be kind enough to help me with this?
