### ISSUE TITLE
何时能支持CMake？ (GIT8266O-55)

### ISSUE THREAD

**Issue by gkcity** [espressif/ESP8266_RTOS_SDK#400]
何时能支持CMake？

**Comment by redchenjs** [comment]
合并到esp-idf以后不就有了

**Comment by gkcity** [comment]
> 合并到esp-idf以后不就有了

那大概还需要多久才能合并完成？

**Comment by redchenjs** [comment]
@wujiangang

**Comment by donghengqaz** [comment]
你有什么功能必须要 CMake 才能实现的吗？

**Comment by gkcity** [comment]
我这边的代码都是CMake工程，如果8266也支持cmake，那移植到8266会快很多，几乎不用怎么修改.

**Comment by donghengqaz** [comment]
好的，原本在 v3.0 中已经添加了 cmake 的配置脚本，后俩没有就缺少维护了，等 v3.1 release 以后我会完善这些脚本。

**Comment by gkcity** [comment]
好的，辛苦了。

**Comment by 1XiaSheng** [comment]
还能看到你们两个能够进行愉快的聊天啊

**Comment by FayeY** [comment]
Please have a try with the latest v3.2, it supports cmake. Thanks.
