### ISSUE TITLE
[GIT8266O-44] Memory Leak on Interrupt Handler

### ISSUE THREAD

**Issue by filzek** [espressif/ESP8266_RTOS_SDK#407]
Hi @wujiangang 

We did face a issue where ISR causing memory leak (Master) if you use a routine that manipulate any kind of volatile variables it cause a memory leakage and it disrupt all the memory until 16KB being free. 

We try to find what kind of operations cause the leak but so far the cause is the ISR. Need to check.

I can provide private proprietary code to exam and find solution in the driver part.

**Comment by donghengqaz** [comment]
ISR is always used by hardware driver, could you please tell which driver causes this problem? And could you supply the application for it?

**Comment by filzek** [comment]
When manipulate char arrays with malloc instructions inside ISR, we try to find solution but is impossible to fix, didnt find where it creates the memory leak, but it does until 16kb and stop.

**Comment by donghengqaz** [comment]
We have fixed some bugs recently, is your problem there ?
