### ISSUE TITLE
problem with regex.h

### ISSUE THREAD

**Issue by grays820** [espressif/ESP8266_RTOS_SDK#409]
hi guys,
    i want to use regex in my project, but when i inlude regex.h, it still raise me error like above, plz help me out ,tks.

C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/test/build/main\libmain.a(user_main.o):(.literal.txxx+0xc): undefined reference to `regcomp'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/test/build/main\libmain.a(user_main.o):(.literal.txxx+0x10): undefined reference to `regexec'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/test/build/main\libmain.a(user_main.o):(.literal.txxx+0x18): undefined reference to `regfree'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/test/build/main\libmain.a(user_main.o): In function `txxx':
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/test/main/user_main.c:51: undefined reference to `regcomp'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/test/main/user_main.c:61: undefined reference to `regexec'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/test/main/user_main.c:86: undefined reference to `regfree'

**Comment by donghengqaz** [comment]
If you use v3.0 and above you may add "regex " to your own application components, perfer to [example](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/get-started/project_template).
