### ISSUE TITLE
关于gpio14 红外发送的问题. (GIT8266O-59)

### ISSUE THREAD

**Issue by vachelcai** [espressif/ESP8266_RTOS_SDK#412]
----------------------------- Delete below -----------------------------

现在下载了网上一个例子,不过跑不起来,而且好像是1.5的版本,非现在3.0版本,里面提到用iis的时钟脚.
有几点不太清楚的
1.是循环填充数据,让iis一直发送脉冲,然后在需要空白的时候停止时钟么?
2.SDK3.0中iis完全没有提到,也没有寄存器资料,希望提供,还有示例里面还用到dma,是必需还是只是没修改而已?
3.是不是spi如果不是用于flash也一样可以实现?
4.sigma-delta有更多的介绍么?

INSTRUCTIONS
============

Before submitting a new issue, please follow the checklist and try to find the answer.

- [ ] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [ ] I have searched the issue tracker for a similar issue and not found a similar issue.

If the issue cannot be solved after the steps before, please follow these instructions so we can get the needed information to help you in a quick and effective fashion.

1. Fill in all the fields under **Environment** marked with [ ] by picking the correct option for you in each case and deleting the others.
2. Describe your problem.
3. Include [debug logs on the monitor](http://esp-idf.readthedocs.io/en/latest/get-started/idf-monitor.html#automatically-decoding-addresses).
4. Provide more items under **Other items if possible** can help us better locate your problem.
5. Use markup (buttons above) and the Preview tab to check what the issue will look like.
6. Delete these instructions from the above to the below marker lines before submitting this issue.

----------------------------- Delete above -----------------------------

## Environment

- Development Kit:
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    //bd6ea4393c7d2f059fc4decc70f1ec3eb3597268
- Development Env:      [Arduino IDE|Make|Eclipse|other]
- Operating System:     [Windows|Ubuntu|MacOS]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description

//Detailed problem description goes here.

### Steps to repropduce

1. step1
2. ...

// It helps if you attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{
    
}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by xiongyumail** [comment]
8266可以使用I2S或者Sigma_Delta等产生IR的载波，但是Sigma_Delta的占空比只能到1/3

I2S和相关的SLC(DMA)计划在3.2进行发布。

**Comment by vachelcai** [comment]
能提早给个能运行的范例呢,在3.0sdk下能跑的..3.2不知道几时能看到哦

**Comment by FayeY** [comment]
目前最新的 master 已经添加了 I2S 功能。请知悉，谢谢。

**Comment by Fonger** [comment]
@vachelcai 我用最新的 ESP8266_RTOS_SDK 3.2 寫了一個紅外接收/發射範例 https://github.com/Fonger/ESP8266-RTOS-IR 是基於該例子的 I2S 最佳方案 占空比可到 1/2 請參考
