### ISSUE TITLE
NONOS所有版本和RTSO V3.0之前版本都不能支持64Mb OTA操作吗？

### ISSUE THREAD

**Issue by guanglun** [espressif/ESP8266_RTOS_SDK#413]
NONOS所有版本和RTSO V3.0之前版本都不能支持64Mb(8MB) OTA操作吗？
试了RTOS V3.0应该是可以支持64Mb OTA升级的，低于此版本的RTOS和所有NONOS都无法成功升级，看SDK是bootloader和spi_flash不支持导致的。如果我把2MB或者1MB的固件刷进去其他扇区就无法读写。
请问有谁对8MB OTA有使用经验？

**Comment by guanglun** [comment]
@FayeY 已经花了几天时间把工程转移到了SDK3.0环境，可以很好的支持8MB的OTA。使用新SDK的时候有几点不满意的地方:
1.编译速度很慢，尤其配置了menuconfig以后需要CONFIG很长时间才开始编译总体感觉就是相比以前版本的SDK(nonosdk rtossdk)编译体验要差很多.
2.串口的驱动程序感觉效率不高，我在根据串口Demo进行115200的4K数据连续接收的过程中发现有时候会出现丢包现象(OVF)，Demo默认设置收到100B的包触发一次FULL中断，我改成80以后好了一些，不过最后我还是在阅读SDK源码的基础上自己写了一份串口驱动最终才能顺利得接收。

**Comment by donghengqaz** [comment]
1. 你可以尝试 make -jn （n 为你的电脑的数量)
2. 你能把串口效率低具体原因说一下嘛？

**Comment by FayeY** [comment]
由于长时间无更新，此问题暂时关闭。如果有新问题，烦请另外提交。感谢对 ESP 的关注！
