### ISSUE TITLE
Can not use light sleep function with sdk release\v2.x.x

### ISSUE THREAD

**Issue by nghiaquy1991** [espressif/ESP8266_RTOS_SDK#418]
## Environment
- Development Kit: ESP8266-12E
- IDF version (``git rev-parse --short HEAD`` to get the commit id.):  
   f07915833fe22cf86b6c10f17a88500c162af9c4
- Development Env:      [Make]
- Operating System:     [Ubuntu]
- Power Supply:         [USB]

## Problem Description
I want to use force light-sleep function for my MQTT application. 
I have a timer, when it is timeout. I will set device to force light sleep, after a few section, I will wakeup device by an external INT.

- INT timer
void sleep_timer_callback (xTimerHandle xTimer)
{
    GPIO_ConfigTypeDef io_conf;
    wifi_station_disconnect();
    wifi_set_opmode(NULL_MODE);
    wifi_fpm_set_sleep_type(LIGHT_SLEEP_T);
    wifi_fpm_open();
    // Init wakeup pin
    io_conf.GPIO_IntrType = GPIO_PIN_INTR_DISABLE;
    io_conf.GPIO_Mode = GPIO_Mode_Input;
    io_conf.GPIO_Pin = WAKEUP_PIN_BIT;
    io_conf.GPIO_Pullup = GPIO_PullUp_DIS;
    gpio_config(&io_conf);
    wifi_enable_gpio_wakeup(WAKEUP_PIN, GPIO_PIN_INTR_HILEVEL);
    wifi_fpm_set_wakeup_cb(wakeup_callback);
    wifi_fpm_do_sleep(0xFFFFFFFF);
}

- Wakeup callback
static void wakeup_callback (void)
{
    wifi_fpm_close();
    wifi_set_opmode(STATION_MODE);
    wifi_station_connect();
}
But I also use another pin for INT button.
void IRAM_ATTR gpio_intr_handler(void)
{
}
### Expected Behavior
1. Device will sleep when timer timeout.
2. Device will wakeup from function wakeup_callback.

### Actual Behavior
1. After call wifi_fpm_set_wakeup_cb(wakeup_callback); the current still >75 mA --> device is not in light sleep.
2. Change wakeup pin from low to high. The code implement function gpio_intr_handler(), so the function wakeup_callback  will never run.

Dear Esspressif team, Please help me fix this issue. Thanks

**Comment by donghengqaz** [comment]
Could any low-power example can work ?

**Comment by donghengqaz** [comment]
I know a little low power management, so I may cost much time.

**Comment by nghiaquy1991** [comment]
Dear donghengqaz,
"Could any low-power example can work ?" 
No, I trying but no one can work.
"I know a little low power management, so I may cost much time."
I understand, I am still waiting for your solution.

**Comment by nghiaquy1991** [comment]
Hi FayeY,
When I use `wifi_set_sleep_type(LIGHT_SLEEP);`
My current consumption of ESP8266 diagram look like:
![current](https://user-images.githubusercontent.com/22209364/50945327-c6a08700-14c6-11e9-8662-f60d4e972585.PNG)
My Avg current is about 27 mA.
Base on issue #290 I guess that I can not improve this result with v3.0.0
So, I am still base on v2.x.x

Does the latest V3.0.1 have a better power consumption in light sleep?

**Comment by Junhao-Espressif** [comment]
Hi @nghiaquy1991 

Could you try with master？

We will release V3.1 very soon.

**Comment by FayeY** [comment]
We have pre-released the [V3.1 RC1](https://github.com/espressif/ESP8266_RTOS_SDK/releases) which reduced the power consumption, would you like to have a try? Thanks.

**Comment by nghiaquy1991** [comment]
Thanks you so much.

I will try and report again.
