### ISSUE TITLE
还是用中文吧,  使用最新SDK 编译出错

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/ESP8266_RTOS_SDK#422]
F:/esp/ESP8266_RTOS_SDK/components/esp-tls/esp_tls.c: In function 'esp_tcp_conne   ct':
F:/esp/ESP8266_RTOS_SDK/components/esp-tls/esp_tls.c:106:10: error: dereferencin   g pointer to incomplete type 'struct sockaddr_in6'
         p->sin6_port = htons(port);
          ^
make[1]: *** [/f/esp/ESP8266_RTOS_SDK/make/component_wrapper.mk:286：esp_tls.o]    错误 1
make: *** [F:/esp/ESP8266_RTOS_SDK/make/project.mk:467：component-esp-tls-build]    错误 2

**Comment by Werner42** [comment]
你ipv6 没开吧……

**Comment by 1XiaSheng** [comment]
我在make menuconfig里面关闭了IPV6

**Comment by 1XiaSheng** [comment]
必须打开吗?

**Comment by 1XiaSheng** [comment]
打开IPV6后编译通过.

**Comment by 27-301** [comment]
会加个宏把 esp-tls 中的 IPV6 代码屏蔽掉，否则开了 IPV6 不用，内存和目标文件开销都会变大。
