### ISSUE TITLE
lwip  read 阻塞将近120秒

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/ESP8266_RTOS_SDK#434]
使用 lwip  #define read(s,mem,len)      lwip_read(s,mem,len)
使用 lwip read 阻塞了将近2分钟!menuconfig 中有没有默认接收超时参数? 没有的话要告知用户. 我最开始没有这个情况, 后来更新了SDK就有, 必须手动设置吗?

**Comment by donghengqaz** [comment]
你的应用场景是什么？为了会阻塞这么长时间，难道这段时间都没有数据过来？

**Comment by FayeY** [comment]
请问，这个问题有更新吗？

**Comment by 1XiaSheng** [comment]
我使用 recv() 没问题了,希望文档中有点说明就好.
