### ISSUE TITLE
ESP8266 RTOS 3.0 and NONOS 2.2.1 https request ( GET method) download speed only 20KB/s How to fixed this problem

### ISSUE THREAD

**Issue by Msq001** [espressif/ESP8266_RTOS_SDK#438]

**Comment by FayeY** [comment]
Hi, there is an [OTA example](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/system), would you like to have a try?

**Comment by Msq001** [comment]
hi.  the OTA example is under 200kb/s， Can it reach 1 mb/s?

**Comment by donghengqaz** [comment]
The OTA example should write the flash, you can unmask the write flash function and test.
