### ISSUE TITLE
[GIT8266O-51] MQTTRun cycle failed

### ISSUE THREAD

**Issue by aibeb** [espressif/ESP8266_RTOS_SDK#441]
## Environment

- Development Kit:  bf27e5990f94983b6924d01bacea6fe66e8868c9
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    //bd6ea4393c7d2f059fc4decc70f1ec3eb3597268
- Development Env:      Make
- Operating System:     MacOS
- Power Supply:         USB

### Steps to repropduce

CONFIG_MQTT_SUB_TOPIC="/temperature"
CONFIG_MQTT_PUB_TOPIC="/temperature"

## Debug Logs

```
I (38201) example: wait wifi connect...
I (38221) example: MQTT Connecting
I (38241) example: MQTT Connected
I (38241) example: Use MQTTStartTask
I (38331) example: MQTT subscribe to topic /temperature OK
I (38341) example: MQTT published topic /temperature, len:17 heap:59100
I (38351) example: Message arrived[len:17]: message number 15
W (38351) mc: mqtt close session
E (38361) mc: MQTTRun cycle failed
W (42351) mc: mqtt close session
E (42351) example: Return code from MQTT publish is -1
```

## Other items if possible

- [x] sdkconfig file (attach the sdkconfig file from your project folder)
- [x] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [x] coredump (This provides stacks of tasks.)

**Comment by aibeb** [comment]
The latest demo used，Only the following differences
```
CONFIG_MQTT_SUB_TOPIC="/temperature"
CONFIG_MQTT_PUB_TOPIC="/temperature"
```

**Comment by ustccw** [comment]
@aibeb please make sure that your MQTT broker is still working.

**Comment by aibeb** [comment]
@ustccw  
Cycle print the following logs, mqrr broker is working。
```
I (38331) example: MQTT subscribe to topic /temperature OK
I (38341) example: MQTT published topic /temperature, len:17 heap:59100
I (38351) example: Message arrived[len:17]: message number 15
W (38351) mc: mqtt close session
E (38361) mc: MQTTRun cycle failed
W (42351) mc: mqtt close session
E (42351) example: Return code from MQTT publish is -1
```

**Comment by aibeb** [comment]
@ustccw 

You can run mqtt demo to do a test, only pub=sub, I think this problem must be

**Comment by ustccw** [comment]
@aibeb 此现象确实存在, 由于 sub topic == pub topic.  
1. 可以将 Pub QoS 设置为 0 即可.  
![selection_007](https://user-images.githubusercontent.com/24221485/51424714-dc235880-1c0c-11e9-9661-f6894da6d6c5.png)

2. 通常情况下, 不应该设置 sub topic == pub topic, 因为 MQTT 消息会发给自己, 没有意义.

**Comment by cipibad** [comment]
Same issue for me also, pls advise

**Comment by ustccw** [comment]
@cipibad This phenomenon does exist because sub topic = pub topic.

1. you could set pub QoS=0 to make it work.
2. Normally, you shouldn't set sub topic = pub topic, because the MQTT message will be sent to you, which is meaningless.

**Comment by cipibad** [comment]
This means there is still bug in mqtt for QoS 1/QoS 2?

**Comment by ustccw** [comment]
if you want to set QoS1/QoS2, you should set recv cycle and publish interval in `make menuconfig`.

**Comment by ustccw** [comment]
**Normally, you shouldn't set sub topic = pub topic, because the MQTT message will be sent to you, which is meaningless.**

**Comment by cipibad** [comment]
I am not using same pub/sub. 
I have an application using mqtt and that was working in earlier versions (https://github.com/espressif/ESP8266_RTOS_SDK/commit/01d32b73d4cc370795c6b23b56841ad1d3984963)
It is using pub/sub on mqtt via SSL.

Currently subscribe looks to work only without SSL:
with ssl:

> connected with SSID, channel 6
> I (12826) event: sta ip: 192.168.201.203, mask: 255.255.255.0, gw: 192.168.201.1
> 
> E (13796) example: Return code from network connect is 1
> I (13796) example: wait wifi connect...
> E (14396) example: Return code from network connect is 1
> I (14396) example: wait wifi connect...
> I (14426) example: MQTT Connecting
> I (14446) example: MQTT Connected
> I (14456) example: Use MQTTStartTask
> I (14466) example: MQTT subscribe to topic /espressif/sub OK
> I (14506) example: MQTT published topic /espressif/pub, len:16 heap:5100
> I (19556) example: MQTT published topic /espressif/pub, len:16 heap:5100
> I (24586) example: MQTT published topic /espressif/pub, len:16 heap:5100

without ssl:
I (9970) event: sta ip: 192.168.201.203, mask: 255.255.255.0, gw: 192.168.201.1
I (11550) example: MQTT Connecting
I (11560) example: MQTT Connected
I (11560) example: Use MQTTStartTask
I (11580) example: MQTT subscribe to topic /espressif/sub OK
I (11630) example: MQTT published topic /espressif/pub, len:16 heap:52588
....
I (96420) example: Message arrived[len:14]: a3169da3.2a93c

Thank you,
Ciprian

**Comment by ustccw** [comment]
@cipibad MQTT based on SSL will be in the plan of `release v3.2`
