### ISSUE TITLE
wifi smartconfig log输出

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/ESP8266_RTOS_SDK#444]
SYNC: 0_0_62_62
SYNC: 0_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
SYNC: 62_62_62_62
smartconfig 模式中,这个数据SYNC的log是否有开关控制, 代表什么意思?

**Comment by FireWinter** [comment]
>           SYNC: 0_0_62_62
> SYNC: 0_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> SYNC: 62_62_62_62
> smartconfig 模式中,这个数据SYNC的log是否有开关控制, 代表什么意思?

log默认是关掉的，可通过传参来进行开关控制，打开需传参：smartconfig_main.c修改：esp_smartconfig_start(sc_callback, 1) ，关掉：esp_smartconfig_start(sc_callback）；
log只是debug的信息
