### ISSUE TITLE
Missing libupgrade.a

### ISSUE THREAD

**Issue by ganeshgreyson** [espressif/ESP8266_RTOS_SDK#45]
I was trying to do the FOTA but seems that libupgrade.a is missing. Does any one how to get the libupgrade.a

**Comment by Eszartek** [comment]
You obtain it by adding it to your project from the  ESP8266_IOT_PLATFORM project located here: https://github.com/espressif/ESP8266_IOT_PLATFORM/tree/master/upgrade . I suggest you start by building the ESP8266_IOT_PLATFORM project first to get to know how everything works, then incorporate it into your existing code.

**Comment by ganeshgreyson** [comment]
Thanks Eszartek, It works in RTOS sdk
