### ISSUE TITLE
 linux环境 按照README操作esp8266编译，打印乱码

### ISSUE THREAD

**Issue by beikeln** [espressif/ESP8266_RTOS_SDK#452]
你好：
我在linux 环境下按照README操作esp8266编译，跑示例的get-started project
make all    
make flash 
都是可以的
串口使用默认的波特率115200，但是上电后出现乱码
改用其他波特率也不行

**Comment by xiongyumail** [comment]
1. 可以在终端中直接看log， 使用`make monitor`
2. 其它串口调试软件请使用`74880`波特率

**Comment by beikeln** [comment]
谢谢
使用make monitor 打印是正常的。

但看了打印，make monitor 启动的也是 idf_monitor on /dev/ttyUSB0 74880
但我若使用其他串口，如：minicom  -D   /dev/ttyUSB0 -b 74880，这样显示仍然是乱码~

**Comment by beikeln** [comment]
是不是要用其他串口，需要在make menuconfig中将serial 设置成74880 再重新编译？

**Comment by 27-301** [comment]
不用，应该是 minicom 不支持 74880 的波特率，你可以使用 miniterm.py，度一下吧。
