### ISSUE TITLE
新版本找不到system_get_time()函数

### ISSUE THREAD

**Issue by beikeln** [espressif/ESP8266_RTOS_SDK#454]
你好：
新的3.1版本在esp_system.h中找不到 system_get_time()接口，
原2.1版本中是有的。
获取时间的这个函数接口不提供了吗？

**Comment by beikeln** [comment]
在components/lwip/apps/ping/ping.c:399 是有system_get_time()这个函数的调用，
请问头文件是哪个呢
thx

**Comment by donghengqaz** [comment]
You can use "extern uint32_t esp_get_time(void);"， it is replaced "system_get_time".

**Comment by woodyfan** [comment]
你好，这样后续需要获取时间戳直接i=esp_get_time();即可获得当前的毫秒时间戳了吗？

**Comment by Fonger** [comment]
@donghengqaz What is the difference between `esp_timer_get_time()` and `esp_get_time()`? And I' recommend add the definition for esp_get_time() in header with some comments.
