### ISSUE TITLE
aws iot demo aws_iot: failed! mbedtls_ssl_handshake returned -0x7200

### ISSUE THREAD

**Issue by myzhang001** [espressif/ESP8266_RTOS_SDK#461]
aws iot 连接失败
[0;31mE (17826) aws_iot: failed! mbedtls_ssl_handshake returned -0x7200[0m
[0;31mE (17866) subpub: Error(-4) connecting to apg8net6ftn73-ats.iot.us-west-2.amazonaws.com:8883[0m

**Comment by Junhao-Espressif** [comment]
Hi @myzhang001 ,

menuconfig ->
     Component config  --->
         SSL ->
             mbedTLS ->
                   TLS maximum INPUT message content length **(set to 16384)**

**Comment by myzhang001** [comment]
非常感谢你的解答，已经解决了
