### ISSUE TITLE
新更新的外设spi使用问题

### ISSUE THREAD

**Issue by Hynsn** [espressif/ESP8266_RTOS_SDK#466]
// Write an 8-bit cmd
static esp_err_t oled_write_cmd(uint8_t data)
{
    uint32_t buf = data << 24;
    spi_trans_t trans = {0};
    trans.mosi = &buf;
    trans.bits.mosi = 8;
    oled_set_dc(0);
    spi_trans(HSPI_HOST, trans);
    return ESP_OK;
}

请问8266的硬件SPI默认一次传输是32bit吗，我看了从 2.0 sdk到 3.0都是这样，因为在开发中通常还是按一个byte字节通信，请问 传输一个字节是否只能按照上述代码方法处理？是否考虑会提供byte为单位的api？

**Comment by xiongyumail** [comment]
esp8266的spi寄存器是32位的，但是可以自定义传输的bits,用户可以参考上述方法自行封装 byte为单位的api.

**Comment by Hynsn** [comment]
好的，谢谢。希望尽快完善spi外设驱动，spi比串口用途要多
