### ISSUE TITLE
aws iot  demo 证书问题

### ISSUE THREAD

**Issue by myzhang001** [espressif/ESP8266_RTOS_SDK#470]
hi,
    aws iot  demo 中证书的数组是存放在哪个文件里面呢

extern const uint8_t aws_root_ca_pem_start[] asm("_binary_aws_root_ca_pem_start");
extern const uint8_t aws_root_ca_pem_end[] asm("_binary_aws_root_ca_pem_end");
extern const uint8_t certificate_pem_crt_start[] asm("_binary_certificate_pem_crt_start");
extern const uint8_t certificate_pem_crt_end[] asm("_binary_certificate_pem_crt_end");
extern const uint8_t private_pem_key_start[] asm("_binary_private_pem_key_start");
extern const uint8_t private_pem_key_end[] asm("_binary_private_pem_key_end");

**Comment by 27-301** [comment]
第一，先看下：https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html#embedding-binary-data
第二，再看下：https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/protocols/aws_iot#option-1-embedded-key--cert-into-app-binary

**Comment by myzhang001** [comment]
我知道demo  中是把下载的文档放到cert 文件夹下面，但是在实际项目中是使用自己的服务器接收 这个该怎么处理呢，按我的理解应该是放到一个头文件里面是一串数组的形式存放在flash  里面

**Comment by 27-301** [comment]
这部分是在编译的时候自动处理了，会将证书文件作为 binary 文件自动转化为数组，并在链接的时候编译进目标文件，最终都是在 flash 中。

**Comment by myzhang001** [comment]
我如果动态的修改可以么，因为实际的场景是不能提前烧录的，需要认证后服务器下发证书给我，然后我修改flash 的数组，请问这个证书的地址是多少，还是说只能提前把证书给我然后编译进代码这种方式

**Comment by 27-301** [comment]
证书只是一组数据，你可以选择编译进目标代码，也可以选择放在 flash 的某个 sector 中，由你的程序来读取。

当前 demo 中是会编译进目标代码。

**Comment by myzhang001** [comment]
我想放在 flash  的某个sector  中，应该怎么做呢，是实例代码么

**Comment by donghengqaz** [comment]
下发的证书由于数量量不小，建议采用 partition 的形式存储下来，不要直接替换数组，可能会溢出的。参考文档：https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/docs/en/api-guides/partition-tables.rst ，API 位于 https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/spi_flash/include/esp_partition.h
