### ISSUE TITLE
newlib regex 无法使用 (GIT8266O-63)

### ISSUE THREAD

**Issue by grays820** [espressif/ESP8266_RTOS_SDK#479]
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/Test/build/components\libcomponents.a(anycmd.o):(.literal.process_cmd+0x8): undefined reference to `regcomp'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/Test/build/components\libcomponents.a(anycmd.o):(.literal.process_cmd+0xc): undefined reference to `regexec'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/Test/build/components\libcomponents.a(anycmd.o):(.literal.process_cmd+0x10): undefined reference to `regfree'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/Test/build/components\libcomponents.a(anycmd.o): In function `process_cmd':
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/AnyFreeRTOSLib/anycmd.c:139: undefined reference to `regcomp'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/AnyFreeRTOSLib/anycmd.c:149: undefined reference to `regexec'
C:/Users/grays/Documents/Workspace/MyProjects/AnyHardware/src/AnyFreeRTOSLib/anycmd.c:147: undefined reference to `regfree'

make flash会报无法找到这些函数，这个很重要啊。。

**Comment by donghengqaz** [comment]
newlib 暂时不支持这个功能，你有需要的话，我们尝试提供给你支持这个功能的 newlib 库。

**Comment by grays820** [comment]
> newlib 暂时不支持这个功能，你有需要的话，我们尝试提供给你支持这个功能的 newlib 库。

为啥暂时不支持，以后会加上么，因为如果自己要做AT的命令功能用正则做字符串操作快很多哎。。

**Comment by donghengqaz** [comment]
这个组件在 newlib 依赖 POSIX，编译 ESP8266 的 newlib 的支持库的时候是不带 POSIX 的，所以需要这个功能的话就得把依赖都带上，要么直接提取出来单独编译。
