### ISSUE TITLE
Firmware update sucks

### ISSUE THREAD

**Issue by MaiMariarti** [espressif/ESP8266_RTOS_SDK#48]
I have never seen a firmware update so complicated in over 30 years of doing this type of thing!
wth? Why can't you ppl create a simple 1 file bin to be uploaded to the chip?
I don't want to make file, its ridiculous. One chip, one firmware. Is that too much to ask?
None of this 4 segment bullshit.

**Comment by rojer** [comment]
you may be interested in mOS. OTA is described in [this article](http://www.embedded.com/design/prototyping-and-development/4443082/Updating-firmware-reliably).
it talks about CC3200, but everything applies to esp8266 (and 32) as well.
