### ISSUE TITLE
how to pack the build .bin files to one file ? 怎样打包编译出的固件到一个文件?

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/ESP8266_RTOS_SDK#480]
bootloader.bin
xxx_app.bin
partitions_two_ota.bin

how to pack in one file to flash?
怎样打包编译出的固件到一个文件并直接烧录?

**Comment by 1XiaSheng** [comment]
![qq 20190130135057](https://user-images.githubusercontent.com/37097029/51960976-1e168f00-2496-11e9-97d1-cc88240e8ec9.png)
怎样设置build目录到其他地方? 在编译是怎样使编译build文件夹自动以到其他目录?

**Comment by xiongyumail** [comment]
@1XiaSheng 
windows下的esptool有combine bin的选项。

**Comment by 1XiaSheng** [comment]
> @1XiaSheng
> windows下的esptool有combine bin的选项。

已看到,接下来试一下

**Comment by 1XiaSheng** [comment]
@xiongyumail 
测试ok. 谢谢
