### ISSUE TITLE
最新版本sdk  无法编译

### ISSUE THREAD

**Issue by myzhang001** [espressif/ESP8266_RTOS_SDK#481]
make[1]: Entering directory '/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig'
make[1]: /media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/check-lxdialog.sh: Command not found
cc -c   -DLOCALE -MD  /media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c -o mconf.o
In file included from /media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c:23:0:
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:38:10: error: #include expects "FILENAME" or <FILENAME>
 #include CURSES_LOC
          ^~~~~~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:103:2: error: unknown type name ‘chtype’
  chtype atr; /* Color attribute */
  ^~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:200:16: error: unknown type name ‘WINDOW’
 int on_key_esc(WINDOW *win);
                ^~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:221:17: error: unknown type name ‘WINDOW’
 void attr_clear(WINDOW * win, int height, int width, chtype attr);
                 ^~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:221:54: error: unknown type name ‘chtype’; did you mean ‘idtype_t’?
 void attr_clear(WINDOW * win, int height, int width, chtype attr);
                                                      ^~~~~~
                                                      idtype_t
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:223:21: error: unknown type name ‘WINDOW’
 void print_autowrap(WINDOW * win, const char *prompt, int width, int y, int x);
                     ^~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:224:19: error: unknown type name ‘WINDOW’
 void print_button(WINDOW * win, const char *label, int y, int x, int selected);
                   ^~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:225:18: error: unknown type name ‘WINDOW’
 void print_title(WINDOW *dialog, const char *title, int width);
                  ^~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:226:15: error: unknown type name ‘WINDOW’
 void draw_box(WINDOW * win, int y, int x, int height, int width, chtype box,
               ^~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:226:66: error: unknown type name ‘chtype’; did you mean ‘idtype_t’?
 void draw_box(WINDOW * win, int y, int x, int height, int width, chtype box,
                                                                  ^~~~~~
                                                                  idtype_t
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:227:8: error: unknown type name ‘chtype’; did you mean ‘idtype_t’?
        chtype border);
        ^~~~~~
        idtype_t
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:228:18: error: unknown type name ‘WINDOW’
 void draw_shadow(WINDOW * win, int y, int x, int height, int width);
                  ^~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c: In function ‘conf’:
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:97:29: error: ‘KEY_MAX’ undeclared (first use in this function); did you mean ‘TMP_MAX’?
 #define ERRDISPLAYTOOSMALL (KEY_MAX + 1)
                             ^
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c:671:45: note: in expansion of macro ‘ERRDISPLAYTOOSMALL’
   if (res == 1 || res == KEY_ESC || res == -ERRDISPLAYTOOSMALL)
                                             ^~~~~~~~~~~~~~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:97:29: note: each undeclared identifier is reported only once for each function it appears in
 #define ERRDISPLAYTOOSMALL (KEY_MAX + 1)
                             ^
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c:671:45: note: in expansion of macro ‘ERRDISPLAYTOOSMALL’
   if (res == 1 || res == KEY_ESC || res == -ERRDISPLAYTOOSMALL)
                                             ^~~~~~~~~~~~~~~~~~
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c: In function ‘show_help’:
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c:793:19: warning: implicit declaration of function ‘getmaxx’; did you mean ‘gettext’? [-Wimplicit-function-declaration]
  help.max_width = getmaxx(stdscr) - 10;
                   ^~~~~~~
                   gettext
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c:793:27: error: ‘stdscr’ undeclared (first use in this function); did you mean ‘stderr’?
  help.max_width = getmaxx(stdscr) - 10;
                           ^~~~~~
                           stderr
In file included from /media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c:23:0:
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c: In function ‘conf_choice’:
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/lxdialog/dialog.h:97:29: error: ‘KEY_MAX’ undeclared (first use in this function); did you mean ‘TMP_MAX’?
 #define ERRDISPLAYTOOSMALL (KEY_MAX + 1)
                             ^
/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/mconf.c:855:9: note: in expansion of macro ‘ERRDISPLAYTOOSMALL’
   case -ERRDISPLAYTOOSMALL:
         ^~~~~~~~~~~~~~~~~~
Makefile:171: recipe for target 'mconf.o' failed
make[1]: *** [mconf.o] Error 1
make[1]: Leaving directory '/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig'
make: *** No rule to make target '/media/sf_ubuntu/test/ESP8266_RTOS_SDK/tools/kconfig/conf', needed by '/home/zmy/smart_config/ESP8266_RTOS_SDK/examples/wifi/smart_config/build/include/config/auto.conf'.  Stop.

**Comment by SunXiuF** [comment]
我也遇到了这个问题 请问怎么解决的
