### ISSUE TITLE
uart_enable_swap() blocks indefinitely (GIT8266O-65)

### ISSUE THREAD

**Issue by dreske** [espressif/ESP8266_RTOS_SDK#484]
## Environment

- Development Kit:
- IDF version (``git rev-parse --short HEAD`` to get the commit id.):  a0a9f22
- Development Env:     eclipse
- Operating System:     Arch Linux
- Power Supply:         external 5V

## Problem Description
When I try to use the secondary gpio's for uart0, the swap function never returns. Issue was introduced in d1ab0c20dda8c1f181d61a45e0ee0f587a115d3a (uart.c)

It blocks at line 261:
```
if (pdTRUE == xSemaphoreTake(p_uart_obj[uart_num]->tx_done_sem, (portTickType)portMAX_DELAY)) {
```

**Remark**: sdk is configured to use UART1 for console output.

It is locally solved by adding following line to uart.c (line 898 @ master)
```
xSemaphoreGive(p_uart_obj[uart_num]->tx_done_sem);
```
But I don't know, if this is the correct solution, but it sounds like.

### Expected Behavior
UART0 swaps gpio's

### Actual Behavior
uart_enable_swap() blocks indefinitely. 

### Code to reproduce this issue
https://gist.github.com/dreske/547efb10769032952de4ac65d90c822f

**Comment by xiongyumail** [comment]
Do you have to try to update to the latest SDK?

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue with the latest SDK.
Thanks.
