### ISSUE TITLE
undefined reference to `uxTaskGetSystemState' (GIT8266O-66)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/ESP8266_RTOS_SDK#485]
#include <stdio.h>
	#include <string.h>
	#include <stdlib.h>

	#include "freertos/FreeRTOS.h"
	#include "freertos/task.h"

	void app_main(void)

	   TaskStatus_t *pxTaskStatusArray;
	   volatile UBaseType_t uxArraySize;
	   uint32_t ulTotalRunTime;

	   uxArraySize = uxTaskGetSystemState( pxTaskStatusArray,
	                                 uxArraySize,
	                                 &ulTotalRunTime );

	}

	$ make
	LD build/i2c.elf
	/home/nop/ESP8266_RTOS_SDK/rtos/task-test3/build/main/libmain.a(user_main.o):(.literal.app_main+0x1c): undefined reference to `uxTaskGetSystemState'
	/home/nop/ESP8266_RTOS_SDK/rtos/task-test3/build/main/libmain.a(user_main.o): In function `app_main':
	/home/nop/ESP8266_RTOS_SDK/rtos/task-test3/main/user_main.c:47: undefined reference to `uxTaskGetSystemState'
	collect2: error: ld returned 1 exit status
	/home/nop/ESP8266_RTOS_SDK/make/project.mk:405: recipe for target '/home/nop/ESP8266_RTOS_SDK/rtos/task-test3/build/i2c.elf' failed
	make: *** [/home/nop/ESP8266_RTOS_SDK/rtos/task-test3/build/i2c.elf] Error 1

I changed components/freertos/port/esp8266/include/freertos/FreeRTOSConfig.h.

//#define configUSE_TRACE_FACILITY      0
#define configUSE_TRACE_FACILITY        1

It resolve.

**Comment by donghengqaz** [comment]
Set ”#define configUSE_TRACE_FACILITY	0“  to be  "#define configUSE_TRACE_FACILITY	1" in file FreeRTOSConfig.h.

**Comment by 27-301** [comment]
@donghengqaz Please add a menuconfig to configure trace facility.

**Comment by nopnop2002** [comment]
Do you have a plan to include in menuconfig that trace facility becomes effective or not??

**Comment by nopnop2002** [comment]
I confirmed that configUSE_TRACE_FACILITY can become effectively using menuconfig.
Please close this issue.
