### ISSUE TITLE
fatal: bad revision 'HEAD'

### ISSUE THREAD

**Issue by DCSA35** [espressif/ESP8266_RTOS_SDK#491]
Hello,

working with RTOS SDK 2.0 on an ESP8266
on 'make' I got always
fatal: bad revision 'HEAD'
In fact it is not fatal, everything works fine.
What is the meaning?
Thank you.

**Comment by donghengqaz** [comment]
If you develop with V2.x.x ESP8266 SDK, you may use "gen_misc.sh" under the root directory to build the project instead of command "make".

**Comment by FayeY** [comment]
It is suggested to use our latest [ESP8266 RTOS SDK](https://github.com/espressif/ESP8266_RTOS_SDK/releases). Thanks.

**Comment by DCSA35** [comment]
Dear FayeY,

 

thank you for help.

So far I did not find exact reason, maybe it is a PATH problem,

because I use ESP8266 and ESP32 in parallel.

Anyway it is no real problem.

 

Best wishes

 

 

Gesendet: Dienstag, 12. März 2019 um 03:42 Uhr
Von: "FayeY" <notifications@github.com>
An: espressif/ESP8266_RTOS_SDK <ESP8266_RTOS_SDK@noreply.github.com>
Cc: DCSA35 <ghoem@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [espressif/ESP8266_RTOS_SDK] fatal: bad revision 'HEAD' (#491)


Closed #491.

**Comment by FayeY** [comment]
With V2.x.x ESP8266 RTOS SDK, the command for compilation is "gen_misc.sh".

It is suggested to use the latest V3.x ESP8266 RTOS SDK which is the same as the ESP32-IDF, you can compile it with the command "make".

Please feel free to reopen the issue, if your problem is still unsolved.

Thanks.
