### ISSUE TITLE
Unable to call to function vTaskList 

### ISSUE THREAD

**Issue by zinahe** [espressif/ESP8266_RTOS_SDK#495]
In trying to generate a run-time stat about running tasks, I tried to call **vTaskList** but it fails with the following error message:

undefined reference to `vTaskList'
collect2: error: ld returned 1 exit status

Based on a recommendation found in ESP32 forums I did try to enable it's use in **components/freertos/include/freertos/FreeRTOS.h** by setting 
configUSE_TRACE_FACILITY and configUSE_STATS_FORMATTING_FUNCTIONS as follows

#ifndef configUSE_STATS_FORMATTING_FUNCTIONS                  
    #define configUSE_STATS_FORMATTING_FUNCTIONS 1            
#endif                                                        
                                                              
#ifndef configUSE_TRACE_FACILITY                              
    #define configUSE_TRACE_FACILITY 1                        
#endif    

A similar issue can be found [here](https://github.com/espressif/arduino-esp32/issues/1350)

**Comment by donghengqaz** [comment]
"configUSE_TRACE_FACILITY", "configUSE_STATS_FORMATTING_FUNCTIONS" and "configSUPPORT_DYNAMIC_ALLOCATION" should be set to be "1" at "FreeRTOSConfig.h".

**Comment by joaorsbarbosa** [comment]
I'm still unable to call vTaskList even with @donghengqaz  solution. Those values are already set to 1 on my system

**Comment by donghengqaz** [comment]
Using SDK of release/v3.1 or newer version, you can only enable at "make menuconfig":
```
Component config
    ---> FreeRTOS
          ---> Enable FreeRTOS trace facility
              ---> Enable FreeRTOS stats formatting function
```
