### ISSUE TITLE
call_user_start placed into irom instead of iram (Crash)

### ISSUE THREAD

**Issue by r44083** [espressif/ESP8266_RTOS_SDK#499]
## Environment
- Development Kit: ESP8266 dev board
- IDF version: ESP8266_RTOS_SDK v3.1
- Development Env: Make
- Operating System: Windows 10
- Power Supply: USB

I have noticed that entry function is placed to irom instead of iram.

My app is crashed because ESP8266 can't load ```call_user_start``` from irom on boot.
I don't use 2nd bootloader, so my app starts from 0x40200000: ```irom0_0_seg  :    org = 0x40200000, len = 2M```

Here is boot log:
```
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 20480, room 16 
tail 0
chksum 0x2b
load 0x3ffe8000, len 1340, room 8 
tail 4
chksum 0x1c
load 0x3ffe853c, len 216, room 4 
tail 4
chksum 0x9d
csum 0x9d
Fatal exception (0): 
epc1=0x40218780, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
Fatal exception (0): 
epc1=0x40218780, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
Fatal exception (0): 
epc1=0x40218780, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
```
0x40218780 is ```call_user_start``` according to map file:
```
 .text.call_user_start
                0x40218768       0xfb out/obj/src/hal/ESP8266/ESP8266_RTOS_SDK/components\esp8266\source\startup.o
                                0x113 (size before relaxing)
                0x40218780                call_user_start
 *fill*         0x40218863        0x1 
```

If I add ```IRAM_ATTR``` to the ```call_user_start```, it successfully executed, ``chip_boot``` is executed too, I get the following boot log (but app doesn't work anyway):
```
 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x40100000, len 20752, room 16 
tail 0
chksum 0x0f
load 0x3ffe8000, len 1340, room 8 
tail 4
chksum 0x35
load 0x3ffe853c, len 216, room 4 
tail 4
chksum 0xb4
csum 0xb4
```
0x40100304 is ```call_user_start``` according to map file:
```
 .iram1         0x401002d4      0x113 out/obj/src/hal/ESP8266/ESP8266_RTOS_SDK/components\esp8266\source\startup.o
                0x40100304                call_user_start
 *fill*         0x401003e7        0x1 
```

Here is elf, map and bin files:
[omef-esp8266.zip](https://github.com/espressif/ESP8266_RTOS_SDK/files/2913860/omef-esp8266.zip)

P.S: ```CONFIG_BOOTLOADER_INIT_SPI_FLASH``` is not defined to let the app init SPI flash itself

**Why ```call_user_start``` is placed to the irom?**
**What could be the problem to start app properly?**

**Comment by donghengqaz** [comment]
call_user_start shoud unpacks the IRAM functions. So if you link call_user_start to IRAM, no one can unpack the IRAM function.

**Comment by r44083** [comment]
But you can not call funtions from irom before SPI Flash initialization.
My app starts from call_user_star() which placed to irom. How can you call call_user_star() on boot from SPI Flash?

**Comment by donghengqaz** [comment]
Bootloader will initialize the SPI flash before jumping to user APP.

**Comment by r44083** [comment]
User app has the following config in menuconfig:
```CONFIG_BOOTLOADER_INIT_SPI_FLASH```
I set it to 0. So App should init SPI flash itself.

**Comment by r44083** [comment]
Fix is:
1. Call ```Cache_Read_Enable(0, 0, 0);``` at the beginning of call_user_start()
2. Move call_user_start() to iram by adding ```__attribute__((section(".iram1")))``` to ```call_user_start()```
