### ISSUE TITLE
mqtt sub 如果收到Qos不匹配的消息会造成 sub线程挂掉，就再也无法接受到新消息，只有重启才可以 (GIT8266O-80)

### ISSUE THREAD

**Issue by grays820** [espressif/ESP8266_RTOS_SDK#503]
如果板子我设置Qos 为1
用MQTT.fx 发送Qos0的测试消息无问题，如果我发送其他的消息，接受线程会挂掉，必须重启板子才行，log报错如下
[0;32mI (2087) AnyLib: Message arrived[len:4]: 1234[0m
[0;33mW (2097) mc: mqtt close session[0m
[0;31mE (2097) mc: MQTTRun cycle failed[0m

**Comment by panguoxian** [comment]
我的也一样，有同样的问题，解决了吗？

**Comment by ustccw** [comment]
@grays820 @panguoxian 可否具体描述一下你的环境呢?

**Comment by xuhongv** [comment]
- @panguoxian  @grays820 来试下这个框架 ： https://github.com/xuhongv/xMqttEsp8266Rtos3.0Lib

**Comment by FayeY** [comment]
想请问，这个问题有什么进展吗？是否已经解决了？

**Comment by FayeY** [comment]
由于长时间无更新，此问题暂时关闭。如有需要，欢迎 reopen 重新开启讨论。
