### ISSUE TITLE
系统开机异常register map is 3ffffe8c error－有没有人遇到 (GIT8266O-134)

### ISSUE THREAD

**Issue by invention88** [espressif/ESP8266_RTOS_SDK#509]
2nd stage bootloader[0m
[0;32mI (193) boot: compile time 16:12:54[0m
[0;32mI (194) boot: SPI Speed      : 40MHz[0m
[0;32mI (198) boot: SPI Mode       : QIO[0m
[0;32mI (202) boot: SPI Flash Size : 2MB[0m
[0;32mI (206) boot: Partition Table:[0m
[0;32mI (210) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (217) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (225) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (232) boot:  2 factory          factory app      00 00 00010000 000f0000[0m
[0;32mI (240) boot: End of partition table[0m
[0;32mI (244) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x3e018 (253976) map[0m
[0;32mI (408) esp_image: segment 1: paddr=0x0004e030 vaddr=0x3ffe8000 size=0x0053c (  1340) load[0m
[0;32mI (410) esp_image: segment 2: paddr=0x0004e574 vaddr=0x3ffe853c size=0x0011c (   284) load[0m
[0;32mI (416) esp_image: segment 3: paddr=0x0004e698 vaddr=0x40100000 size=0x066f0 ( 26352) load[0m
[0;32mI (440) boot: Loaded app from partition at offset 0x10000[0m

Core 0 was running in ISR context:

register map is 3ffffe8c error

有没有人遇到这类系统开机异常的情况？

本来一直都很正常，在代码加几条语句，编译后再升级，就成这样了。有时候去掉新加的就可以下运行了。（实际上代码都没跑到修改的地方）

**Comment by donghengqaz** [comment]
哪个版本，加的什么？

**Comment by invention88** [comment]
/*
   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <string.h>
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"

#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event_loop.h"
#include "esp_log.h"

#include "nvs_flash.h"

#include <netdb.h>
#include <sys/socket.h>



/* The examples use simple WiFi configuration that you can set via
   'make menuconfig'.

   If you'd rather not, just change the below entries to strings with
   the config you want - ie #define EXAMPLE_WIFI_SSID "mywifissid"
*/
#define EXAMPLE_WIFI_SSID CONFIG_WIFI_SSID
#define EXAMPLE_WIFI_PASS CONFIG_WIFI_PASSWORD

/* FreeRTOS event group to signal when we are connected & ready to make a request */
static EventGroupHandle_t wifi_event_group;

/* The event group allows multiple bits for each event,
   but we only care about one event - are we connected
   to the AP with an IP? */
static const int CONNECTED_BIT = BIT0;


static const char *TAG = "IOT";

/*
static const char *REQUESTDATE = "GET " "http://www.beijing-time.org/time.asp" " HTTP/1.1\r\n"
	"Host: beijing-time.org\r\n"
	"User-Agent: esp-idf/1.0 esp32\r\n"
	"\r\n";
*/
static esp_err_t event_handler(void *ctx, system_event_t *event)
{
    switch(event->event_id) {
    case SYSTEM_EVENT_STA_START:
        esp_wifi_connect();
        break;
    case SYSTEM_EVENT_STA_GOT_IP:
        xEventGroupSetBits(wifi_event_group, CONNECTED_BIT);
        break;
    case SYSTEM_EVENT_STA_DISCONNECTED:
        /* This is a workaround as ESP32 WiFi libs don't currently
           auto-reassociate. */
        esp_wifi_connect();
        xEventGroupClearBits(wifi_event_group, CONNECTED_BIT);
        break;
    default:
        break;
    }
    return ESP_OK;
}

static void initialise_wifi(void)
{
    tcpip_adapter_init();
    wifi_event_group = xEventGroupCreate();
    ESP_ERROR_CHECK( esp_event_loop_init(event_handler, NULL) );
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK( esp_wifi_init(&cfg) );
    ESP_ERROR_CHECK( esp_wifi_set_storage(WIFI_STORAGE_RAM) );
    wifi_config_t wifi_config = {
        .sta = {
            .ssid = EXAMPLE_WIFI_SSID,
            .password = EXAMPLE_WIFI_PASS,
        },
    };
    ESP_LOGI(TAG, "Setting WiFi configuration SSID %s...", wifi_config.sta.ssid);
    ESP_ERROR_CHECK( esp_wifi_set_mode(WIFI_MODE_STA) );
    ESP_ERROR_CHECK( esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config) );
    ESP_ERROR_CHECK( esp_wifi_start() );
}
/*
 void GetTime()
{
	const struct addrinfo hints = {
			.ai_family = AF_INET,
			.ai_socktype = SOCK_STREAM,
		};
	struct addrinfo *res;
	struct in_addr *addr;
	int s, r=0;
    char recv_buf[64];
	printf("GetTime\n");
	int err = getaddrinfo("beijing-time.org", "80", &hints, &res);
	if(err != 0 || res == NULL) {
            ESP_LOGE(TAG, "DNS lookup failed err=%d res=%p", err, res);
            vTaskDelay(1000 / portTICK_PERIOD_MS);
        }
	addr = &((struct sockaddr_in *)res->ai_addr)->sin_addr;
	ESP_LOGI(TAG, "DNS lookup succeeded. IP=%s", inet_ntoa(*addr));
	s = socket(res->ai_family, res->ai_socktype, 0);
	if(s < 0) {
		ESP_LOGE(TAG, "... Failed to allocate socket.");
		freeaddrinfo(res);
		vTaskDelay(1000 / portTICK_PERIOD_MS);
	}

	freeaddrinfo(res);
	r = write(s, REQUESTDATE, strlen(REQUESTDATE));
	printf("r:%d\n", r);
	struct timeval receiving_timeout;
        receiving_timeout.tv_sec = 5;
        receiving_timeout.tv_usec = 0;
	r=setsockopt(s, SOL_SOCKET, SO_RCVTIMEO, &receiving_timeout,
                sizeof(receiving_timeout));
	printf("r:%d\n", r);

	r = read(s, recv_buf, sizeof(recv_buf)-1);
	printf("r:%d\n", r);
    for(int i = 0; i < r; i++) {
        putchar(recv_buf[i]);
    }
}
*/
void WaitConnected(void)
{
	/* Wait for the callback to set the CONNECTED_BIT in the
           event group.
        */
	xEventGroupWaitBits(wifi_event_group, CONNECTED_BIT,
                            false, true, portMAX_DELAY);
}

extern void Sensor_ThreadStart(void);
extern void HTTP_ThreadStart(void);
extern void MQTT_ThreadStart(void);
extern void AT_ThreadStart();

int StrToHex(char* str, unsigned int * result)
{
	int iRet = 0;
	unsigned int tmp = 0;
	int len = strlen(str);
	int i = 0;

	if(len <= 2)
	{
		return -1;
	}

	//if((str[0] != '0') || (str[0] != 'x')) 这里用这句能正常开机
	if((str[0] != '0') || (str[1] != 'x'))//这里用这句就会出现上面这种异常
	{
		return -1;
	}

	for(i = 2; i < len; i++)
	{
		tmp <<= 4;
		if((str[i] >= '0') && (str[i] <= '9'))
		{
			tmp |= str[i]-'0';
		}
		else if((str[i] >= 'A') && (str[i] <= 'F'))
		{
			tmp |= str[i]-'A'+10;
		}
		else if((str[i] >= 'a') && (str[i] <= 'f'))
		{
			tmp |= str[i]-'a'+10;
		}
		else
		{
			iRet = -1;
			break;
		}
	}

	if(iRet == 0)
	{
		*result = tmp;
		printf("ToHex:%s->0x%x\n", str, tmp);
	}
	
	return iRet;
}

int StrToDec(char* str, unsigned int * result)
{
	int iRet = 0;
	unsigned int tmp = 0;
	int len = strlen(str);
	int i = 0;

	for(i = 0; i < len; i++)
	{
		if((str[i] >= '0') && (str[i] <= '9'))
		{
			tmp *= 10;
			tmp += str[i]-'0';
		}
		else
		{
			iRet = -1;
			break;
		}
	}
	
	if(iRet == 0)
	{
		*result = tmp;
		printf("ToDec:%s->%d\n", str, tmp);
	}
	
	return iRet;
}


/*
	p1/p2
*/
void GetStrDivision(unsigned int p1, unsigned int p2, char bits, char* buf, char buf_len)
{
	unsigned int idx = 0;
	unsigned int result = 0;
	unsigned int tmpP1 = 0;

	memset(buf, 0, buf_len);

	if(p2 == 0)
	{
		printf("parameter p2(%d) error.\n", p2);
		return;
	}

	result = p1/p2;
	sprintf(buf, "%d", result);
	
	tmpP1 = p1%p2;

	if(tmpP1 == 0)
	{
		printf("RESULE: %d/%d=%s\n", p1, p2, buf);
		return;
	}
	
	idx = strlen(buf);
	
	sprintf(buf+idx++, ".");

	result = 0;

	if(bits > (buf_len-idx))
	{
		bits = buf_len - idx - 1;
	}
	
	while(tmpP1)
	{
		tmpP1 *= 10;
		result = tmpP1/p2;

		if(result > 0)
		{
			tmpP1 = tmpP1%p2;
		}
		
		bits--;
		
		if(bits == 0)
		{
			if((tmpP1%p2) > (p2>>1))
			{
				if(result < 9)
				{	
					result++;
				}
			}
			sprintf(buf+idx++, "%d", result);
			break;
		}
		
		sprintf(buf+idx++, "%d", result);
	}


	printf("RESULE: %d/%d=%s\n", p1, p2, buf);
}

void TestFunc(void)
{
	char str[30];
	GetStrDivision(1, 12345, 10, str, 30);
	GetStrDivision(1, 3, 4, str, 30);
	GetStrDivision(1, 6, 10, str, 30);
	GetStrDivision(444, 222, 10, str, 30);
	GetStrDivision(440, 22, 10, str, 30);
	GetStrDivision(123, 6, 10, str, 30);
	GetStrDivision(123, 66, 10, str, 30);
	GetStrDivision(555, 76, 10, str, 30);
	GetStrDivision(555, 7676, 10, str, 30);
	

	unsigned int result = 0;
	StrToDec("1234", &result);
	StrToDec("123400", &result);
	StrToDec("0123400", &result);
	StrToHex("0x1234", &result);
	StrToHex("0x123400", &result);
	StrToHex("0x0123400", &result);
}

/******************************************************************************
 * FunctionName : app_main
 * Description  : entry of user application, init user function here
 * Parameters   : none
 * Returns      : none
*******************************************************************************/
void app_main(void)
{
    printf("SDK version:%s\n", esp_get_idf_version());
	
	ESP_ERROR_CHECK( nvs_flash_init() );
	
    initialise_wifi();

	TestFunc();
	
	
    //HTTP_ThreadStart();

	#if (CONFIG_CONSOLE_UART_NUM == 0)
	//Sensor_ThreadStart();
	#endif
	
	//MQTT_ThreadStart();

	//AT_ThreadStart();

}

**Comment by invention88** [comment]
用的master版本d847d847e
上面的异常地方是StrToHex函数注释的地方，非常奇怪。
经常会时不时的遇到类似这样的问题，重新整理调整一下函数就好了，如果GetStrDivision函数的调用地方全部删掉，也能正常开机。
感觉像是系统资源问题，但是这些函数需要的资源又是非常小。

**Comment by invention88** [comment]
补充一下编译配置文件内容：
#
# Automatically generated file; DO NOT EDIT.
# Espressif IoT Development Framework Configuration
#
CONFIG_IDF_TARGET_ESP32=
CONFIG_IDF_TARGET_ESP8266=y

#
# SDK tool configuration
#
CONFIG_TOOLPREFIX="xtensa-lx106-elf-"
CONFIG_PYTHON="python"
CONFIG_MAKE_WARN_UNDEFINED_VARIABLES=y

#
# Bootloader config
#
CONFIG_BOOTLOADER_INIT_SPI_FLASH=
CONFIG_LOG_BOOTLOADER_LEVEL_NONE=
CONFIG_LOG_BOOTLOADER_LEVEL_ERROR=
CONFIG_LOG_BOOTLOADER_LEVEL_WARN=
CONFIG_LOG_BOOTLOADER_LEVEL_INFO=y
CONFIG_LOG_BOOTLOADER_LEVEL_DEBUG=
CONFIG_LOG_BOOTLOADER_LEVEL_VERBOSE=
CONFIG_LOG_BOOTLOADER_LEVEL=3
CONFIG_BOOTLOADER_CHECK_APP_SUM=y
CONFIG_BOOTLOADER_CHECK_APP_HASH=
CONFIG_BOOTLOADER_APP_TEST=

#
# Serial flasher config
#
CONFIG_ESPTOOLPY_PORT="/dev/ttyUSB0"
CONFIG_ESPTOOLPY_BAUD_115200B=y
CONFIG_ESPTOOLPY_BAUD_230400B=
CONFIG_ESPTOOLPY_BAUD_921600B=
CONFIG_ESPTOOLPY_BAUD_2MB=
CONFIG_ESPTOOLPY_BAUD_OTHER=
CONFIG_ESPTOOLPY_BAUD_OTHER_VAL=115200
CONFIG_ESPTOOLPY_BAUD=115200
CONFIG_ESPTOOLPY_COMPRESSED=y
CONFIG_FLASHMODE_QIO=y
CONFIG_FLASHMODE_QOUT=
CONFIG_FLASHMODE_DIO=
CONFIG_FLASHMODE_DOUT=
CONFIG_ESPTOOLPY_FLASHMODE="dio"
CONFIG_SPI_FLASH_MODE=0x0
CONFIG_ESPTOOLPY_FLASHFREQ_80M=
CONFIG_ESPTOOLPY_FLASHFREQ_40M=y
CONFIG_ESPTOOLPY_FLASHFREQ_26M=
CONFIG_ESPTOOLPY_FLASHFREQ_20M=
CONFIG_ESPTOOLPY_FLASHFREQ="40m"
CONFIG_SPI_FLASH_FREQ=0x0
CONFIG_ESPTOOLPY_FLASHSIZE_1MB=
CONFIG_ESPTOOLPY_FLASHSIZE_2MB=y
CONFIG_ESPTOOLPY_FLASHSIZE_4MB=
CONFIG_ESPTOOLPY_FLASHSIZE_8MB=
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=
CONFIG_ESPTOOLPY_FLASHSIZE="2MB"
CONFIG_SPI_FLASH_SIZE=0x200000
CONFIG_ESPTOOLPY_BEFORE_RESET=y
CONFIG_ESPTOOLPY_BEFORE_NORESET=
CONFIG_ESPTOOLPY_BEFORE="default_reset"
CONFIG_ESPTOOLPY_AFTER_RESET=y
CONFIG_ESPTOOLPY_AFTER_NORESET=
CONFIG_ESPTOOLPY_AFTER="hard_reset"
CONFIG_MONITOR_BAUD_9600B=
CONFIG_MONITOR_BAUD_57600B=
CONFIG_MONITOR_BAUD_74880B=y
CONFIG_MONITOR_BAUD_115200B=
CONFIG_MONITOR_BAUD_230400B=
CONFIG_MONITOR_BAUD_921600B=
CONFIG_MONITOR_BAUD_2MB=
CONFIG_MONITOR_BAUD_OTHER=
CONFIG_MONITOR_BAUD_OTHER_VAL=74880
CONFIG_MONITOR_BAUD=74880
CONFIG_ESPTOOLPY_ENABLE_TIME=
CONFIG_ESPTOOLPY_ENABLE_SAVELOG=

#
# Example Configuration
#
CONFIG_WIFI_SSID="newifi_AA2C"
CONFIG_WIFI_PASSWORD="12345687"
CONFIG_MQTT_BROKER="192.168.1.209"
CONFIG_MQTT_PORT=8086
CONFIG_MQTT_SUB_TOPIC="/espressif/sub"
CONFIG_SUB_QOS0=
CONFIG_SUB_QOS1=
CONFIG_SUB_QOS2=y
CONFIG_DEFAULT_MQTT_SUB_QOS=2
CONFIG_MQTT_PUB_TOPIC="/espressif/pub"
CONFIG_PUB_QOS0=
CONFIG_PUB_QOS1=
CONFIG_PUB_QOS2=y
CONFIG_DEFAULT_MQTT_PUB_QOS=2
CONFIG_MQTT_PUBLISH_INTERVAL=1000
CONFIG_MQTT_PAYLOAD_BUFFER=1460

#
# Partition Table
#
CONFIG_PARTITION_TABLE_SINGLE_APP=y
CONFIG_PARTITION_TABLE_TWO_OTA=
CONFIG_PARTITION_TABLE_CUSTOM=
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"
CONFIG_PARTITION_TABLE_OFFSET=0x8000
CONFIG_PARTITION_TABLE_FILENAME="partitions_singleapp.csv"

#
# Compiler options
#
CONFIG_OPTIMIZATION_LEVEL_DEBUG=y
CONFIG_OPTIMIZATION_LEVEL_RELEASE=
CONFIG_OPTIMIZATION_ASSERTIONS_ENABLED=y
CONFIG_OPTIMIZATION_ASSERTIONS_SILENT=
CONFIG_OPTIMIZATION_ASSERTIONS_DISABLED=
CONFIG_CXX_EXCEPTIONS=
CONFIG_STACK_CHECK_NONE=y
CONFIG_STACK_CHECK_NORM=
CONFIG_STACK_CHECK_STRONG=
CONFIG_STACK_CHECK_ALL=
CONFIG_STACK_CHECK=

#
# Component config
#

#
# App update
#
CONFIG_APP_UPDATE_CHECK_APP_SUM=y
CONFIG_APP_UPDATE_CHECK_APP_HASH=
CONFIG_AWS_IOT_SDK=

#
# ESP8266-specific
#
CONFIG_ESP8266_DEFAULT_CPU_FREQ_80=y
CONFIG_ESP8266_DEFAULT_CPU_FREQ_160=
CONFIG_ESP8266_DEFAULT_CPU_FREQ_MHZ=80
CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF=y
CONFIG_NEWLIB_STDOUT_LINE_ENDING_LF=
CONFIG_NEWLIB_STDOUT_LINE_ENDING_CR=
CONFIG_ESP_FILENAME_MACRO_NO_PATH=y
CONFIG_ESP_FILENAME_MACRO_RAW=
CONFIG_ESP_FILENAME_MACRO_NULL=
CONFIG_USING_NEW_ETS_VPRINTF=y
CONFIG_LINK_ETS_PRINTF_TO_IRAM=
CONFIG_SOC_FULL_ICACHE=
CONFIG_SOC_IRAM_SIZE=0xC000
CONFIG_CONSOLE_UART_DEFAULT=
CONFIG_CONSOLE_UART_CUSTOM=y
CONFIG_CONSOLE_UART_NONE=
CONFIG_CONSOLE_UART_CUSTOM_NUM_0=
CONFIG_CONSOLE_UART_CUSTOM_NUM_1=y
CONFIG_CONSOLE_UART_NUM=1
CONFIG_CONSOLE_UART_BAUDRATE=115200
CONFIG_UART0_SWAP_IO=
CONFIG_DISABLE_ROM_UART_PRINT=
CONFIG_MAIN_TASK_STACK_SIZE=3584
CONFIG_TASK_WDT=y
CONFIG_TASK_WDT_PANIC=y
CONFIG_TASK_WDT_TIMEOUT_13N=
CONFIG_TASK_WDT_TIMEOUT_14N=
CONFIG_TASK_WDT_TIMEOUT_15N=y
CONFIG_TASK_WDT_TIMEOUT_S=15
CONFIG_RESET_REASON=y
CONFIG_WIFI_PPT_TASKSTACK_SIZE=2048
CONFIG_EVENT_LOOP_STACK_SIZE=2048
CONFIG_ESP8266_CORE_GLOBAL_DATA_LINK_IRAM=y
CONFIG_CRYSTAL_USED_26MHZ=y
CONFIG_CRYSTAL_USED_40MHZ=
CONFIG_ESP8266_OTA_FROM_OLD=
CONFIG_ESP8266_BOOT_COPY_APP=

#
# WIFI
#
CONFIG_SCAN_AP_MAX=32
CONFIG_WIFI_TX_RATE_SEQUENCE_FROM_HIGH=y

#
# PHY
#
CONFIG_ESP_PHY_CALIBRATION_AND_DATA_STORAGE=y
CONFIG_ESP_PHY_INIT_DATA_IN_PARTITION=

#
# ESP HTTP client
#
CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS=y

#
# HTTP Server
#
CONFIG_HTTPD_MAX_REQ_HDR_LEN=512
CONFIG_HTTPD_MAX_URI_LEN=512

#
# FreeRTOS
#
CONFIG_DISABLE_FREERTOS=
CONFIG_FREERTOS_ENABLE_REENT=
CONFIG_FREERTOS_HZ=100
CONFIG_FREERTOS_MAX_HOOK=2
CONFIG_FREERTOS_ISR_STACKSIZE=512
CONFIG_FREERTOS_GLOBAL_DATA_LINK_IRAM=y
CONFIG_FREERTOS_TIMER_STACKSIZE=2048
CONFIG_TASK_SWITCH_FASTER=y
CONFIG_USE_QUEUE_SETS=
CONFIG_ENABLE_FREERTOS_SLEEP=
CONFIG_FREERTOS_USE_TRACE_FACILITY=
CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=

#
# libsodium
#
CONFIG_LIBSODIUM_USE_MBEDTLS_SHA=y

#
# Log output
#
CONFIG_LOG_DEFAULT_LEVEL_NONE=
CONFIG_LOG_DEFAULT_LEVEL_ERROR=
CONFIG_LOG_DEFAULT_LEVEL_WARN=
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
CONFIG_LOG_DEFAULT_LEVEL_DEBUG=
CONFIG_LOG_DEFAULT_LEVEL_VERBOSE=
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_COLORS=y
CONFIG_LOG_SET_LEVEL=

#
# LWIP
#
CONFIG_LWIP_USE_IRAM=
CONFIG_LWIP_HIGH_THROUGHPUT=
CONFIG_LWIP_GLOBAL_DATA_LINK_IRAM=y
CONFIG_TCPIP_RECVMBOX_SIZE=32

#
# ARP
#
CONFIG_LWIP_ARP_TABLE_SIZE=10
CONFIG_LWIP_ARP_MAXAGE=300

#
# SOCKET
#
CONFIG_LWIP_SOCKET_MULTITHREAD=y
CONFIG_ENABLE_NONBLOCK_SPEEDUP=
CONFIG_SET_SOLINGER_DEFAULT=y
CONFIG_ESP_UDP_SYNC_SEND=y
CONFIG_ESP_UDP_SYNC_RETRY_MAX=5
CONFIG_LWIP_MAX_SOCKETS=10
CONFIG_LWIP_SO_REUSE=y
CONFIG_LWIP_SO_REUSE_RXTOALL=y
CONFIG_LWIP_SO_RCVBUF=
CONFIG_LWIP_RECV_BUFSIZE_DEFAULT=11680
CONFIG_LWIP_TCP_CLOSE_TIMEOUT_MS_DEFAULT=10000
CONFIG_LWIP_IP_FRAG=
CONFIG_LWIP_IP_REASSEMBLY=
CONFIG_LWIP_IP_REASS_MAX_PBUFS=10
CONFIG_LWIP_IP_SOF_BROADCAST=
CONFIG_LWIP_IP_SOF_BROADCAST_RECV=
CONFIG_LWIP_ICMP=y
CONFIG_LWIP_MULTICAST_PING=
CONFIG_LWIP_BROADCAST_PING=
CONFIG_LWIP_RAW=

#
# DHCP
#
CONFIG_LWIP_DHCP_DOES_ARP_CHECK=y
CONFIG_LWIP_DHCP_MAX_NTP_SERVERS=1
CONFIG_LWIP_DHCPS_LEASE_UNIT=60
CONFIG_LWIP_DHCPS_MAX_STATION_NUM=8
CONFIG_LWIP_AUTOIP=
CONFIG_LWIP_IGMP=y
CONFIG_DNS_MAX_SERVERS=2
CONFIG_LWIP_NETIF_LOOPBACK=

#
# TCP
#
CONFIG_TCP_HIGH_SPEED_RETRANSMISSION=
CONFIG_LWIP_MAX_ACTIVE_TCP=5
CONFIG_LWIP_MAX_LISTENING_TCP=8
CONFIG_TCP_MAXRTX=12
CONFIG_TCP_SYNMAXRTX=6
CONFIG_TCP_MSS=1460
CONFIG_TCP_SND_BUF_DEFAULT=2920
CONFIG_TCP_WND_DEFAULT=5840
CONFIG_TCP_RECVMBOX_SIZE=6
CONFIG_TCP_QUEUE_OOSEQ=
CONFIG_TCP_OVERSIZE_MSS=y
CONFIG_TCP_OVERSIZE_QUARTER_MSS=
CONFIG_TCP_OVERSIZE_DISABLE=
CONFIG_LWIP_TCP_TIMESTAMPS=

#
# UDP
#
CONFIG_LWIP_MAX_UDP_PCBS=4
CONFIG_UDP_RECVMBOX_SIZE=6
CONFIG_TCPIP_TASK_STACK_SIZE=2048

#
# LWIP RAW API
#
CONFIG_LWIP_MAX_RAW_PCBS=4
CONFIG_LWIP_IPV6=
CONFIG_LWIP_STATS=
CONFIG_ESP_LWIP_MEM_DBG=
CONFIG_LWIP_DEBUG=

#
# mDNS
#
CONFIG_ENABLE_MDNS=

#
# MQTT(Paho)
#
CONFIG_V3_1=y
CONFIG_V3_1_1=
CONFIG_DEFAULT_MQTT_VERSION=3
CONFIG_MQTT_CLIENT_ID="client001"
CONFIG_MQTT_KEEP_ALIVE=30
CONFIG_MQTT_USERNAME="username001"
CONFIG_MQTT_PASSWORD="psw001"
CONFIG_CLEAN_SESSION=y
CONFIG_KEEP_SESSION=
CONFIG_DEFAULT_MQTT_SESSION=1
CONFIG_NO_TLS=y
CONFIG_TLS_VERIFY_NONE=
CONFIG_TLS_VERIFY_PEER=
CONFIG_TLS_VERIFY_CLIENT=
CONFIG_DEFAULT_MQTT_SECURITY=0
CONFIG_MQTT_SEND_BUFFER=2048
CONFIG_MQTT_RECV_BUFFER=2048
CONFIG_MQTT_SEND_CYCLE=30000
CONFIG_MQTT_RECV_CYCLE=0
CONFIG_MQTT_PING_TIMEOUT=3000

#
# Newlib
#
CONFIG_NEWLIB_ENABLE=y
CONFIG_NEWLIB_LIBRARY_LEVEL_NORMAL=
CONFIG_NEWLIB_LIBRARY_LEVEL_NANO=y

#
# PThreads
#
CONFIG_ENABLE_PTHREAD=
CONFIG_ESP32_PTHREAD_TASK_PRIO_DEFAULT=5
CONFIG_ESP32_PTHREAD_TASK_STACK_SIZE_DEFAULT=3072

#
# SSL
#
CONFIG_SSL_USING_MBEDTLS=
CONFIG_SSL_USING_AXTLS=
CONFIG_SSL_USING_WOLFSSL=y

#
# wolfSSL
#
CONFIG_WOLFSSL_DEBUG=

#
# tcpip adapter
#
CONFIG_IP_LOST_TIMER_INTERVAL=120
CONFIG_TCPIP_ADAPTER_GLOBAL_DATA_LINK_IRAM=y

#
# Unified Provisioning
#
CONFIG_ENABLE_UNIFIED_PROVISIONING=

#
# wpa_supplicant
#
CONFIG_LTM_FAST=y

**Comment by donghengqaz** [comment]
这个应该是编译的时候产生的非4字节对齐的数据，在 word 级别的寻址访问的时候产生额问题，现在应该已经修复了。

**Comment by FayeY** [comment]
由于长时间无更新，此问题暂时关闭。如果使用最新版本仍然有问题，欢迎 reopen issue 继续展开讨论。
