### ISSUE TITLE
Memory Leak in zalloc or malloc with concurrent free.

### ISSUE THREAD

**Issue by filzek** [espressif/ESP8266_RTOS_SDK#510]
WROOM-02

Memory Leak in zalloc or malloc with concurrent free.

Memory never return to it back state.

**Comment by donghengqaz** [comment]
You can use heap debug to help find the leak memory in header file "esp_heap_trace.h":

```
esp_err_t heap_trace_start(heap_trace_mode_t mode);

void heap_trace_dump(void);
```
