### ISSUE TITLE
smartconfig 超时退出有什么回调和消息没有? esp_esptouch_set_timeout(254); (GIT8266O-112)

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/ESP8266_RTOS_SDK#513]
```
  esp_esptouch_set_timeout(254);
```
使用上面方法设置超时退出后,有什么回调和消息能够获取吗? 配置超时我需要使用 esp_wifi_deinit();重置网络功能吗?

**Comment by xuhongv** [comment]
- 暂时没回调方法提供

**Comment by FireWinter** [comment]
> @FireWinter 有什么建议吗？

没有回调和消息获取，超时退出会打印：smartconfig restart，此时重新进入配网状态，不需要手动重置网络，内部会进行重置。

**Comment by FayeY** [comment]
请问，这个问题是否得到了解答？

**Comment by 1XiaSheng** [comment]
有回答，但是个人认为配置超时应该有事件
