### ISSUE TITLE
RTOS_SDK 3.1 如何访问 RTC memory ？system_rtc_mem_read()

### ISSUE THREAD

**Issue by huozhe0930** [espressif/ESP8266_RTOS_SDK#518]
想在深度睡眠状态利用 rtc memory保持一些数据，但是在RTOS_SDK 3.1中，找不到访问rtc memory的API， system_rtc_mem_read()这个API已经没了。

**Comment by huozhe0930** [comment]
读esp32的api文档，RTC_DATA_ATTR--这个宏定义在esp8266z中也是有效的。就是这么用的吗？如果定义的数据超过了rtc memory的最大允许范围，会有编译告警吗？应用程序可用rtc memory的大小仍然是512字节吗？

**Comment by donghengqaz** [comment]
可以使用 RTC_DATA_ATTR，超过的数据超过范围的话，链接的时候会报错，原则上是 512 字节。

**Comment by huozhe0930** [comment]
多谢
