### ISSUE TITLE
USER_DATA_ATTR  特点？（按代码注释，指定数据存放在0x10开始的地址）；RAM or Flash？NVS？

### ISSUE THREAD

**Issue by huozhe0930** [espressif/ESP8266_RTOS_SDK#521]
----------------------------- Delete below -----------------------------
有更详细的使用说明吗？

**Comment by donghengqaz** [comment]
放在 flash，可以保证这个数据段放在用户代码之前。

**Comment by huozhe0930** [comment]
谢谢。

**Comment by 27-301** [comment]
比如你可以放一些特殊的字符串，那这个字符串就在 flash 的特定位置，你可以拿来作某些校验功能用。

先 close，有其他问题再提出，谢谢～
