### ISSUE TITLE
RTOS-SDK3.1 怎么读 RTC counter的值，怎么知道RTC counter 每增加一个计数，代表多长时间？

### ISSUE THREAD

**Issue by huozhe0930** [espressif/ESP8266_RTOS_SDK#524]
看不到任何关于 RTC counter的说明！

**Comment by 27-301** [comment]
你是需要之前版本 RTOS or NonOS SDK rtc 的哪个接口功能来着？

**Comment by huozhe0930** [comment]
我想用rtc来计时，这样就不用频繁去网络同步时间。（电池供电，频繁访问网络，太耗电了）。

之前的SDK有system_rtc_get_time()这样的接口，但是SDK3.1找不到这样的API可用。

**Comment by 27-301** [comment]
了解，我们会列入计划。

这个 rtc 不会太准确。现在你可以先用 sntp 去获取时间，然后直接用 time 接口就可以了。

**Comment by huozhe0930** [comment]
多谢指导，明白了。
