### ISSUE TITLE
MQTT使用MQTTClient  阻塞触发watchdog BUG

### ISSUE THREAD

**Issue by panguoxian** [espressif/ESP8266_RTOS_SDK#530]
前提：目前有项目需求使用MQTT，如果Subscribe和publish的Topic不对，服务器会断开连接。

当我使用MQTTClient.h 里的：MQTTPublish()和MQTTSubscribe()函数 。当主题不是预定的主题函数会阻塞也不会返回，最后触发watchdog 重启。

假设服务器预定Topic为“123”，当publish的主题为“1234”时会阻塞。

不知各位有什么解决办法吗？

**Comment by ustccw** [comment]
@panguoxian 你可以试着把 `QoS1` 改为 `QoS0`, 这和服务器的行为有关.

我们官方通常用 mosquitto 作为 mqtt broker, 测试没有此问题的.
