### ISSUE TITLE
subscribe 用 qos1 收到服务器qos1消息会mqtt close session

### ISSUE THREAD

**Issue by panguoxian** [espressif/ESP8266_RTOS_SDK#533]
使用例程ibm_mqtt例程。
1、subscribe 用 qos1 收到服务器qos1 发布 消息会发生

mqtt close session
MQTTRun cycle failed

2、subscribe 用 qos 0 收到服务器qos1发面的消息不会发生上面的问题。

**Comment by ustccw** [comment]
@panguoxian `ibm_mqtt` 是什么例程?
可以跑一下我们官方例程: https://github.com/espressif/ESP8266_RTOS_SDK/tree/release/v3.1/examples/protocols/mqtt

里面默认配置就是 `QoS1`
