### ISSUE TITLE
sdk3.1如何获取chipID (GIT8266O-83)

### ISSUE THREAD

**Issue by match0131** [espressif/ESP8266_RTOS_SDK#542]
sdk 2.x.x中一直使用system_get_chip_id()获取chipID，3.1SDK中是否完全取消了类似接口？

**Comment by donghengqaz** [comment]
这个接口本质上是通过获取 MAC 地址的 [3, 5] 字节（总共 [0, 5]）来生成 Chip ID，你可以通过 `esp_read_mac(buf, ESP_MAC_WIFI_STA)` 来生成这个 Chip ID。

**Comment by donghengqaz** [comment]
原来的算法是 ID = mac[3] << 16 | mac[4] << 8 | mac[5]。

**Comment by match0131** [comment]
了解了，谢谢
