### ISSUE TITLE
关于 smartConfig 问题，无法识别是 airkiss 配网还是 espTouch 配网？ (GIT8266O-85)

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_RTOS_SDK#544]
- 最近在项目需求中需要识别当前的配网类型是 airkiss 还是 esptouch ，根据以往 sdk2.0 的开发经验，只需要根据结束配网的回调中判断数据即可！

```
    case SC_STATUS_LINK_OVER:
        ESP_LOGI(TAG, "SC_STATUS_LINK_OVER");
        //判断数据是否为空从而判断是否为 airkiss配网？
        if (pdata != NULL) {
            uint8_t phone_ip[4] = {0};
            memcpy(phone_ip, (uint8_t *)pdata, 4);
            ESP_LOGI(TAG, "lcoal phone ip : %d.%d.%d.%d ", phone_ip[0], phone_ip[1], phone_ip[2], phone_ip[3]);
        }  else  {
            ESP_LOGI(TAG, "airkiss start");
        }
        xEventGroupSetBits(wifi_event_group, ESPTOUCH_DONE_BIT);
        break;
```
-----------------------------------

- **现在的问题是，不管哪种配网模式，这个指针 `pdata` 都是 空的**

-----------------------------------

![image](https://user-images.githubusercontent.com/25237870/55694879-bfffae00-59e8-11e9-93f7-047f372b66c4.png)

**Comment by xuhongv** [comment]
- 目前 我是基于 3.1 分支的！

**Comment by FireWinter** [comment]
> * 目前 我是基于 3.1 分支的！

请问你有用最新的esptouch apk进行测试吗？如果是esptouch，pdata 应该不为空，设备端能拿到手机端的ip地址。

**Comment by xuhongv** [comment]
- 我现在是 airkiss 配网，pdata也不为空！
@FireWinter

**Comment by xuhongv** [comment]
@FireWinter @27-301 请问此问题有没有在安排解决了！ rtos 3.1 的配网模式回调中如何判断是 airkiss还是 esptouch？

**Comment by FireWinter** [comment]
> @FireWinter @27-301 请问此问题有没有在安排解决了！ rtos 3.1 的配网模式回调中如何判断是 airkiss还是 esptouch？

当前回调不区分配网模式是airkiss还是esptouch，目前已增加该功能，暂时还未合入github代码分支，近期会先合入并同步到rtos master分支，也会在这里通知到你。

**Comment by xuhongv** [comment]
感谢！！第一时间通知我即可！！

**Comment by xuhongv** [comment]
- 此问题有解决了没 @FireWinter @27-301

**Comment by FireWinter** [comment]
> * 此问题有解决了没 @FireWinter @27-301

已经合入esp8266 rtos master版本，可以测试下

**Comment by xuhongv** [comment]
nice
