### ISSUE TITLE
smartconfig 如何断电重联 (GIT8266O-87)

### ISSUE THREAD

**Issue by panguoxian** [espressif/ESP8266_RTOS_SDK#546]
使用SDK RTOS 3.1官方smartconfig 例程

通过手机espTouch 连接成功后，断电后不能自动重连。
也没找到相关API，想问下应该如何实现？

**Comment by xuhongv** [comment]
- 需要自己保存上次 esptouch的账号密码在本地，之后读取就可以了；参考https://github.com/xuhongv/StudyInEsp8266/tree/master/32_ESP8266_Rtos3.0_NVSWiFi

**Comment by panguoxian** [comment]
> * 需要自己保存上次 esptouch的账号密码在本地，之后读取就可以了；参考https://github.com/xuhongv/StudyInEsp8266/tree/master/32_ESP8266_Rtos3.0_NVSWiFi

非常感谢，解决了我的问题。

**Comment by xuhongv** [comment]
- @panguoxian 你可能还需调用 esp_wifi_connect() 才会自动连接，虽然已经获取到了路由器密码！

**Comment by donghengqaz** [comment]
你可以试下 `esp_wifi_set_storage(WIFI_STORAGE_FLASH)` 模式。

**Comment by 27-301** [comment]
Thanks the answer from @xuhongv . Close this issue, please feel free to open if need.
