### ISSUE TITLE
3.1SDK如何获取2.x.x旧版本存储的wifi配置信息 (GIT8266O-88)

### ISSUE THREAD

**Issue by match0131** [espressif/ESP8266_RTOS_SDK#547]
我们的设备在2.x.x旧版本SDK中使用wifi_station_set_config存储了多个ap的ssid和pwd等重要信息，目前想在旧设备ota升级成3.1SDK后直接获取这些wifi配置，

该如何操作？
是否有相关接口直接调用？
或者是否有flash存储的地址和读取裸数据的格式？

谢谢

**Comment by xuhongv** [comment]
- 可以自定义参数保存，可参看这个：https://github.com/xuhongv/StudyInEsp8266/tree/master/32_ESP8266_Rtos3.0_NVSWiFi

**Comment by match0131** [comment]
额。。。我不是问如何使用3.1SDK存储wifi信息。而是问如何在OTA升级成3.1SDK后获取2.x.x旧版本SDK写入的wifi配置。如何获取不到，是否就变成2.x.x设备OTA升级成3.1SDK后，就无法连接以前配置过的wifi网络了？

**Comment by donghengqaz** [comment]
暂时只能然用户去重新配次网。
