### ISSUE TITLE
RTOS_SDK3.1 如何设置sntp获取网络时间的间隔 (GIT8266O-89)

### ISSUE THREAD

**Issue by huozhe0930** [espressif/ESP8266_RTOS_SDK#548]
为了减少电池供电的能耗，我想设置sntp从网络获取时间的间隔。但是没有找到这样的可用API，
不知道sntp首次获取服务器网络时间后，第二次获取服务器时间的间隔是多少？如何设置这个时间间隔？
在两次获取网络时间间隔时间内，是通过RTC定时器来进行计时的吗？

**Comment by panguoxian** [comment]
自己写这部分，使用
time(&now);
localtime_r(&now, &timeinfo);

**Comment by donghengqaz** [comment]
时间是固定的 `SNTP_UPDATE_DELAY`，需要你在 `lwipopt.h` 里面定义这个宏，单位是 ms。

**Comment by huozhe0930** [comment]
谢谢。

**Comment by huozhe0930** [comment]
SNTP_UPDATE_DELAY，这个宏，我是在sntp_opts.h文件中找到的。
