### ISSUE TITLE
如何获取指定AP的RSSI？ (GIT8266O-95)

### ISSUE THREAD

**Issue by panguoxian** [espressif/ESP8266_RTOS_SDK#551]
SDK3.1版本
需要搜索附近AP的连接RSSI，即未连接的AP。
找不到相关API,查看20A编程手册，只有旧版的，没有找到新版本的编程手册。

1.5版本的编程手册。使用下面的函数。但是我找不到，不知是哪一个头文件的函数？
wifi_station_scan(&config,scan_done);

谢谢！！

**Comment by xuhongv** [comment]
-  esp_wifi_get_ap_rssi()

**Comment by 27-301** [comment]
according to the information you provided, you just want to use scan feature, please refer to https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/esp8266/include/esp_wifi.h, and also can refer to https://github.com/espressif/esp-idf/blob/master/examples/wifi/iperf/main/cmd_wifi.c for the scan part.

**Comment by panguoxian** [comment]
@27-301  thank , The problem has been solved.
