### ISSUE TITLE
esp_wifi_scan_start(&scan_config, true) 只能扫描到几个AP (GIT8266O-98)

### ISSUE THREAD

**Issue by panguoxian** [espressif/ESP8266_RTOS_SDK#552]
使用
esp_wifi_scan_start(&scan_config, true)   //先扫描
esp_wifi_scan_get_ap_records(&ap_num, ap_records) //再读取上一次扫描的AP。
只能扫描到几个AP；
还有很多AP，比如用手机和电脑都能找到，但模块扫不出来。
不知问题出在哪里？

**Comment by ustccw** [comment]
`wifi_scan_config_t` 中配置扫描时间, 扫描类型, 是否扫描隐藏 AP.

**Comment by panguoxian** [comment]
@ustccw 非常感谢你的回复，已经尝试过了，配置时间不起作用。只能扫描出部分，还有很多信号很强的无线路由无法扫描出来。
