### ISSUE TITLE
esp_wifi_scan_start() 之后如何获取扫描完成事件？ (GIT8266O-100)

### ISSUE THREAD

**Issue by panguoxian** [espressif/ESP8266_RTOS_SDK#554]
esp_wifi_scan_start() 之后如何获取扫描完成事件？

esp_wifi_scan_start() 之后马上esp_wifi_scan_get_ap_records()会造成一部分AP无法搜索出来。

因为scan 还没有done.

现在做法是：
esp_wifi_scan_start() 
vTaskDelay(5000);
esp_wifi_scan_get_ap_records()

如何知道是否扫描完成？？

**Comment by ustccw** [comment]
WiFi callback 里有 `SYSTEM_EVENT_SCAN_DONE` 事件.

**Comment by panguoxian** [comment]
@ustccw 非常感谢！！我是新手，对新的SDK还不熟悉。

**Comment by 27-301** [comment]
you can also refer to https://github.com/espressif/esp-idf/blob/master/examples/wifi/iperf/main/cmd_wifi.c for the scan feature.
