### ISSUE TITLE
如何对串口切换一个做log输出另一个做正常串口 (GIT8266O-107)

### ISSUE THREAD

**Issue by panguoxian** [espressif/ESP8266_RTOS_SDK#557]
手册里的我没看懂，UART \ UART0 \UART1有什么区别？

理解切换后UART1 输出就是GPIO2引脚，只能输出log信息。原来的串口保持。

当我把log输出使用make menucinfig 切换成UART1输出后，向串口发信息，会造成死机重启。

手册里说使用切换函数切换串口，UART就不会输出上电信息，但是我切换了一样输出 。

**Comment by xiongyumail** [comment]
@panguoxian 
理解错了，
交换串口:
UART0的RXD和CTS交换
TXD和RTS交换
所以此时你需要从CTS,RTS输入输出数据

UART1打印
只是printf接口port到了UART1, 上电信息仍然会从UART0打印。

**Comment by panguoxian** [comment]
@xiongyumail 非常感谢，解决了我的问题。
