### ISSUE TITLE
lwip_socket_set_so_link() not conditional on SET_SOLINGER_DEFAULT (GIT8266O-115)

### ISSUE THREAD

**Issue by ourairquality** [espressif/ESP8266_RTOS_SDK#560]
Disabling the SET_SOLINGER_DEFAULT option causes compilation to fail as calls to lwip_socket_set_so_link() are still enabled. Workaround was to just make all the calls to lwip_socket_set_so_link() conditional on SET_SOLINGER_DEFAULT.

Given that SET_SOLINGER_DEFAULT causes writes to fail randomly when the socket is closed after writing data, and connection resets, it seems likely that projects will want to disable this option. Probably also confusing to have this different behavior for LWIP_SOCKET_MULTITHREAD, and this feature is also likely to be disabled as many projects are banging on the same socket from multiple threads.

**Comment by donghengqaz** [comment]
I will fix the problem as fast as possible, and thanks for your reporting.
