### ISSUE TITLE
V2 to V3 OTA (GIT8266O-119)

### ISSUE THREAD

**Issue by berkutta** [espressif/ESP8266_RTOS_SDK#564]
I'm trying to perform an V2 to V3 OTA. But I'm currently struggling with building the OTA binary. I followed the guide under https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/api-guides/fota-from-old-new.html#workflow but I'm always getting the following error on `make ota`:

```
LD build/ota.elf
esptool.py v2.4.0
pack_fw.py v1.0.2
usage: pack_fw pack3 [-h] <address> <filename> [<address> <filename> ...]
pack_fw pack3: error: argument <address> <filename>: Detected overlap at address: 0x4000 for file: /home/bmarty/esp/ESP8266_RTOS_SDK/examples/system/ota/native_ota/build/partitions_two_ota.1MB.mini.bin
make: *** [/home/bmarty/esp/ESP8266_RTOS_SDK/components/esp8266/Makefile.projbuild:122: build/ota.v2_to_v3.ota.bin] Error 2

```

**Comment by donghengqaz** [comment]
The bootlaode size is larger, so you should config the partition table offset from 0x4000 to 0x5000 at least, and modify you partition file.

**Comment by berkutta** [comment]
Ok, I have now changed to the partition layout partitions_two_ota_v2tov3.2MB.csv and set offset to 0x8000. But now I'm getting the following strange error on `make ota`:

```
LD build/ota.elf
esptool.py v2.4.0
pack_fw.py v1.0.2
Traceback (most recent call last):
  File "/home/bmarty/esp/ESP8266_RTOS_SDK/tools/pack_fw.py", line 195, in <module>
    _main()
  File "/home/bmarty/esp/ESP8266_RTOS_SDK/tools/pack_fw.py", line 189, in _main
    main()
  File "/home/bmarty/esp/ESP8266_RTOS_SDK/tools/pack_fw.py", line 168, in main
    operation_func(args)
  File "/home/bmarty/esp/ESP8266_RTOS_SDK/tools/pack_fw.py", line 101, in pack3
    fw_data += data
TypeError: can only concatenate str (not "bytes") to str
make: *** [/home/bmarty/esp/ESP8266_RTOS_SDK/components/esp8266/Makefile.projbuild:122: build/ota.v2_to_v3.ota.bin] Error 1
```

**Comment by donghengqaz** [comment]
Maybe this is the problem of your python, I has built the project and have no problem like this.

**Comment by donghengqaz** [comment]
Could you tell me your os and python version ?

**Comment by berkutta** [comment]
I'm using Python 2.7.16 (and Python 3.7.3 but doesn't seem to be relevant) on a Archlinux. What OS are you using?

**Comment by donghengqaz** [comment]
I use ubuntu 18.04, and its internal python 2.7.15rc1 which is the script will default use.

**Comment by berkutta** [comment]
I have tried it now with Ubuntu 18.04.1 and 2.7.15rc1 but it still doesn't work. I'm now getting the following Error on `make ota`:
```
pack_fw.py v1.0.2
Traceback (most recent call last):
  File "/home/bmarty/esp/ESP8266_RTOS_SDK/tools/pack_fw.py", line 195, in <module>
    _main()
  File "/home/bmarty/esp/ESP8266_RTOS_SDK/tools/pack_fw.py", line 189, in _main
    main()
  File "/home/bmarty/esp/ESP8266_RTOS_SDK/tools/pack_fw.py", line 168, in main
    operation_func(args)
  File "/home/bmarty/esp/ESP8266_RTOS_SDK/tools/pack_fw.py", line 110, in pack3
    if args.app in argfile.name:
TypeError: 'in <string>' requires string as left operand, not NoneType
/home/bmarty/esp/ESP8266_RTOS_SDK/components/esp8266/Makefile.projbuild:122: recipe for target 'build/ota.v2_to_v3.ota.bin' failed
make: *** [build/ota.v2_to_v3.ota.bin] Error 1
```

**Comment by donghengqaz** [comment]
Thanks your help, I have found the problem, it is that when some merged code is old and make the command arguments lost.

**Comment by berkutta** [comment]
That also solved the issue on Archlinux. The special binary is also working perfectly with old Bootloader. Thanks for fixing the issue and also providing such a nice solution to update from old SDK.

**Comment by donghengqaz** [comment]
Thank you ：）
