### ISSUE TITLE
don't use rtc mem data

### ISSUE THREAD

**Issue by addendumE** [espressif/ESP8266_RTOS_SDK#57]
Hello,
I tried to compile and flash the "project template" example but the only message I get during boot is "don't use rtc mem data". No other chars are output during boot.

**Comment by physiii** [comment]
I'm getting the same issue. I think is has to do with where in memory the binaries are being flashed.
 
Here's where I'm putting the binaries
esptool.py write_flash 0x00000 eagle.flash.bin 0x20000 eagle.irom0text.bin

**Comment by druizoses** [comment]
I'm also getting the same issue. Then, once the device is booted, only shows garbage characters
Does anybody knows how to fix it?
