### ISSUE TITLE
esp_log_set_vprintf (GIT8266O-126)

### ISSUE THREAD

**Issue by berkutta** [espressif/ESP8266_RTOS_SDK#571]
Are there any plans to provide something similiar to esp_log_set_vprintf from esp-idf in esp8266_rtos_sdk?

**Comment by chschnell** [comment]
Have you tried [esp_log_set_putchar()](https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/log/log.c#L301)? It takes a callback function with [putchar()](https://linux.die.net/man/3/putchar)-like behaviour, you should be able to simply use the normal LOG macros to log to your custom sink after calling that. I haven't tried it out yet, but I was planning to use it to redirect log messages.

**Comment by berkutta** [comment]
That's exactly what I need, thanks @chschnell!
