### ISSUE TITLE
Test Partition (GIT8266O-128)

### ISSUE THREAD

**Issue by berkutta** [espressif/ESP8266_RTOS_SDK#573]
Is there an example partition schema with OTA0/OTA1 and Test Partition for the ESP8266 with IDF Style SDK? If I try with booting Test Partition from e.g. 0x210000 I always get a `app bin error` from the Bootloader. I tried with following schema:
```
nvs,      data, nvs,     0x9000,   0x4000
otadata,  data, ota,     0xd000,   0x2000
phy_init, data, phy,     0xf000,   0x1000
ota_0,    0,    ota_0,   0x10000,  0xF0000
ota_1,    0,    ota_1,   0x110000, 0xF0000
test,     0,    test,    0x210000, 0xF0000

```

**Comment by donghengqaz** [comment]
Now the SDK only supports two "app".
