### ISSUE TITLE
examples/protocols/ibm-mqtt例子 (GIT8266O-142)

### ISSUE THREAD

**Issue by wildhorse1230** [espressif/ESP8266_RTOS_SDK#584]
这个问题解决了吗？只要是进去这个里面的sendPacket函数里面就会返回出错,导致连接被关掉,
if (msg.qos != QOS0) {
            if (msg.qos == QOS1) {
                len = MQTTSerialize_ack(c->buf, c->buf_size, PUBACK, 0, msg.id);
            } else if (msg.qos == QOS2) {
                len = MQTTSerialize_ack(c->buf, c->buf_size, PUBREC, 0, msg.id);
            }

            if (len <= 0) {
                rc = FAILURE;
            } else {
                rc = sendPacket(c, len, timer);
            }

            if (rc == FAILURE) {
                goto exit;    // there was a problem
            }
        }

**Comment by donghengqaz** [comment]
这个老 mqtt 组件后期维护力度不高了，建议使用 esp-mqtt。
