### ISSUE TITLE
Error getting/setting PWM params (GIT8266O-146)

### ISSUE THREAD

**Issue by EventHor1zon** [espressif/ESP8266_RTOS_SDK#588]
## Environment

- Development Kit: NodeMCU (ESP8266)
- IDF version: 07d80fa9 (master)
- Development Env:     Atom/Platformio
- Operating System:     linux
- Power Supply:        USB

## Problem Description

Error getting/setting PWM duty on an active PWM pin.

### Expected Behavior

Expected PWM duty to get/set without errors

### Actual Behavior

Implementing these functions gives a 'channel num error'.

### Code to reproduce this issue

```cpp
#include "esp_log.h"
#include "driver/pwm.h"

void manage_pwm(void *args){
     uint32_t duty;
    while(1){ 
    if(pwm_get_duty(0, &duty) != ESP_OK){ ESP_LOGI(PWM_TAG, "Error in getting duty...\n"); 
} /*error here*/
    if(pwm_set_duty(0, &duty) != ESP_OK){ ESP_LOGI(PWM_TAG, "Error in setting duty...\n); } /* error here */
    }
}

void app_main()
{
    uint32_t duty=0;
    uint32_t pin = GPIO_NUM_0;
    if(pwm_init(1000, &duty, 1, &pin) != ESP_OK) { ESP_LOGI(MAIN_TAG, "Error in intialising pwm\n"); }
     if(pwm_set_phase(0, 0) != ESP_OK) { ESP_LOGI(MAIN_TAG, "Error in setting phase\n"); }
     if(pwm_start() != ESP_OK) { ESP_LOGI(MAIN_TAG, "Error in starting pwm\n"); }

     xTaskCreate(manage_pwm, "pwm", 5012, NULL, 2, NULL);
}
```

Debug: 

Does not cause crash behaviour. Compiles as expected. Errors generated when attempting to modify the PWM channel

Fix:

The channel number is defined as type uint32_t in pwm_init in pwm.h and pwm.c. The variable is added to the pwm_obj_t struct as a uint8_t type  without a cast. Changing the declaration of pwm_init (in both /components/esp8266/driver/pwm.c and /components/esp8266/include/driver/pwm.h) 
``` cpp
esp_err_t pwm_init(uint32_t period, uint32_t *duties, uint8_t channel_num, const uint32_t *pin_num)
``` 
removes this error.

(First github issue, applogies for any missing elements)x

**Comment by xiongyumail** [comment]
@EventHor1zon 

Bugfix has been submitted, thank you!
