### ISSUE TITLE
lwip IP层分片重组 (GIT8266O-149)

### ISSUE THREAD

**Issue by Hynsn** [espressif/ESP8266_RTOS_SDK#591]
你好，了解到较低版本的LWIP协议并不支数据包持数据包的分片与重装功能，请问idf框架中有支持IP层分片吗？抱歉lwip研究的不是很深入，遇到一个问题 APP端发送过来数据超过1468(tcp)/1472(udp)字节时，WiFi模块就完全接受不到数据，网上也查不到好的解决办法，lwip有相应的配置可以解决这个问题吗？

**Comment by donghengqaz** [comment]
我建议你在应用层做组包/分包比较好，IP 分片也是有的，需要配置 `Component config -> LWIP -> Enable fragment outgoing IP packets`。

**Comment by Hynsn** [comment]
好的，谢谢。恰好需要处理的数据长了一丢丢。
