### ISSUE TITLE
How to set printf func to uart1 in esp8266 3.0 RTOS_SDK by code? (GIT8266O-150)

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_RTOS_SDK#592]
- How to set printf func to uart1 in esp8266 3.0 RTOS_SDK by code not in the Make menuconfig ?

**Comment by xiongyumail** [comment]
可以重新定义`ets_putc`替换原有的同名弱函数
```
int ets_putc(int c)
{
    
}
```

**Comment by xuhongv** [comment]
- 这个函数在哪的，，，

**Comment by donghengqaz** [comment]
ets_putc 在 ets_printf.c 里面，你也可以使用 VFS，这个可以选择需要哪个串口，工程参考 exmaples/system/console。

**Comment by xuhongv** [comment]
- 感谢，我现在试试！

**Comment by FayeY** [comment]
想请问，这个问题解决了吗？
