### ISSUE TITLE
lwip IP层分片重组 (GIT8266O-154)

### ISSUE THREAD

**Issue by Hynsn** [espressif/ESP8266_RTOS_SDK#596]
你好，经过测试，当前版本SDK支持IP层分片重组，但不稳定（附件是打印的log）。这里我使用安卓网络助手UDP发送超过1472长度的数据，wifi工作在STA模式下，menuconfig也按照要求配置。
![menuconfig](https://user-images.githubusercontent.com/13035957/57990798-91dbb680-7adc-11e9-879c-f54e22a64278.jpg)
[附件log](https://github.com/espressif/ESP8266_RTOS_SDK/files/3195851/log_20190520.txt)

**Comment by donghengqaz** [comment]
你这个是哪里踩内存了吧，总是 stack 溢出，你用的是不是最新的 matser 分支？最近修复了一些 bug, 可能对你的问题有帮助。

**Comment by donghengqaz** [comment]
你把 LWIP 主线程 stack 配置大一点，从 2048 -> 3072.

**Comment by Hynsn** [comment]
是旧一点的Master分支，代码没有问题。已更新到最新的版本测试，成功解决该bug。
