### ISSUE TITLE
Doc error eclipse-setup.rst   (GIT8266O-160)

### ISSUE THREAD

**Issue by cqwuxiaolong** [espressif/ESP8266_RTOS_SDK#600]
18:58:34 **** Build of configuration Default for project ESP8266_RTOS_SDK ****
make -j8 all 
Makefile:8: /home/cqwuxiaolong/esp/ESP8266_RTOS_SDK:/home/cqwuxiaolong/esp/ESP8266_RTOS_SDK//make/project.mk: No such file or directory
make: *** No rule to make target '/home/cqwuxiaolong/esp/ESP8266_RTOS_SDK:/home/cqwuxiaolong/esp/ESP8266_RTOS_SDK//make/project.mk'.  Stop.
"make -j8 all" terminated with exit code 2. Build might be incomplete.

18:58:34 Build Failed. 1 errors, 1 warnings. (took 267ms)

if build SDK ,can not use 
"* Click "Add..." again, and enter name ``IDF_PATH``. The value should be the full path where ESP8266_RTOS_SDK is installed."

**Comment by donghengqaz** [comment]
你目录没有配置对吧，'/home/cqwuxiaolong/esp/ESP8266_RTOS_SDK:/home/cqwuxiaolong/esp/ESP8266_RTOS_SDK//make/project.mk'，这就是个错误路径。eclipse 用的人不多，用起来也比较麻烦，用 vscode 编辑代码，敲敲命令更加方便简单。
