### ISSUE TITLE
how to set std::thread prios correctly? issue about:  esp_pthread_get_cfg(&cfg) and esp_pthread_set_cfg(&cfg) (GIT8266O-169)

### ISSUE THREAD

**Issue by dsyleixa** [espressif/ESP8266_RTOS_SDK#609]
forwarded from these discussions, 
https://github.com/espressif/esp-idf/issues/3544#issuecomment-496157019
https://github.com/espressif/arduino-esp32/issues/2814#issuecomment-495916516
there are still  issues about how to set thread prios correcty.

```
esp_pthread_cfg_t cfg;
  esp_pthread_get_cfg(&cfg);
  cfg.prio=1;
  esp_pthread_set_cfg(&cfg);
```
is suspected not to work because cfg might be empty and the function may return an error
and
```
  esp_pthread_cfg_t cfg;
  if (esp_pthread_get_cfg(&cfg) != ESP_OK) {
      cfg = esp_pthread_get_default_config();
  }
  cfg.prio=1;
  if (esp_pthread_set_cfg(&cfg) != ESP_OK) {
      printf("esp_pthread_set_cfg failed\n");
      abort();
  };
```

does not work, because 
esp_pthread_get_default_config();
is not found by the compiler.

**Which is the correct way, or what am I missing?**

_________________

latest (still faulty) code version (for Arduino API/IDE) 
(issue: main loop() is blocked totally, constantly, compltely):

```
// std::thread for ESP32, Arduino IDE

// ver 0.0.5 fibonacci

#include <Arduino.h>
#include <thread>
#include <esp_pthread.h>

#ifndef LED_BUILTIN
#define LED_BUILTIN 13
#endif

const auto one_sec = std::chrono::seconds
{
    1
};



int fibbonacci(int n) {
   if(n == 0){
      return 0;
   } else if(n == 1) {
      return 1;
   } else {
      return (fibbonacci(n-1) + fibbonacci(n-2));
   }
}



void fibonacci_loop() {
    thread_local uint32_t counter = 0, i=0;
    while(true) {
        Serial.println((String)"fibonacci_loop counter: "+counter);  
        for(i=30; i<41; i++) {    // limits: test, debug
          Serial.println( (String)"Fibbonacci of "+i+"="+fibbonacci(i));            
        }                
        counter++;      
    }
}



void blinker_loop() {
    thread_local uint32_t counter = 0;
    while(true) {
        digitalWrite(LED_BUILTIN, HIGH);
        Serial.println((String)"blinker_loop (HIGH) counter: "+ counter);
        std::this_thread::sleep_for(one_sec);
        
        digitalWrite(LED_BUILTIN, LOW);
        Serial.println((String)"blinker_loop (LOW) counter: "+ counter);
        std::this_thread::sleep_for(one_sec);
        
        counter++;
    }
}



std::thread *thread_1;
std::thread *thread_2;

void setup() {
  Serial.begin(115200);
  //debug
  delay(1000);
  
  esp_pthread_cfg_t cfg;
  if (esp_pthread_get_cfg(&cfg) != ESP_OK) {
      cfg = esp_pthread_get_default_config();
  }
  cfg.prio=1;
  if (esp_pthread_set_cfg(&cfg) != ESP_OK) {
      printf("esp_pthread_set_cfg failed\n");
      abort();
  };
  
  thread_1 = new std::thread(blinker_loop);
  thread_2 = new std::thread(fibonacci_loop);
}



void loop() {
    static uint32_t main_loop_counter = 0;
    Serial.println((String)"main loop: " + main_loop_counter);
    delay(5000);
    main_loop_counter++;
}
```

**Comment by dsyleixa** [comment]
after having fixed that, the wishful would be for the future, e.g. like for POSIX pthread

    param.sched_priority = 1;
    pthread_setschedparam(thread0, SCHED_RR, &param);
   
    param.sched_priority = 2;
    pthread_setschedparam(thread1, SCHED_RR, &param);
   
        param.sched_priority = 5;
    pthread_setschedparam(thread2, SCHED_RR, &param);

**Comment by donghengqaz** [comment]
Is your problem is about esp-idf(ESP32)？If so, the issue should be moved to esp-idf issues place.

**Comment by dsyleixa** [comment]
yes, but it has been stated that it's about issues in the pthread libs.
Additionally it turned out that there are watchdog and scheduler issues in the pthread/std::thread implementation about preemptivity.

**Comment by me21** [comment]
You're posting an issue for ESP32 in ESP8266 repo.

**Comment by dsyleixa** [comment]
sorry, I missed that - where is the RTOS repo for ESP32?

**Comment by me21** [comment]
https://github.com/espressif/arduino-esp32 you've already opened an issue there.

**Comment by me21** [comment]
https://github.com/espressif/esp-idf

**Comment by dsyleixa** [comment]
well - that is not actually about the underlying ESP32 RTOS, is it?

**Comment by me21** [comment]
It is.

**Comment by dsyleixa** [comment]
ok, thank you!
