### ISSUE TITLE
HTTPS is used always, even if the URL starts with "http" (GIT8266O-170)

### ISSUE THREAD

**Issue by oleszczyk** [espressif/ESP8266_RTOS_SDK#610]
## Environment

- Development Kit: custom device
- IDF version: f49b40e79ddd52f89d2bdb597001a240beae4064
- Development Env:      Make
- Operating System:     Ubuntu
- Power Supply:            USB

## Problem Description

If CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS is enabled current implementation forces using SSL everytime - whatever user requests 'http' or 'https' URL. It would be better if HTTPS connection was handle only when there is 'https' in the URL beginning. Otherwise simple HTTP connection should be used.

### Expected Behavior

When user enabled CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS switch, then still should be possible to use HTTP protocol without SSL if URL indicates that.

### Actual Behavior

When user enabled CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS switch then whatever what URL he requests always SSL will be forced. Current implementation:

```cpp
#ifdef CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS
    esp_transport_handle_t ssl;
    _success = (
                   (ssl = esp_transport_ssl_init()) &&
                   (esp_transport_set_default_port(ssl, DEFAULT_HTTPS_PORT) == ESP_OK) &&
                   (esp_transport_list_add(client->transport_list, ssl, "https") == ESP_OK)
               );
    if (!_success) {
        ESP_LOGE(TAG, "Error initialize SSL Transport");
        esp_http_client_cleanup(client);
        return NULL;
    }
    if (config->cert_pem) {
        esp_transport_ssl_set_cert_data(ssl, config->cert_pem, strlen(config->cert_pem));
    }
#endif
```

## Other items if possible

I have already created pull request with necessary changes here:
https://github.com/espressif/ESP8266_RTOS_SDK/pull/606

**Comment by donghengqaz** [comment]
The SSL objects are only created, but not used. This may cost some RAM. You can refer to the [http client exmaple](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/protocols/esp_http_client);
