### ISSUE TITLE
pwm设置相位时候，发送：phase error 180, valid ramge from (-180,180) (GIT8266O-171)

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_RTOS_SDK#611]
## Environment

- Development Kit:
- IDF version： v3.2-dev-342-g02382a2c
- Development Env:      [Make]
- Operating System:     [Windows]
- Power Supply:         [USB]

## Problem Description

  最近在做pwm互补的驱动工程，看到新版的sdk支持相位设置，但是设置相位时候，设置 180时候， 提示错误！难道范围是 -179 到 179 ? 

### 设置179时候，波形如下，提示：` phase error 180, valid ramge from (-180,180)`：

![image](https://user-images.githubusercontent.com/25237870/58536050-0bcd1780-8222-11e9-967a-95e6947eced0.png)

## Other items if possible

- [ ] 现在我修改底层驱动把范围调整为 大于181 ，现在没事了！

![image](https://user-images.githubusercontent.com/25237870/58535553-e12e8f00-8220-11e9-8e80-20d0b1781341.png)

- [ ] 波形截图.
![image](https://user-images.githubusercontent.com/25237870/58535700-26eb5780-8221-11e9-8148-d8bbdccecc8a.png)

**Comment by xiongyumail** [comment]
@xuhongv 

需要反相可以用`pwm_set_channel_invert()`接口，
不过驱动里也可以改成[-180, 180]

**Comment by xuhongv** [comment]
感谢！
