### ISSUE TITLE
MMAP flash partitions to memory NOT supported in ESP8266_RTOS_SDK? (GIT8266O-172)

### ISSUE THREAD

**Issue by zinahe** [espressif/ESP8266_RTOS_SDK#612]
Hi,

It appears the functions **spi_flash_mmap()** and **esp_partition_mmap()** are blocked behind either **#ifdef CONFIG_IDF_TARGET_ESP32** or  **#ifdef CONFIG_ENABLE_FLASH_MMAP** in many places. 

https://github.com/espressif/ESP8266_RTOS_SDK/blob/3a30f08a0bd192f60e00770bdadef822daaf4439/components/app_update/esp_ota_ops.c#L505-L520

https://github.com/espressif/ESP8266_RTOS_SDK/blob/1e294d110262625d6e8df0b4c0ceb5fe9f2f6b58/components/spi_flash/include/esp_partition.h#L260-L290

I'm wondering if this feature is missing because of hardware limitation or it's coming to ESP8266 at some point.

Regards,

Zinahe A.

**Comment by donghengqaz** [comment]
ESP8266 does not support MMU and its flash map unit bus width is not enough wide, so the feature can't bu used.
