### ISSUE TITLE
RTOS3.2 demo http_request receive many data(100K+) will died  (GIT8266O-177)

### ISSUE THREAD

**Issue by FreeChase** [espressif/ESP8266_RTOS_SDK#617]
i find the Chip will died occasionally when i use the demo:http_request get 100K+ data from AliCloud,
and i configure HARD_WDG, but it cant reset the chip, At the same time ,the UART0 will send many data.

**Comment by metadata1984** [comment]
it‘s not ony appear in v3.2 ,bus also in v3.1。’

**Comment by donghengqaz** [comment]
You can add function("esp_task_wdt_reset") to "feed" watch dog after finishing "read" data from socket.

**Comment by FreeChase** [comment]
I find, I will send data with UART0 when I readed http data. So if the return number of function read is -1, 
The UART0 will send many data.  So function int uart_write_bytes(uart_port_t uart_num, const char *src, size_t size)  should check  size.

**Comment by FayeY** [comment]
May I ask if this issue is solved now？

**Comment by FreeChase** [comment]
这个 uart_write_bytes 函数，得坐下size参数检查处理，因为输入-1，它也传输数据。

**Comment by xiongyumail** [comment]
@FreeChase

uart_write_bytes的变量size使用的是size_t 类型，它实际上是无符号类型的。
对长度检查应放在应用层，然后强制整形为(size_t)类型。
