### ISSUE TITLE
ibm-mqtt examples: mqtt close session (GIT8266O-178)

### ISSUE THREAD

**Issue by DraftPaper** [espressif/ESP8266_RTOS_SDK#618]
## 问题描述
使用ibm-mqtt的例子：
当收到qos0的订阅消息时，不会有问题；
当收到qos1和qos2的订阅消息时，会话被关闭（必现）；
log显示：
mc: mqtt close session
mc: MQTTRun cycle failed

### 跟踪1
问题发生在MQTTClient.c文件的cycle()函数中
![image](https://user-images.githubusercontent.com/50624956/59024329-4cf9a300-8884-11e9-82f4-d251e78c8d33.png)
当qos不为0时，会调用rc = sendPacket(c, len, timer);
但函数返回FAILURE，导致session被关闭

### 跟踪2
![image](https://user-images.githubusercontent.com/50624956/59024786-399b0780-8885-11e9-8cbb-a38d2231a9c8.png)
跟踪sendPacket函数，发现是由于TimerIsExpired()函数超时，导致数据未发送，且返回FAILURE

### 跟踪3
添加打印
![image](https://user-images.githubusercontent.com/50624956/59024961-a7473380-8885-11e9-8495-df74fd7d3cec.png)
在执行sendPacket()前打印定时器内容，log显示为：
timer:88, 0, 2448
将xTicksToWait强制设置为5000，不会断开会话

**Comment by donghengqaz** [comment]
这个看上去就是等待时间不对导致的问题。现在这个 IBM 的 MQTT 已经啊不维护了，官方也不怎么维护，从易用性和长远的考虑，我建议你使用 esp-mqtt。
