### ISSUE TITLE
Support for Multicasting UDP

### ISSUE THREAD

**Issue by chillin0531** [espressif/ESP8266_RTOS_SDK#62]
Hi,
Is it possible to perform multicasting in ESP8266? If so, how?

**Comment by HKRS** [comment]
Hey..!
I'm also trying to do multicast .It's(esp8266) not joining into multicast group. there is a function for it i.e
netconn_join_leave_group(struct netconn *conn,
                         ip_addr_t *multiaddr,
                         ip_addr_t *netif_addr,
                         enum netconn_igmp join_or_leave)

**Comment by tzxespressio** [comment]
Hi guys , could you give the sample code about joining IGMP? I have test  IGMP，I'm sure it can work.
