### ISSUE TITLE
esp-tls: mbedtls_x509_crt_parse returned -0x2180 when function OTA (GIT8266O-180)

### ISSUE THREAD

**Issue by thisdream** [espressif/ESP8266_RTOS_SDK#620]
esp-tls: mbedtls_x509_crt_parse returned -0x2180

## Environment

    Development Kit: esp8266
    IDF version commit: esp-idf v3.2-dev-353-gf49b40e7
    Development Env: [VScode]
    Operating System: [Windows|
    Power Supply: [USB]

## Problem Description

when I try example of simple_ota_example show logs :esp-tls: mbedtls_x509_crt_parse returned -0x2180
all bug logs:
csum 0xfa
[0;32mI (49) boot: ESP-IDF v3.2-dev-353-gf49b40e7 2nd stage bootloader[0m
[0;32mI (49) boot: compile time 12:36:01[0m
[0;32mI (50) qio_mode: Enabling default flash chip QIO[0m
[0;32mI (58) boot: SPI Speed      : 40MHz[0m
[0;32mI (64) boot: SPI Mode       : QIO[0m
[0;32mI (70) boot: SPI Flash Size : 4MB[0m
[0;32mI (76) boot: Partition Table:[0m
[0;32mI (82) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (93) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (105) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (116) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (128) boot:  3 ota_0            OTA app          00 10 00010000 000f0000[0m
[0;32mI (139) boot:  4 ota_1            OTA app          00 11 00110000 000f0000[0m
[0;32mI (151) boot: End of partition table[0m
[0;32mI (158) boot: No factory image, trying OTA 0[0m
[0;32mI (165) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x6f8b8 (456888) map[0m
[0;32mI (332) esp_image: segment 1: paddr=0x0007f8d0 vaddr=0x3ffe8000 size=0x00558 (  1368) load[0m
[0;32mI (333) esp_image: segment 2: paddr=0x0007fe30 vaddr=0x3ffe8558 size=0x0019c (   412) load[0m
[0;32mI (344) esp_image: segment 3: paddr=0x0007ffd4 vaddr=0x40100000 size=0x065f8 ( 26104) load[0m
[0;32mI (365) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (409) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (419) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (579) phy_init: phy ver: 1055_12[0m
[0;32mI (589) reset_reason: RTC reset 2 wakeup 0 store 0, reason is 2[0m
[0;32mI (599) simple_ota_example: Setting WiFi configuration SSID SmartT1...[0m
[0;32mI (609) simple_ota_example: Starting OTA example...[0m
[0;32mI (33669) event: sta ip: 192.168.43.201, mask: 255.255.255.0, gw: 192.168.43.1[0m
[0;32mI (33669) simple_ota_example: Connect to Wifi ! Start to Connect to Server....[0m
[0;31mE (33809) esp-tls: mbedtls_x509_crt_parse returned -0x2180

[0m
[0;31mE (33829) esp-tls: Failed to open new connection[0m
[0;31mE (33829) TRANS_SSL: Failed to open a new connection[0m
[0;31mE (33829) HTTP_CLIENT: Connection failed, sock < 0[0m
[0;31mE (33839) esp_https_ota: Failed to open HTTP connection: 28674[0m
[0;31mE (33849) simple_ota_example: Firmware Upgrades Failed[0m

**Comment by donghengqaz** [comment]
Your certificate is error, the client and server must use the same certificate of "ca_cert.h".
