### ISSUE TITLE
esp_mqtt reconnect error: TRANS_SSL: esp_tls_conn_read error, errno=Socket is not connected (GIT8266O-189)

### ISSUE THREAD

**Issue by hiperiondev** [espressif/ESP8266_RTOS_SDK#628]
If MQTT broker not respond after connection (ex: go down) not reconnect and start infinite error:
 esp_mqtt reconnect error: TRANS_SSL: esp_tls_conn_read error, errno=Socket is not connected

This problem is solved by esp-idf patch:
https://github.com/espressif/esp-idf/issues/2805
https://github.com/espressif/esp-idf/files/2667143/0001-tcp_transport-fixed-ssl-reconnection-issue.patch.txt

**Comment by hiperiondev** [comment]
was corrected in ESP-IDF:
https://github.com/espressif/esp-idf/commit/582bf1878983b45e96d690a253d665a590b06266

**Comment by donghengqaz** [comment]
The code sync maybe a little slow, and thank you very much. I will fix the bug as soon as possible.

**Comment by hiperiondev** [comment]
solved: https://github.com/espressif/ESP8266_RTOS_SDK/commit/e5c02e2de7c2fbbb46b53e00e393b18b8186abdd
