### ISSUE TITLE
FreeRTOS SDK SPI API issue

### ISSUE THREAD

**Issue by mohdamerkhalidi** [espressif/ESP8266_RTOS_SDK#63]
Hi,
 I am trying to work with the SPI APIs for esp8266-12f. When reading the SPI device ID using the SPI SDK API for getting the device id, I get 4016E0. It seems the external flash on the board is of size 4Mbytes divided into 4KByte sectors(I did verify this). While reading the flash sectors, I can read the sectors from 0-127 but when reading sector 128,129.., the API returns error. Is this because the flash size is 4Mbit rather than  4Mbyte. Or is there something that I am missing here? The FreeRTOS' API system_get_sdk_version returns the SDK Version as 1.4.0(c599790).

**Comment by tzxespressio** [comment]
How do you download your bin file to the board? by esptools or the windows download tool which can get from bbs.espressif.com ,I think something wrong happended when you choose the flash size map.
