### ISSUE TITLE
Can we configure the GPIO mode as push-pull mode? (GIT8266O-193)

### ISSUE THREAD

**Issue by kmalloc8** [espressif/ESP8266_RTOS_SDK#630]
Hi, 
Can we configure the GPIO mode as push-pull mode?  
It seems only has open-drain mode in gpio.h.

**Comment by xiongyumail** [comment]
@kmalloc8 

`GPIO_MODE_OUTPUT`

**Comment by kmalloc8** [comment]
@xiongyumail , thank you!!
