### ISSUE TITLE
新版SDK复位问题 (GIT8266O-197)

### ISSUE THREAD

**Issue by leo-ivan** [espressif/ESP8266_RTOS_SDK#634]
新版SDK无法调用system_restore函数，汇报下面的错误：
![image](https://user-images.githubusercontent.com/3993068/59576824-9f905600-90f3-11e9-8c09-a06f89bb0702.png)

 undefined reference to `system_restore'
请问复位调用什么函数，或是其他什么方式可以复位

**Comment by wzbhbb** [comment]
esp_restart();

**Comment by leo-ivan** [comment]
esp_restart()应该是重启而不是复位，类似恢复出厂设置一样。

**Comment by wzbhbb** [comment]
那出厂设置是否可以自己定义，通过程序固定几个参数来实现

**Comment by leo-ivan** [comment]
是可以，以前项目是基于旧的SDK，要想恢复出厂设置直接调用system_restore即可，如果新版SDK不支持的话，那只能自己实现了。

**Comment by ustccw** [comment]
@leo-ivan @wzbhbb 可以试一下接口 `esp_wifi_restore`, 定义在 `esp_wifi.h`

**Comment by leo-ivan** [comment]
@ustccw 好的，谢谢
