### ISSUE TITLE
结构体esp_chip_info_t中revision的值对于esp8266和esp32是否相互唯一，即：esp8266与esp32的revision的值不会重复 (GIT8266O-201)

### ISSUE THREAD

**Issue by thisdream** [espressif/ESP8266_RTOS_SDK#638]
结构体esp_chip_info_t中revision的值对于esp8266和esp32是否相互唯一，即：esp8266与esp32的revision的值不会重复？

**Comment by donghengqaz** [comment]
No, the "revision" only serves their own family chip，so you may also use “model” to check the target one.
