### ISSUE TITLE
NodeMCU esp8266 upload issue (GIT8266O-202)

### ISSUE THREAD

**Issue by davood-dorostkar** [espressif/ESP8266_RTOS_SDK#639]
Hello!

I've got a NodeMCU board like this one: [NodeMCU](https://www.indiamart.com/proddetail/node-mcu-esp-8266-wifi-board-ch340-15318259991.html)

I installed the CH340 driver and esp8266 library, but I still can't upload sketches into it. I tried pushing the Flash button while uploading the code with no success.
I don't know how to communicate with the board. I am using VScode with PlatformIO (I've tried Arduino IDE as well with the same result) and It says:
`A fatal error occurred: Failed to connect to ESP8266: Timed out waiting for packet header
*** [upload] Error 2`

Could anybody help?

Full serial log:

Verbose mode can be enabled via -v, --verbose option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz 80KB RAM (4MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 41 compatible libraries
Scanning dependencies...
No dependencies
Retrieving maximum program size .pioenvs\nodemcuv2\firmware.elf
Checking size .pioenvs\nodemcuv2\firmware.elf
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [===       ]  32.4% (used 26540 bytes from 81920 bytes)
PROGRAM: [==        ]  24.6% (used 257096 bytes from 1044464 bytes)
Configuring upload protocol...
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: COM13
Uploading .pioenvs\nodemcuv2\firmware.bin
esptool.py v2.6
Serial port COM13
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP8266: Timed out waiting for packet header
*** [upload] Error 2
======================================================= [ERROR] Took 27.75 seconds =======================================================
The terminal process terminated with exit code: 1

**Comment by FayeY** [comment]
Sorry that we have limited experience about the nodemcu. Maybe you can get some help in https://github.com/nodemcu.
