### ISSUE TITLE
系统时间获取的API (GIT8266O-203)

### ISSUE THREAD

**Issue by woodyfan** [espressif/ESP8266_RTOS_SDK#640]
我想实现一个离线时钟，希望在联网的时候通过sntp实现网络校时，并同时存储系统时间，离线的时候通过类似于 system_get_time()的api获取本地时间进行时间的更新，但是好像在3.0版本以后就没有这个api了，system_rtc_get_time()也没有找到，不知道是否有类似的替代函数

**Comment by xiongyumail** [comment]
参考`sntp`例程
<https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/protocols/sntp>

**Comment by woodyfan** [comment]
这个例程没有考虑联网离线以后的时钟更新问题，如果后期突然断网不是时钟就不能继续走了吗？这就是我想要系统时间API的原因

**Comment by woodyfan** [comment]
我烧写进去试了一下并看了看SNTP完整内容，发现断网后时钟继续走的问题在协议中已经解决了，系统时间在本例中是伪需求，故关闭本issue
