### ISSUE TITLE
esp8266 新SDK烧录后无法启动 (GIT8266O-204)

### ISSUE THREAD

**Issue by lindabang** [espressif/ESP8266_RTOS_SDK#641]
**问题描述:**
新下载的最新版本的SDK,编译后烧录到esp8266无法运行, 错误如下:
 ets Jan  8 2013,rst cause:2, boot mode:(3,0)

load 0x40100000, len 9560, room 16 
tail 8
chksum 0x69
load 0x3ffea938, len 48, room 0 
tail 0
chksum 0x69
load 0x3ffea968, len 4848, room 8 
tail 8
chksum 0xaa
I (47) boot: ESP-IDF v3.2-7-g7351110 2nd stage bootloader
I (47) boot: compile time 21:28:07
I (47) boot: SPI Speed      : 40MHz
I (53) boot: SPI Mode       : DIO
I (59) boot: SPI Flash Size : 4MB
I (65) boot: Partition Table:
I (71) boot: ## Label            Usage          Type ST Offset   Length
I (82) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (94) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (105) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (117) boot:  3 ota_0            OTA app          00 10 00010000 000f0000
I (128) boot:  4 ota_1            OTA app          00 11 00110000 000f0000
I (140) boot: End of partition table
I (147) boot: No factory image, trying OTA 0
I (154) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x31454 (201812) map
I (251) esp_image: segment 1: paddr=0x0004146c vaddr=0x3ffe8000 size=0x0051c (  1308) load
I (252) esp_image: segment 2: paddr=0x00041990 vaddr=0x3ffe851c size=0x0019c (   412) load
I (263) esp_image: segment 3: paddr=0x00041b34 vaddr=0x40100000 size=0x05ae0 ( 23264) load
I (286) boot: Loaded app from partition at offset 0x10000
I (305) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (31

(串口至此就没有输出了, 感觉到此系统就死机了)

**系统环境:**
Centos 7.0 32bit   

已经尝试编译以下代码:
commit id: 735111069bab94866b6ee3566144007a91c217f6
tag: v3.2 , v3.1, v3.0

已经尝试过各种menuconfig, 包括缺省的menuconfig, 以下最后尝试的sdkconfig:

[sdkconfig.txt](https://github.com/espressif/ESP8266_RTOS_SDK/files/3319003/sdkconfig.txt)

![es8266-sdk3](https://user-images.githubusercontent.com/23623339/59986900-55ffb800-966b-11e9-994d-53818772a27f.PNG)
![es8266-sdk3-2](https://user-images.githubusercontent.com/23623339/59987213-7b40f600-966c-11e9-878c-ebf962016d49.PNG)

**Comment by mygod520** [comment]
你好，请问问题是否解决呢
