### ISSUE TITLE
esp_event + esp_websocket_client (GIT8266O-209)

### ISSUE THREAD

**Issue by berkutta** [espressif/ESP8266_RTOS_SDK#646]
Would it maybe be possible to get esp_event + esp_websocket_client from ESP-IDF in ESP8266_RTOS_SDK?

**Comment by donghengqaz** [comment]
We had planed to add it at SDK release/v4.0 version. Do you need to use this?  esp_websocket_client is a protocol and it is neccessary, but is esp_event also needed?
