### ISSUE TITLE
esp8266的ap 口是不是不能接收目的mac不是本接口的数据？ (GIT8266O-211)

### ISSUE THREAD

**Issue by philar** [espressif/ESP8266_RTOS_SDK#648]
如题

**Comment by donghengqaz** [comment]
广播等报文也能收到。

**Comment by philar** [comment]
那单播的目的mac不是本接口的能收到吗？

发自我的 iPhone

**Comment by donghengqaz** [comment]
如果想收到必须开启 sniffer 模式，但是这个模式下 sta/ap 无法工作，具体使用可以参考 [sniffer example](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/wifi/sniffer)。
