### ISSUE TITLE
使用esp_https_ota升级固件时，如何忽略服务器的证书？ (GIT8266O-213)

### ISSUE THREAD

**Issue by lindabang** [espressif/ESP8266_RTOS_SDK#650]
我不希望验证服务器的SSL证书，以使ESP8266能够与更多的服务器连接。
在做升级固件的时候，使用了esp_https_ota，如何才能不验证服务器证书？

**Comment by donghengqaz** [comment]
我看了这个组件的源码，发现证书这个东西必须传递进去用于校验；我又看了esp-idf 里面最新的改动也必须校验服务器证书，这是防止被劫持导致更新了一个错误的固件。

**Comment by lindabang** [comment]
我们使用ESP8266做的标准传感器，预想服务器端按照标准就可以管控这个传感器，所以无法预置服务器证书

**Comment by donghengqaz** [comment]
我这边必须维持 SDK 和 esp-idf 的业务逻辑上保持一致，所以我可以提供一个 patch 给你们去做这个事情，怎么样？

**Comment by redchenjs** [comment]
@donghengqaz esp-idf中的ota组件能够配置为http模式，此模式下无需校验ssl证书，不如直接引进这个特性？

**Comment by donghengqaz** [comment]
看上去这个是有点老了，我直接更新到 esp-idf v3.3 里面的组件和 example。

**Comment by donghengqaz** [comment]
我试着更新了一下，发现依赖项目太多，需要花不少时间来做这个事情。

**Comment by lindabang** [comment]
好的，谢谢各位
