### ISSUE TITLE
A little bug about wifi reconnection (GIT8266O-215)

### ISSUE THREAD

**Issue by Genius-SexyBoy** [espressif/ESP8266_RTOS_SDK#651]
Issue: Disconnect reason : 2
SDK version: master && release-v3.2
Location: wifi event callback func(`static esp_err_t event_handler(void *ctx, system_event_t *event`))

Description：In my project, I use the wifi to obtain some data from server, when it finished, the wifi will be disconnected and waiting for the next connection.And the" **Disconnect reason : 2** "will be discovered in the reconnection period.But it seems to have no effect on my project except costing more a little time to reconnection.

All Logs:

I (84753) event_handler: Scanf done
I (84753) event_handler: Send ZL_SCANF_DONE done!
I (84843) ZL_WIFI_EVENT: Receive done
I (84843) network: checking ssid...
I (87263) event_handler: Scanf done
I (87263) event_handler: Send ZL_SCANF_DONE done!
I (87353) ZL_WIFI_EVENT: Receive done
I (87353) network: checking ssid...
I (87353) network: Setting WiFi configuration SSID Huang...
I (87533) wificlock: Free heap size: 54252

I (88493) event_handler: Send ZL_DISCONNECTED done!
**E (88493) event_handler: Disconnect reason : 2**
I (88493) ZL_WIFI_EVENT: Receive done
I (90533) wificlock: Free heap size: 52952

I (91353) event_handler: Scanf done
I (91353) event_handler: Send ZL_SCANF_DONE done!
I (91403) ZL_WIFI_EVENT: Receive done
I (91403) network: checking ssid...
I (91403) network: Setting WiFi configuration SSID Huang...
I (93533) wificlock: Free heap size: 53860

I (94593) event: sta ip: 192.168.43.9, mask: 255.255.255.0, gw: 192.168.43.1
I (94593) event_handler: Send ZL_GOT_IP done!
I (94593) ZL_WIFI_EVENT: Receive done
I (96533) wificlock: Free heap size: 53860

That's all.
Regards.

**Comment by donghengqaz** [comment]
How do you obtain some data from server? Could you apply some exmaple code to show how it works?

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details. Thanks.
