### ISSUE TITLE
what means of osi_funcs in wifi_init_config_t (GIT8266O-220)

### ISSUE THREAD

**Issue by thisdream** [espressif/ESP8266_RTOS_SDK#656]
I don't know the work of osi_funcs in wifi_init_config_t,that is definded in esp_wifi.h

- IDF version：esp8266-rtos-sdk v3.2 and  idf v3.2

**Comment by donghengqaz** [comment]
It is no meaning for ESP8266 SDK but it has great meaning that it will register operation system adapter API to Wi-Fi library for esp-idf.
