### ISSUE TITLE
ESP8266 release/v3.2 深度睡眠超时唤醒误差为何那么大，是否可优化 (GIT8266O-225)

### ISSUE THREAD

**Issue by fengfeng0328** [espressif/ESP8266_RTOS_SDK#661]
ESP8266 release/v3.2 深度睡眠超时唤醒实测误差较大，复现方法如下：

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include "driver/gpio.h"

#include "esp_log.h"
#include "esp_system.h"

#include "esp_sleep.h"

static const char *TAG = "main";

/******************************************************************************
 * @ 10秒后系统进入深度睡眠模式，外部唤醒
 * @ EXT_RSTB  管脚拉低，芯片重置并唤醒
*******************************************************************************/
void app_main(void)
{
	for (int timer = 0; timer < 10; timer++) {
		ESP_LOGI(TAG, "timer: %d\n",timer);
		vTaskDelay(1000 / portTICK_RATE_MS);
	}

	ESP_LOGI(TAG, "start esp_deep_sleep\n");

	/* 发现进入深度睡眠后无法再次烧录固件 */
	esp_deep_sleep(0xffffffff);
}

实测误差截图：
![image](https://user-images.githubusercontent.com/34309825/61684663-c2460800-ad4c-11e9-8d27-13dc8867043e.png)

理论时间：0xffffffff/(1000乘1000乘60)=71分钟
实际时间：如截图67分钟
误差时间：4分钟

请问这是芯片限制还是可做优化？

**Comment by donghengqaz** [comment]
深度睡眠的时候，由于使用低功耗的振荡器来产生脉冲时钟，所以是有一些的误差的需要做校准，建议你在应用层做时间校准。
