### ISSUE TITLE
调用esp_wifi_sta_get_ap_info()接口宕机 (GIT8266O-226)

### ISSUE THREAD

**Issue by DraftPaper** [espressif/ESP8266_RTOS_SDK#662]
## 环境
- SDK version: v3.2
- Development Env: Make
- Operating System: Ubuntu

## 问题描述
station从ap处断开后，调用esp_wifi_sta_get_ap_info()接口，出现宕机（必现）

### 预期行为
esp_wifi_sta_get_ap_info()返回ESP_ERR_WIFI_NOT_CONNECT

### 复现步骤
1. 设备处于station模式，并连接ap；
2. 由于某些原因导致连接被断开（触发SYSTEM_EVENT_STA_DISCONNECTED事件）后；
3. 调用esp_wifi_sta_get_ap_info()接口，出现宕机。

## Debug Logs
08:00:05.640 [I] miio_net: Wifi event[5]
08:00:05.640 [W] miio_net: Wifi disconnect from ssid xxx, reason 2 (wifi_cb_event_handler,263)

Task stack [esp_event_loop_] stack from [3fff9490] to [3fff9c90], total [2048] size
00000000 00000004 00000008 0000000c 00000010 00000014 00000018 0000001c 00000020 00000024 00000028 0000002c 00000030 00000034 00000038 0000003c

**Comment by FayeY** [comment]
新版本应该已经解决了这个问题，烦请更新使用。谢谢！
