### ISSUE TITLE
怎让让esp8266支持中文? (GIT8266O-229)

### ISSUE THREAD

**Issue by Sangxin2017** [espressif/ESP8266_RTOS_SDK#665]
How to support Chinese?

**Comment by xiongyumail** [comment]
中文文档么？

**Comment by Sangxin2017** [comment]
> 中文文档么？
中文编码，希望可以传输中文

**Comment by donghengqaz** [comment]
你要怎么传输中文，传到那里去？

**Comment by Sangxin2017** [comment]
> 你要怎么传输中文，传到那里去？
比如当我请求服务器的天气信息的时候，其中包含了中文字符，获取后经过串口输出就是乱码，怎么解决这个问题?

**Comment by Flymachine** [comment]
这是编码的问题，一般的串口程序和调试工具都是GB2313这种，而不是UTF8。而网页端为了兼容性，一般是UTF8的，你可以保留一份常用字库，把UTF8转成GB2312这种


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 萌萌哒技术小组 <notifications@github.com>
发送时间: 2019年8月2日 21:56
收件人: espressif/ESP8266_RTOS_SDK <ESP8266_RTOS_SDK@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[espressif/ESP8266_RTOS_SDK] 怎让让esp8266支持中文? (GIT8266O-229) (#665)



 
你要怎么传输中文，传到那里去？
 比如当我请求服务器的天气信息的时候，其中包含了中文字符，获取后经过串口输出就是乱码，怎么解决这个问题?

**Comment by Flymachine** [comment]
也可以直接让服务器发送GB2312编码的中文字符。




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 萌萌哒技术小组 <notifications@github.com>
发送时间: 2019年8月2日 21:56
收件人: espressif/ESP8266_RTOS_SDK <ESP8266_RTOS_SDK@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[espressif/ESP8266_RTOS_SDK] 怎让让esp8266支持中文? (GIT8266O-229) (#665)



 
你要怎么传输中文，传到那里去？
 比如当我请求服务器的天气信息的时候，其中包含了中文字符，获取后经过串口输出就是乱码，怎么解决这个问题?

**Comment by Sangxin2017** [comment]
如果我把中文写进bin文件中那会是什么编码呢

**Comment by Sangxin2017** [comment]
我把源代码文件转换成GB2312格式，然后编译成固件刷进去后，使用普通的GB2312串口调试助手成功输出中文，感谢各位的帮助。

**Comment by Flymachine** [comment]
你拿个十六进制编辑器设置好编码然后打开bin看看就知道了，字面量都是静态的。


会编译成什么编码主要看你编译选项怎么写的了。一般默认的都是GB2312，但也不排除有用UTF-8的。所以说比较麻烦。


C++新版出了u8关键字，专门标识一个字面量是UTF-8编码的，算是解决了这个标识不清的问题。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 萌萌哒技术小组 <notifications@github.com>
发送时间: 2019年8月3日 18:27
收件人: espressif/ESP8266_RTOS_SDK <ESP8266_RTOS_SDK@noreply.github.com>
抄送: Flymachine <1473152048@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[espressif/ESP8266_RTOS_SDK] 怎让让esp8266支持中文? (GIT8266O-229) (#665)




如果我把中文写进bin文件中那会是什么编码呢

**Comment by EaonL** [comment]
同遇到这个问题，我希望编译器最终生成执行镜像 *.bin的时候，以utf-8编码中文字符串，而不是GB2312，How can I do it？
