### ISSUE TITLE
IP报文丢包，导致DHCP获取IP变慢 (GIT8266O-232)

### ISSUE THREAD

**Issue by JunboFei** [espressif/ESP8266_RTOS_SDK#668]
使用release-v3.1版本

esp8266侧使用DHCP获取IP地址，第一个Discover报文发出去后，没有收到Offer报文（可以确认DHCP Sever已经发出Offer报文），2秒超时后再次发送Discover报文，Offer报文接收正常。

路由器侧mac和ip绑定

日志如下：

esp8266侧：
dhcp_start(netif=0x40108124) en0
dhcp_start(): mallocing new DHCP client
dhcp_start(): allocated dhcpdhcp_start(): starting DHCP configuration
udp_bind(ipaddr = 0.0.0.0, port = 68)
udp_bind: bound to 0.0.0.0, port 68)
udp_connect: connected to 0.0.0.0, port 67)
dhcp_discover()
transaction id xid(f1e82121)
dhcp_discover: making request
dhcp_discover: realloc()ing
dhcp_discover: sendto(DISCOVER, IP_ADDR_BROADCAST, DHCP_SERVER_PORT)
udp_send: added header in given pbuf 0x3fff6f58
udp_send: sending datagram of length 316
udp_send: UDP packet length 316
udp_send: UDP checksum 0x3e56
udp_send: ip_output_if (,,,,0x11,)
ip4_output_if: en0
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       336     | (v, hl, tos, len)
+-------------------------------+
|        0      |000|       0   | (id, flags, offset)
+-------------------------------+
|  255  |   17  |    0xba9d     | (ttl, proto, chksum)
+-------------------------------+
|    0  |    0  |    0  |    0  | (src)
+-------------------------------+
|  255  |  255  |  255  |  255  | (dest)
+-------------------------------+
ip4_output_if: call netif->output()
dhcp_discover: deleting()ing
dhcp_discover: SELECTING
dhcp_discover(): set request timeout 2000 msecs
[event_handler.246:11050]: SYSTEM_EVENT_STA_CONNECTED

ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
ip4_input: UDP packet to DHCP client port 1900
ip4_input: packet not for us.
dhcp_fine_tmr(): request timeout
dhcp_timeout()
dhcp_timeout(): restarting discovery
dhcp_discover()
transaction id xid(f1e82121)
dhcp_discover: making request
dhcp_discover: realloc()ing
dhcp_discover: sendto(DISCOVER, IP_ADDR_BROADCAST, DHCP_SERVER_PORT)
udp_send: added header in given pbuf 0x3fff6f58
udp_send: sending datagram of length 316
udp_send: UDP packet length 316
udp_send: UDP checksum 0x3e56
udp_send: ip_output_if (,,,,0x11,)
ip4_output_if: en0
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       336     | (v, hl, tos, len)
+-------------------------------+
|        1      |000|       0   | (id, flags, offset)
+-------------------------------+
|  255  |   17  |    0xba9c     | (ttl, proto, chksum)
+-------------------------------+
|    0  |    0  |    0  |    0  | (src)
+-------------------------------+
|  255  |  255  |  255  |  255  | (dest)
+-------------------------------+
ip4_output_if: call netif->output()
dhcp_discover: deleting()ing
dhcp_discover: SELECTING
dhcp_discover(): set request timeout 4000 msecs
ip_input: iphdr->dest 0x47ca8c0 netif->ip_addr 0x0 (0x0, 0x0, 0x47ca8c0)
ip4_input: UDP packet to DHCP client port 68
ip4_input: DHCP packet accepted.
ip4_input: 
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       328     | (v, hl, tos, len)
+-------------------------------+
|    58998      |000|       0   | (id, flags, offset)
+-------------------------------+
|  128  |   17  |    0xd9d7     | (ttl, proto, chksum)
+-------------------------------+
|  192  |  168  |  124  |    1  | (src)
+-------------------------------+
|  192  |  168  |  124  |    4  | (dest)
+-------------------------------+
ip4_input: p->len 328 p->tot_len 328
udp_input: received datagram of length 308
UDP header:
+-------------------------------+
|        67     |        68     | (src port, dest port)
+-------------------------------+
|       308     |     0xb7b8    | (len, chksum)
+-------------------------------+
udp (192.168.124.4, 68) <-- (192.168.124.1, 67)
pcb (0.0.0.0, 68) <-- (0.0.0.0, 67)
udp_input: calculating checksum
dhcp_recv(pbuf = 0x40108200) from DHCP server 192.168.124.1 port 67
pbuf->len = 300
pbuf->tot_len = 300
searching DHCP_OPTION_MESSAGE_TYPE
DHCP_OFFER received in DHCP_STATE_SELECTING state
dhcp_handle_offer(netif=0x40108124) en0
dhcp_handle_offer(): server 0x017ca8c0
dhcp_handle_offer(): offer for 0x047ca8c0
dhcp_select(netif=0x40108124) en0
transaction id xid(f1e82121)
udp_send: added header in given pbuf 0x3fff6f58
udp_send: sending datagram of length 316
udp_send: UDP packet length 316
udp_send: UDP checksum 0x7c8f
udp_send: ip_output_if (,,,,0x11,)
ip4_output_if: en0
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       336     | (v, hl, tos, len)
+-------------------------------+
|        2      |000|       0   | (id, flags, offset)
+-------------------------------+
|  255  |   17  |    0xba9b     | (ttl, proto, chksum)
+-------------------------------+
|    0  |    0  |    0  |    0  | (src)
+-------------------------------+
|  255  |  255  |  255  |  255  | (dest)
+-------------------------------+
ip4_output_if: call netif->output()
dhcp_select: REQUESTING
dhcp_select(): set request timeout 2000 msecs
ip_input: iphdr->dest 0x47ca8c0 netif->ip_addr 0x0 (0x0, 0x0, 0x47ca8c0)
ip4_input: UDP packet to DHCP client port 68
ip4_input: DHCP packet accepted.
ip4_input: 
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       328     | (v, hl, tos, len)
+-------------------------------+
|    59007      |000|       0   | (id, flags, offset)
+-------------------------------+
|  128  |   17  |    0xd9ce     | (ttl, proto, chksum)
+-------------------------------+
|  192  |  168  |  124  |    1  | (src)
+-------------------------------+
|  192  |  168  |  124  |    4  | (dest)
+-------------------------------+
ip4_input: p->len 328 p->tot_len 328
udp_input: received datagram of length 308
UDP header:
+-------------------------------+
|        67     |        68     | (src port, dest port)
+-------------------------------+
|       308     |     0xb4b8    | (len, chksum)
+-------------------------------+
udp (192.168.124.4, 68) <-- (192.168.124.1, 67)
pcb (0.0.0.0, 68) <-- (0.0.0.0, 67)
udp_input: calculating checksum
dhcp_recv(pbuf = 0x40108200) from DHCP server 192.168.124.1 port 67
pbuf->len = 300
pbuf->tot_len = 300
searching DHCP_OPTION_MESSAGE_TYPE
DHCP_ACK received
dhcp_bind(netif=0x40108124) en0
dhcp_bind(): t0 renewal timer 86400 secs
dhcp_bind(): set request timeout 86400000 msecs
dhcp_bind(): t1 renewal timer 43200 secs
dhcp_bind(): set request timeout 43200000 msecs
dhcp_bind(): t2 rebind timer 75600 secs
dhcp_bind(): set request timeout 75600000 msecs
dhcp_bind(): IP: 0x047ca8c0 SN: 0x00ffffff GW: 0x017ca8c0
I (13936) event: sta ip: 192.168.124.4, mask: 255.255.255.0, gw: 192.168.124.1, mc_ip: 192.168.124.1

路由器侧tcpdump信息如下：
16:53:33.432004 dc:4f:22:4d:b4:90 (oui Unknown) > Broadcast, ethertype IPv4 (0x0800), length 350: 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request [|bootp]
16:53:33.465695 00:e0:0c:00:00:fd (oui Unknown) > dc:4f:22:4d:b4:90 (oui Unknown), ethertype IPv4 (0x0800), length 342: 192.168.124.1.bootps > 192.168.124.4.bootpc: BOOTP/DHCP, Reply, length 300
16:53:35.283254 dc:4f:22:4d:b4:90 (oui Unknown) > Broadcast, ethertype IPv4 (0x0800), length 350: 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request [|bootp]
16:53:35.302261 00:e0:0c:00:00:fd (oui Unknown) > dc:4f:22:4d:b4:90 (oui Unknown), ethertype IPv4 (0x0800), length 342: 192.168.124.1.bootps > 192.168.124.4.bootpc: BOOTP/DHCP, Reply, length 300
16:53:35.492539 dc:4f:22:4d:b4:90 (oui Unknown) > Broadcast, ethertype IPv4 (0x0800), length 350: 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request [|bootp]
16:53:35.509555 00:e0:0c:00:00:fd (oui Unknown) > dc:4f:22:4d:b4:90 (oui Unknown), ethertype IPv4 (0x0800), length 342: 192.168.124.1.bootps > 192.168.124.4.bootpc: BOOTP/DHCP, Reply, length 300

**Comment by donghengqaz** [comment]
我前段时间研究过这个问题，我发现路由器收到第一个 DHCP discover，但是路由器本能的不回；你可以用 master 试试，我们缩短了重传 DHCP discover 的时间来优化用户的体验。
