### ISSUE TITLE
ESP8266 : Storing different types of data in flash. (GIT8266O-234)

### ISSUE THREAD

**Issue by Yuvaraj4041** [espressif/ESP8266_RTOS_SDK#670]
## Environment

- Development Kit:       ESP8266_Devkitc_V1
- IDF version :       ESP8266_RTOS_SDK
- Development Env:      Make
- Operating System:     Windows
- Power Supply:         USB

## Problem Description

I want to store 7 fields of data in esp8266 external 2MB flash.
Can anyone help on this.
1). How to store the data in flash? 

2). which address i have to use? 

3). how to make partitions for this 7 fields? 

4). Did anyone have sample code for this?

**Comment by donghengqaz** [comment]
`external 2MB flash` is the flash which stores the running code? If it is you can perfer the [docs](https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/api-guides/partition-tables.html) that tells how to use the partition to manage user's data.

**Comment by Yuvaraj4041** [comment]
Thanks.
