### ISSUE TITLE
Missing wifi_scan_pb2.py for esp_prov.py for Soft AP Provisioning example.

### ISSUE THREAD

**Issue by VijitSingh97** [espressif/ESP8266_RTOS_SDK#671]
## Environment

- Development Kit:
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    896c93c4
- Development Env:      [Make]
- Operating System:     [Ubuntu]
- Power Supply:         [USB]

## Problem Description

I cannot try the soft ap demo.
In order to provision I need to use the /tools/esp_prov/esp_prov.py file, this file requires:
/components/wifi_provisioning/python/wifi_scan_pb2.py.

However wifi_scan_pb2.py is not in the file system.

### Expected Behavior
I can complete the provision demo

### Actual Behavior
Error for missing file, see debug bellow

### Steps to repropduce

1. cd examples/provisioning/softap_prov
2. make -j4 flash monitor
3. (using laptop that esp8266 is connected to) connect to esp8266 AP PROV_1234
4. (In new terminal) python esp_prov.py --ssid myssid --passphrase mypassword --sec_ver 1 --pop abcd1234 --transport softap --softap_endpoint 192.168.4.1:80

### Code to reproduce this issue
No code is modified in the library

## Debug Logs

```
vijit@vijit-Inspiron-13-5378:~/esp/ESP8266_RTOS_SDK/tools/esp_prov$ python esp_prov.py --ssid myssid --passphrase mypassword --sec_ver 1 --pop abcd1234 --transport softap --softap_endpoint 192.168.4.1:80
Traceback (most recent call last):
  File "esp_prov.py", line 29, in <module>
    import security
  File "/home/vijit/Dropbox/esp/ESP8266_RTOS_SDK/tools/esp_prov/security/__init__.py", line 16, in <module>
    from .security0 import *  # noqa: F403, F401
  File "/home/vijit/Dropbox/esp/ESP8266_RTOS_SDK/tools/esp_prov/security/security0.py", line 22, in <module>
    import proto
  File "/home/vijit/Dropbox/esp/ESP8266_RTOS_SDK/tools/esp_prov/proto/__init__.py", line 40, in <module>
    wifi_scan_pb2      = _load_source("wifi_scan_pb2",      idf_path + "/components/wifi_provisioning/python/wifi_scan_pb2.py")
  File "/home/vijit/Dropbox/esp/ESP8266_RTOS_SDK/tools/esp_prov/proto/__init__.py", line 26, in _load_source
    return imp.load_source(name, path)
IOError: [Errno 2] No such file or directory
```

**Comment by jhubbardsf** [comment]
If anybody else gets this issue. The fix is just to copy the contents from https://github.com/espressif/esp-idf/blob/master/components/wifi_provisioning/python/wifi_scan_pb2.py into the ESP8266_RTOS_SDK/components/wifi_provisioning/python/ directory. The esp_prov tool works then. If I have time tonight I'll submit a pull request to fix this issue.
