### ISSUE TITLE
Is MESH support removed for latest RTOS SDK 2.0.0 version? (GIT8266O-237)

### ISSUE THREAD

**Issue by hetalpanara** [espressif/ESP8266_RTOS_SDK#673]
As I see in the release notes, Mesh support removed.
Mesh support is not there for RTOS SDK 2.0.0.0 version?
What is the best version I should use for creating mesh network?

**Comment by FayeY** [comment]
Hi, so sorry that ESP8266 does not support mesh for now. 
But ESP32 does.
You can get the ESP32 mesh from https://github.com/espressif/esp-mdf.
Thanks.
