### ISSUE TITLE
Connecting E-Paper display via SPI causes boot problems (GIT8266O-241)

### ISSUE THREAD

**Issue by tbitowt** [espressif/ESP8266_RTOS_SDK#677]
Hi, I'm having problems with connecting E-Paper display via SPI interface.

The problem seems to be a GPIO15 (HSPI CS pin). When I'm connecting a display to mentioned pin my NodeMCU ESP8266 board seems to have boot problems.

I have checked this display with Arduino libraries and seems that if I connect CS to another GPIO everything is working fine. 

Seems that ```spi_interface_t``` does only contains information about enabling/disabling CS, but there's no way of changing it.

So the quesion is: How do I select which PIN do I use for CS? Or how can I fix boot problems with SPI CS pin connected to GPIO15?

**Comment by berkutta** [comment]
Try a pull down on GPIO15, it must be low for booting.
