### ISSUE TITLE
3.2版本make menuconfig打开SPIFFS模块后编译不过 (GIT8266O-243)

### ISSUE THREAD

**Issue by xizonghu** [espressif/ESP8266_RTOS_SDK#679]
CC build/coap/port/coap_io_socket.o
D:/espressif/ESP8266_RTOS_SDK-3.2/components/coap/port/coap_io_socket.c: In function 'coap_new_endpoint':
D:/espressif/ESP8266_RTOS_SDK-3.2/components/coap/port/coap_io_socket.c:162:5: error: implicit declaration of function 'close' [-Werror=implicit-function-declaration]
     close (sockfd);
     ^
cc1.exe: some warnings being treated as errors

**Comment by donghengqaz** [comment]
你可以试试 release/v3.2，上面修复一些编译问题。
