### ISSUE TITLE
搭建esp8266_rtos环境时，make monitor总是出错 (GIT8266O-245)

### ISSUE THREAD

**Issue by kindemon** [espressif/ESP8266_RTOS_SDK#681]
我在学习搭建RTOS的环境，这是在make flash已经完成的情况下进行的make monitor，试了好几次都是这个结果，小白实在是不懂，恳请各位大佬帮忙。
出错代码如下
MONITOR
winpty: error: cannot start 'G:/ESP8266/msys32/home/ESP8266_RTOS_SDK/tools/idf_monitor .py --baud 74880 --port COM3 --toolchain-prefix xtensa-lx106-elf- --make make G:/ESP8266/msys32/home/ESP8266_RTOS_SDK/myPro/helloworld/build/project_template.elf ' :%1 不是有效的 Win32
make: **** [/home/ESP8266_RTOS_SDK/components/esptool_py/Makefile.projbuild:117: monitor]错误1

**Comment by donghengqaz** [comment]
`%1 不是有效的 Win32`这个意思应该是说你运行的不是 windows 32 位上面的程序，你用的 `xtensa-lx106-elf` 是不是 windows 上面的程序呢？

**Comment by FayeY** [comment]
由于长时间无更新，此问题暂时关闭。如果有需要，欢迎 reopen issue 继续讨论。谢谢！
