### ISSUE TITLE
你好，toolchain setup中提供的下载链接是不是有些问题，下载的压缩包中没有xtensa-lx106-elf 。 (GIT8266O-249)

### ISSUE THREAD

**Issue by xiaoLBGitHub** [espressif/ESP8266_RTOS_SDK#685]
在按照文档的方法建立工程的时候会报错：make：xtensa-lx106-elf-gcc：命令未找到。检查文件发现在 opt/目录下只有xtensa-esp32-elf 文件夹，是不是缺少了xtensa-lx106-elf文件？

**Comment by 27-301** [comment]
请按照首页 README 中的链接下载对应平台的 toolchain，并解压到 /opt 目录，并在 PATH 中添加路径。

**Comment by ustccw** [comment]
@xiaoLBGitHub 请问问题是否解决？

**Comment by xiaoLBGitHub** [comment]
> 请按照首页 README 中的链接下载对应平台的 toolchain，并解压到 /opt 目录，并在 PATH 中添加路径。

谢谢

**Comment by xiaoLBGitHub** [comment]
> @xiaoLBGitHub 请问问题是否解决？

解决了
