### ISSUE TITLE
你好，我该怎么精简编译后的bin固件包大小 (GIT8266O-253)

### ISSUE THREAD

**Issue by fzboffice** [espressif/ESP8266_RTOS_SDK#688]
请问是不是没用到组件文件夹下的一些组件，编译时不会把他们编译进去呢，如果全部都会编译进去，我该用什么方法精简呢

**Comment by Fonger** [comment]
make menuconfig 底下有一個 Compiler Options 進去啟用 Release (-Os) 優化 沒用到的 code 不會編進去 大小會少些

![image](https://user-images.githubusercontent.com/5862369/64492635-7c1b1880-d2a8-11e9-84bb-7b0d38171a0a.png)
