### ISSUE TITLE
如何设置ESP8266的Uart1作为log输出接口 (GIT8266O-254)

### ISSUE THREAD

**Issue by liangyingy** [espressif/ESP8266_RTOS_SDK#689]
sdk：ESP8266_RTOS_SDK  release/v3.2

有一个文档里面说可以使用UART_SetPrintPort(UART1);，设置uart1为log输出接口，可是sdk里面没有这个函数接口。

请问设置ESP8266的Uart1作为log输出接口，应该如何做？

**Comment by ustccw** [comment]
@liangyingy `make menuconfig` -> `Component config` -> `ESP8266-specific` -> `UART for console output` 中配置
