### ISSUE TITLE
如何减小SSL引入后对内存的开销？ (GIT8266O-257)

### ISSUE THREAD

**Issue by yuguitao** [espressif/ESP8266_RTOS_SDK#692]
SDK版本3.2，由于应用开启了SSL的功能，导致内存吃紧。 关于SSL，如何配置和使用才能减少对内存的消耗？

**Comment by KNpTrue** [comment]
相比mbedtls, wolfssl的开销更少，你可以尝试使用wolfssl

**Comment by 27-301** [comment]
可以通过 menuconfig 选择使用 wolfssl，ssl 接口建议使用 esp-tls。
