### ISSUE TITLE
os_timer and esp_timer  no longer works in master branch (release/v3.2 works) (GIT8266O-258)

### ISSUE THREAD

**Issue by Fonger** [espressif/ESP8266_RTOS_SDK#693]
## Environment

- Development Kit:
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    cafe4468
- Development Env:      Make
- Operating System:     Ubuntu
- Power Supply:         USB

## Problem Description

`os_timer_setfn` `os_timer_setarm`
no longer  work in master branch. It works in release/v3.2 branch.
在 master 下沒作用了，但在 release/v3.2 branch 下正常

### Expected Behavior
It should work.

### Actual Behavior
It compiles but it doesn't work.

### Code to reproduce this issue

```cpp
#include "esp_log.h"

static void timer_func(void *arg) {
  printf("hello world!\n");
}
os_timer_t timer;
void app_main()
{
        os_timer_setfn(&timer, timer_func, NULL);
        os_timer_arm(&timer, 1000, 1);
}

```

esp_timer doesn't work either.

```cpp
#include "esp_timer.h"
#include "ets_sys.h"
static void timer_func(void *arg)
{
    printf("hello world!\n");
}
esp_timer_handle_t timer;
esp_timer_create_args_t timer_args = {.callback = timer_func, .arg = NULL, .dispatch_method = ESP_TIMER_TASK, .name = "test timer"};
void app_main()
{
    esp_timer_create(&timer_args, &timer);
    esp_timer_start_periodic(timer, 1000);
}
```

另外想問一下以下問題：

# 1. What's the difference between os_timer and esp_timer?
`os_timer` 和 `esp_timer` 有什麼不同？這兩個應該都是軟件時鐘吧？
These 2 timers are software timer, right?

# 2. missing frc2 definition in timer_struct.h
esp8266應該有兩個hardware timer: frc1, frc2
hw_timer 使用了 frc1 不過因為call overhead 太高
我是透過 timer_struct.h 的 `frc1.ctrl.en = 1` 直接去操作 timer
因為這樣 overhead 比較小 才能在interrupt handler以最短的時間準確操縱紅外線
(我寫了一個紅外 component [ESP8266-RTOS-IR](https://github.com/Fonger/ESP8266-RTOS-IR))

雖然上面還沒有 frc2 struct 的定義 但 timer_register.h 有 frc2 所在的地址
但 frc2 似乎還沒有對應的接口？

# 3. PWM MacTimer vs FRC1 vs FRC2
pwm 中code用到的 MacTimer 又是什麼？我在用 frc1 時會和 pwm 產生干擾嗎
這種情況下要用到第二個硬件時鐘是不是需要 frc2 來解決?
Does PWM conflict with frc1? what is MacTimer used in pwm code? is it equivalent to frc1?

# 4. RTOS Timer
FreeRTOS 的 xTimerCreate 又是用何種方式實現的呢？在 RTOS 下，軟體時鐘、毫秒等級的 timer 是否用 RTOS 的方法較好？
What is the implementation of FreeRTOS Timer? Should I use FreeRTOS timer instead if I need millisecond precision software timer?

# 5. Get current time
esp_get_time() us precision: uint32 這個超時會歸零嗎?
esp_timer_get_time() ms precision: int64

esp_get_time() 沒有定義 要自己定義
是否可以將此定義放在某個 header 文件內 讓 auto completion works?
Can you define esp_get_time() in some header so that auto completion in IDE works? I don't want to declare extern esp_get_time() myself.

# 6. os_delay_us vs ets_delay_us

這兩個應該都是 busy wait delay，有什麼不一樣的地方嗎?
如果用這兩個，delay過程中可能正常觸發 task switch 嗎?
delay 過程是否也會影響到 FRC1 FRC2的運作？

These 2 functions should be busy wait delay, right?
During delay, is it possible to trigger task switch? Will the delay affect the function of FRC1 FRC2 interrupt?

**Comment by Fonger** [comment]
Edit: it works now but I have the same questions.

**Comment by zheyuejiang** [comment]
最近在尝试RTOS V3.3，发现系统时间不准，使用的是esp_timer_get_time().现在想使用esp_get_time()，但是无法找到这个函数，请问怎么使用？
