### ISSUE TITLE
websocket (GIT8266O-261)

### ISSUE THREAD

**Issue by GarMingLi** [espressif/ESP8266_RTOS_SDK#696]
能不能提供websocket的功能？

**Comment by ustccw** [comment]
@GarMingLi 在 `esp-idf` 平台已经有 [websocket](https://github.com/espressif/esp-idf/tree/master/components/esp_websocket_client), `ESP8266_RTOS_SDK` 后续版本也将讨论是否有必要移植过来.

当前建议您从 `esp-idf` 上自己移植过来使用。
