### ISSUE TITLE
lost .......................wolfssl/wolfcrypt/memory.h (GIT8266O-295)

### ISSUE THREAD

**Issue by cqwuxiaolong** [espressif/ESP8266_RTOS_SDK#710]
{
	"resource": "/home/+++/esp/ESP8266_RTOS_SDK/examples/protocols/openssl_server/main/openssl_server_example_main.c",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "1696",
	"severity": 8,
	"message": "cannot open source file \"wolfssl/wolfcrypt/memory.h\" (dependency of \"wolfssl/wolfcrypt/ecc.h\")",
	"source": "C/C++",
	"startLineNumber": 30,
	"startColumn": 1,
	"endLineNumber": 30,
	"endColumn": 35
}

**Comment by ustccw** [comment]
@cqwuxiaolong it is recommended that use `esp-tls` instead of `wolfssl`.
you could take a look at `examples/protocols/https_request`.
