### ISSUE TITLE
cJSON cJSON_AddNumberToObject return null in the version 1.7.12? 更新了master分支，发现cjson创建出错；

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_RTOS_SDK#712]
## Environment

- Development Kit:
- IDF version: v3.2-186-g5369164c
- Development Env:     Make
- Operating System:     Windows
- Power Supply:         USB

## Problem Description

cJSON cJSON_AddNumberToObject return null in the version 1.7.12 ?  

更新了master分支，发现cjson创建出错；

### Code to reproduce this issue  代码

```cpp

void app_main()
{

     ESP_LOGI(TAG, "cJSON_Version() : %s", cJSON_Version());

     int hexPost[3] = {168, 189, 965};
     cJSON *pRoot = cJSON_CreateObject();

    cJSON_AddNumberToObject(pRoot, "fw", 1);
    cJSON_AddItemToObject(pRoot, "data", cJSON_CreateIntArray(hexPost, 3));

    char *s = cJSON_Print(pRoot);

    ESP_LOGI(TAG, " cJSON_Print : %s", s);

    cJSON_free((void *)s);
    cJSON_Delete(pRoot);
}

```

## Debug Logs 日志

```
I (465068) xAirKiss: cJSON_Version() : 1.7.12
I (465068) xAirKiss: cJSON_Print : <null>

```

**Comment by ustccw** [comment]
@xuhongv 看起来修改了 `newlib`, 请确认一下 `make menuconfig`-> `Component config` -> `newlib`

默认配置应为 `float nano`

**Comment by xuhongv** [comment]
- 好的

**Comment by Alanscut** [comment]
@xuhongv 请问最后这个问题解决了吗？是否是cJSON的问题呢？

**Comment by donghengqaz** [comment]
v3.2 的 cjson 里面我填了对数字编码的支持，即使使用 nano 模式的 newlib 也没有问题；master 上面由于使用了新的 cjson，所以没有这个功能，你可以选择 nano float/normal 模式的 newlib。

**Comment by zheyuejiang** [comment]
> v3.2 的 cjson 里面我填了对数字编码的支持，即使使用 nano 模式的 newlib 也没有问题；master 上面由于使用了新的 cjson，所以没有这个功能，你可以选择 nano float/normal 模式的 newlib。

cool!!!!!!!! thanks
