### ISSUE TITLE
Native OTA and simple OTA (GIT8266O-298)

### ISSUE THREAD

**Issue by Dipendra77** [espressif/ESP8266_RTOS_SDK#713]
Hi,
Can anyone tell me the differences between native OTA and simple OTA support for ESP8266 and in what context of Over the Air upgrade are they used ? I just want to upgrade the firmware on the device with a new binary file?  which one should I opt for ?

Thank you in advance.

**Comment by xuhongv** [comment]
simple OTA maybe is the best for you

**Comment by ustccw** [comment]
@Dipendra77 please take a look at pinned issue if you are interested in `native OTA`:
https://github.com/espressif/ESP8266_RTOS_SDK/issues/489

In short, you only need to care about `simple OTA` if you set up your projects after SDK version `3.x`

**Comment by Dipendra77** [comment]
> simple OTA maybe is the best for you

Can you please explain the difference ? On what basis should we decide whether to goo with simple ota or native ota?

**Comment by 27-301** [comment]
native ota may need to use the esp_ota, partition, http, etc. API directly, but simple ota does a wrap, so you can just call esp_https_ota, it's simple.
