### ISSUE TITLE
请问用C++的语法可以正常编译吗，我编译失败了 (GIT8266O-302)

### ISSUE THREAD

**Issue by fzboffice** [espressif/ESP8266_RTOS_SDK#718]

**Comment by ustccw** [comment]
@fzboffice 可以的. 请参考 `components/nvs_flash/src`

**Comment by donghengqaz** [comment]
SDK 里面的 nvs_flash 就是用的 c++ 写的，所以编译应该没有问题，但是有些 C++ 标准库里面的头文件和库文件不一定全，你可以把编译失败的 log 发上来看看。
