### ISSUE TITLE
请问AP模式下 最高被连接数是4，能否突破这个上限

### ISSUE THREAD

**Issue by fzboffice** [espressif/ESP8266_RTOS_SDK#726]
请问AP模式下 最高被连接数是4，能否突破这个上限

**Comment by ustccw** [comment]
@fzboffice 请试一下, 在初始化 `softAP` 时, 设置 `max_connection`.
定义在  `components/esp8266/include/esp_wifi_types.h` : `wifi_ap_config_t`
