### ISSUE TITLE
请问，如何启动light sleep 模式，有的话，麻烦提供一个例程，谢谢！！

### ISSUE THREAD

**Issue by AmasakaXino** [espressif/ESP8266_RTOS_SDK#731]

**Comment by AmasakaXino** [comment]
第一次涉及ESP8266 RTOS SDK的二次开发，对整个工程的API函数并不是特别了解，请大家提供一个简单的light sleep例程，以供参考

**Comment by donghengqaz** [comment]
```
#include "esp_sleep.h"

esp_wifi_set_ps(WIFI_LIGHT_SLEEP_T);
```

我们近期会添加一个 light sleep 的 example 用于简述用法和特性。

**Comment by FayeY** [comment]
/Users/yufei/Library/Containers/com.tencent.WeWorkMac/Data/Library/Application Support/WXWork/Data/1688853265588210/Cache/Image/2019-10/1085c81c-d5aa-4e8b-a557-db187d25ce28.jpg

**Comment by FayeY** [comment]
https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/wifi/power_save
