### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by fzboffice** [espressif/ESP8266_RTOS_SDK#735]
建议把IDF_PATH用另一个名字代替，因为esp32和esp8266同时开发时，环境变量会冲突

**Comment by donghengqaz** [comment]
很多客户已经基于这个环境变量开发了，所以直接修改会影响很多客户，但是我可以改成如下的操作流程：
1. 如果有配置变量 ESP8266_IDF_PATH，则在脚本内重设 IDF_PATH
2. 如果没有配置 ESP8266_IDF_PATH，就使用 IDF_PATH
3. 如果都没有就报错
