### ISSUE TITLE
请问i2c IO扩展芯片 按键问题

### ISSUE THREAD

**Issue by sonwa** [espressif/ESP8266_RTOS_SDK#738]
使用8266 gpio做按键可以用gpio_config_t设置，但请问如果是通过i2c加的IO扩展芯片，里边有三个IO0，1，2对应三个按键。对应官网这个例子“ESP8266_RTOS_SDK/examples/peripherals/gpio/main/user_main.c”，我要怎样设置才能让这个扩展的按键按下去有对应的按键回应？

**Comment by xiongyumail** [comment]
@sonwa 请联系IO扩展芯片供应商提供使用方式。
