### ISSUE TITLE
Bugs / problem in ESP8266_RTOS_SDK  v3.2    /examples/wifi/simple_wifi  program in AP mode

### ISSUE THREAD

**Issue by sajan-p-jose** [espressif/ESP8266_RTOS_SDK#741]
## Environment

- Development Kit:
- IDF version (RTOS_SDK  v3.2): 
    //bd6ea4393c7d2f059fc4decc70f1ec3eb3597268
- Development Env:     Make
- Operating System:    Ubuntu
- Power Supply:        external 3.3V

## Problem Description
AP mode Wifi not connecting, program not stable , restarting
Compiled ESP8266_RTOS_SDK  v3.2    /examples/wifi/simple_wifi  sample program from SDK but it is not working properly
problem can't detect from console log

### Expected Behavior
Wifi connection in AP mode
### Actual Behavior
Wifi not connecting , system restaring
### Steps to repropduce

1. step1
Compile and run ESP8266 IDF V3.2  /examples/wifi/simple-example program
without any modifications 

// It helps if you attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
/* Simple WiFi Example

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "rom/ets_sys.h"
#include "esp_wifi.h"
#include "esp_event_loop.h"
#include "esp_log.h"
#include "nvs_flash.h"

/* The examples use simple WiFi configuration that you can set via
   'make menuconfig'.

   If you'd rather not, just change the below entries to strings with
   the config you want - ie #define EXAMPLE_WIFI_SSID "mywifissid"
*/
#define EXAMPLE_ESP_WIFI_MODE_AP   CONFIG_ESP_WIFI_MODE_AP //TRUE:AP FALSE:STA
#define EXAMPLE_ESP_WIFI_SSID      CONFIG_ESP_WIFI_SSID
#define EXAMPLE_ESP_WIFI_PASS      CONFIG_ESP_WIFI_PASSWORD
#define EXAMPLE_MAX_STA_CONN       CONFIG_MAX_STA_CONN

/* FreeRTOS event group to signal when we are connected*/
static EventGroupHandle_t wifi_event_group;

/* The event group allows multiple bits for each event,
   but we only care about one event - are we connected
   to the AP with an IP? */
const int WIFI_CONNECTED_BIT = BIT0;

static const char *TAG = "simple wifi";

static esp_err_t event_handler(void *ctx, system_event_t *event)
{
    /* For accessing reason codes in case of disconnection */
    system_event_info_t *info = &event->event_info;
    
    switch(event->event_id) {
    case SYSTEM_EVENT_STA_START:
        esp_wifi_connect();
        break;
    case SYSTEM_EVENT_STA_GOT_IP:
        ESP_LOGI(TAG, "got ip:%s",
                 ip4addr_ntoa(&event->event_info.got_ip.ip_info.ip));
        xEventGroupSetBits(wifi_event_group, WIFI_CONNECTED_BIT);
        break;
    case SYSTEM_EVENT_AP_STACONNECTED:
        ESP_LOGI(TAG, "station:"MACSTR" join, AID=%d",
                 MAC2STR(event->event_info.sta_connected.mac),
                 event->event_info.sta_connected.aid);
        break;
    case SYSTEM_EVENT_AP_STADISCONNECTED:
        ESP_LOGI(TAG, "station:"MACSTR"leave, AID=%d",
                 MAC2STR(event->event_info.sta_disconnected.mac),
                 event->event_info.sta_disconnected.aid);
        break;
    case SYSTEM_EVENT_STA_DISCONNECTED:
        ESP_LOGE(TAG, "Disconnect reason : %d", info->disconnected.reason);
        if (info->disconnected.reason == WIFI_REASON_BASIC_RATE_NOT_SUPPORT) {
            /*Switch to 802.11 bgn mode */
            esp_wifi_set_protocol(ESP_IF_WIFI_STA, WIFI_PROTOCAL_11B | WIFI_PROTOCAL_11G | WIFI_PROTOCAL_11N);
        }
        esp_wifi_connect();
        xEventGroupClearBits(wifi_event_group, WIFI_CONNECTED_BIT);
        break;
    default:
        break;
    }
    return ESP_OK;
}

void wifi_init_softap()
{
    wifi_event_group = xEventGroupCreate();

    tcpip_adapter_init();
    ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL));

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
    wifi_config_t wifi_config = {
        .ap = {
            .ssid = EXAMPLE_ESP_WIFI_SSID,
            .ssid_len = strlen(EXAMPLE_ESP_WIFI_SSID),
            .password = EXAMPLE_ESP_WIFI_PASS,
            .max_connection = EXAMPLE_MAX_STA_CONN,
            .authmode = WIFI_AUTH_WPA_WPA2_PSK
        },
    };
    if (strlen(EXAMPLE_ESP_WIFI_PASS) == 0) {
        wifi_config.ap.authmode = WIFI_AUTH_OPEN;
    }

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_AP));
    ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_AP, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_start());

    ESP_LOGI(TAG, "wifi_init_softap finished.SSID:%s password:%s",
             EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS);
}

   void app_main()
{
    //Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES) {
      ESP_ERROR_CHECK(nvs_flash_erase());
      ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);
printf("\nStarting\n");

#if EXAMPLE_ESP_WIFI_MODE_AP
    ESP_LOGI(TAG, "ESP_WIFI_MODE_AP");
    wifi_init_softap();
#else
    ESP_LOGI(TAG, "ESP_WIFI_MODE_STA");
    wifi_init_sta();
#endif /*EXAMPLE_ESP_WIFI_MODE_AP*/

}
 
}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```
D (774) nvs: nvs_get ap.sndchan 1
D (779) nvs: nvs_get lorate 1
V (783) wifi: index=19 value=0x3ffe90a0 flag=1
D (787) nvs: nvs_set_blob ap.ssid 36
V (793) wifi: index=21 value=mypassword flag=1
D (797) nvs: nvs_set_blob ap.passwd 65
V (802) wifi: index=24 value=4 flag=1
D (806) nvs: nvs_set ap.authmode 1 4
V (810) wifi: index=23 value=1 flag=1
D (814) nvs: nvs_set ap.chan 1 1
V (818) wifi: index=25 value=0 flag=1
D (822) nvs: nvs_set ap.hidden 1 0
V (826) wifi: index=26 value=4 flag=1
D (830) nvs: nvs_set ap.max.conn 1 4
V (834) wifi: index=27 value=100 flag=1
D (838) nvs: nvs_set bcn.interval 2 100
I (843) wifi: mode : softAP (62:01:94:37:ba:82)
I (848) wifi: add if1
D (852) wifi: Deriving WPA PSK based on passphrase
D (858) wifi: WPA: group state machine entering state GTK_INIT (VLAN-ID 0)
D (864) wifi: WPA: group state machine entering state SETKEYSDONE (VLAN-ID 0)
«A,P1,%e¢»Í)(Hl!%y.!y¨v(p-û~1ôQèqht-·ít1R11yÐ9"!Ûo@«r«òÊI-9¨iîΦôy(rz«y«R5         ­E
D (428) nvs: nvs_open_from_partition backup_mac 0ID:myssid password:mypassword
D (435) nvs: nvs_get_str_or_blob backup_mac_data
D (441) nvs: nvs_close 1ault callback
I (446) system_api: Base MAC address is not set, read default base MAC address froE
D (456) nvs: nvs_open_from_partition backup_mac 0
D (463) nvs: nvs_get_str_or_blob backup_mac_datad_proberesp:3041)
D (469) nvs: nvs_close 2e resp
D (473) phy_init: loading PHY init data from application binary1)
D (480) nvs: nvs_open_from_partition phy 0
D (486) nvs: nvs_get_str_or_blob cal_data211_send_proberesp:3041)
D (492) nvs: nvs_get_str_or_blob dc_table
D (499) nvs: nvs_close 3_ref_node (ieee80211_send_proberesp:3041)
I (563) phy_init: phy ver: 1151_0
I (569) reset_reason: RTC reset 4 wakeup 0 store 0, reason is 7
D (577) wdt: Enable task watch dog panic, panic time parameter is 11
D (585) wdt: task watch dog trigger time parameter is 15
wdt reset
Starting0100000, len 7664, room 16 
I (593) simple wifi: ESP_WIFI_MODE_AP
D (603) nvs: nvs_open_from_partition misc 1
D (609) nvs: nvs_open_from_partition nvs.net80211 1
D (616) nvs: nvs_get opmode 1
D (621) nvs: nvs_get_str_or_blob sta.ssid
D (626) nvs: nvs_get_str_or_blob sta.mac
D (632) nvs: nvs_get sta.authmode 1
D (637) nvs: nvs_get_str_or_blob sta.pswd
D (643) nvs: nvs_get_str_or_blob sta.pmkt5ëPú~§P`n@«I-9lp×-1ôQèq¨rÊv=zª\9)QmYí e P­Ð
D (649) nvs: nvs_get sta.chan 1
D (653) nvs: nvs_get auto.conn 1
D (658) nvs: nvs_get bssid.set 1
D (663) nvs: nvs_get_str_or_blob sta.bssid
D (669) nvs: nvs_get sta.lis_intval 2
D (674) nvs: nvs_get sta.phym 1
D (679) nvs: nvs_get sta.phybw 1
D (684) nvs: nvs_get_str_or_blob sta.apsw
D (690) nvs: nvs_get_str_or_blob sta.apinfo
D (696) nvs: nvs_get sta.scan_method 1
D (702) nvs: nvs_get sta.sort_method 1
D (708) nvs: nvs_get sta.minrssi 1
D (713) nvs: nvs_get sta.minauth 1
D (718) nvs: nvs_get_str_or_blob ap.ssid
D (724) nvs: nvs_get_str_or_blob ap.mac
D (729) nvs: nvs_get_str_or_blob ap.passwd
D (735) nvs: nvs_get_str_or_blob ap.pmk
D (741) nvs: nvs_get ap.chan 1
D (746) nvs: nvs_get ap.authmode 1
D (751) nvs: nvs_get ap.hidden 1
D (756) nvs: nvs_get ap.max.conn 1
D (761) nvs: nvs_get bcn.interval 2
D (766) nvs: nvs_get ap.phym 1
D (771) nvs: nvs_get ap.phybw 1
D (775) nvs: nvs_get ap.sndchan 1
D (780) nvs: nvs_get lorate 1
V (785) wifi: index=19 value=0x3ffe90a0 flag=1
D (789) nvs: nvs_set_blob ap.ssid 36
V (794) wifi: index=21 value=mypassword flag=1
D (798) nvs: nvs_set_blob ap.passwd 65
V (804) wifi: index=24 value=4 flag=1
D (808) nvs: nvs_set ap.authmode 1 4
V (812) wifi: index=23 value=1 flag=1
D (816) nvs: nvs_set ap.chan 1 1
V (820) wifi: index=25 value=0 flag=1
D (823) nvs: nvs_set ap.hidden 1 0
V (828) wifi: index=26 value=4 flag=1
D (831) nvs: nvs_set ap.max.conn 1 4
V (836) wifi: index=27 value=100 flag=1
«A,P1,%e¢»í)(Hl!%y.!y¨v(p-û~1ôQèqht-·ít1R11yÐ9"!Ûo@«r«òÊI-9¨iÎΦôy(rz«y«r5         ­E
## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by donghengqaz** [comment]
Did you use the raw example ? If so, you can supply your sdkconfig to me, and then I will check this.

**Comment by sajan-p-jose** [comment]
Yes, Problem on raw example in 
AP mode
 sdkconfig attached

[sdkconfig.txt](https://github.com/espressif/ESP8266_RTOS_SDK/files/3789089/sdkconfig.txt)

**Comment by sajan-p-jose** [comment]
Not applicable for new version
