### ISSUE TITLE
最新SDK哪里选择划分FLASH map 类似旧版本的2mb（512+512）?

### ISSUE THREAD

**Issue by Yvan623048750** [espressif/ESP8266_RTOS_SDK#747]
还有支持OTA的flash划分  目前只知道0x10000 是app1的起始地址  app2的起始地址是多少？

**Comment by donghengqaz** [comment]
You can use patition description file [partitions_two_ota.1MB.csv](https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/partition_table/partitions_two_ota.1MB.csv)

Maybe  [OTA example](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/system/ota/native_ota/1MB_flash/new_to_new_no_old) is better.
