### ISSUE TITLE
ESP8266 rtos V3.2 使用gpio唤醒LIGHT_SLEEP问题

### ISSUE THREAD

**Issue by match101** [espressif/ESP8266_RTOS_SDK#748]
我们目前在rtos V3.2版本使用gpio唤醒LIGHT_SLEEP状态时，遇到了以下现象:
1.在睡眠状态下，按下按键后(持续低电平)，设备串口打印了一些滞后的旧信息后(一般不超过20个字符)，不再有任何打印，设备也没有被唤醒
2.继续松开按键后(恢复高电平)，设备才被正常唤醒
3.在 rtos 2.x.x版本中，一样的硬件电路板，在按键按下(持续低电平)时，直接就能被完全唤醒，全过程中不需要松开按键

但是目前我们的业务需求需要在按键按下(持续低电平)时就完全唤醒，
想问一下新版本的SDK在低功耗配置上是否有变更？有无需特别关注的地方？
能否帮我们在新版SDK上实现rtos 2.x.x版本中一样的唤醒效果？

非常感谢！

===========================================================================
进入低功耗前唤醒gpio管脚配置如下：
GPIO[0]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
即普通输入管脚，不启用中断（也尝试过启用中断的配置）

进入低功耗前操作大致如下：

        esp_wifi_disconnect();
        esp_wifi_set_mode(WIFI_MODE_NULL);

        all_timer_stop();
        vTaskDelay(300/portTICK_RATE_MS);

        esp_wifi_fpm_set_sleep_type(WIFI_LIGHT_SLEEP_T);
        esp_wifi_fpm_open();
        esp_wifi_fpm_set_wakeup_cb(cb_func);

        gpio_wakeup_enable(KEY_FUNC_PIN, GPIO_INTR_LOW_LEVEL);

        esp_wifi_fpm_do_sleep();//大约是设定200秒左右

具体版本信息：
硬件：ESP8266 esp-wroom-02
软件sdk： rtos release/v3.2分支
commit efd0a545acfacb75c726186794af0d29c684dc47
Date:   Wed Oct 23 11:19:10 2019 +0800

**Comment by donghengqaz** [comment]
I want to speak Chinese which can make our meaning more clear for us, but I want to show the discussion to some English language developers, so I am sorry I just could speak English.

I added your code to my example and tested it just now, but I did not catch your problem, I posted my code here, you may try it:

```
#include "esp_wifi.h"
#include "esp_sleep.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

static void fsleep_task(void *p)
{
    int c = 0;

    while (1) {
        esp_wifi_set_mode(WIFI_MODE_NULL);
        vTaskDelay(300/portTICK_RATE_MS);

        esp_wifi_fpm_set_sleep_type(WIFI_LIGHT_SLEEP_T);
        esp_wifi_fpm_open();
        esp_wifi_fpm_set_wakeup_cb(NULL);

        gpio_wakeup_enable(GPIO_NUM_2, GPIO_INTR_LOW_LEVEL);

        printf("1234: %u\r\n", c);

        esp_wifi_fpm_do_sleep(200 * 1000 * 1000);//大约是设定200秒左右

        printf("1234: %u\r\n", c);

        c++;
    }
}

void app_main(void)
{
    //initialise_wifi();
    xTaskCreate(&fsleep_task, "fsleep_task", 4096, NULL, 5, NULL);
}
```
