### ISSUE TITLE
make: xtensa-lx106-elf-gcc: Command not found expr: syntax error: unexpected argument ‘5.2.0’ (GIT8266O-313)

### ISSUE THREAD

**Issue by barmy-berg** [espressif/ESP8266_RTOS_SDK#754]
i am trying to run first code hello world on ESP8266 nodeMcu. i have downloaded toolchain , ESP8266_RTOS_SDK as instructed in   https://github.com/espressif/ESP8266_RTOS_SDK .

i am able to execute instruction
make menuconfig

but i am not able to compile the codes and always below message appear
make: xtensa-lx106-elf-gcc: Command not found 
expr: syntax error: unexpected argument ‘5.2.0’

i am working on windows (64 bit). i am not able to find , what is the reason for this error. 
Please help....thanks

**Comment by lasal1989** [comment]
Check this out
https://github.com/espressif/ESP8266_RTOS_SDK/issues/317
