### ISSUE TITLE
hello_world make all failed - Missing braces around initializer in ir_rx.c (GIT8266O-322)

### ISSUE THREAD

**Issue by nabeelkirmani** [espressif/ESP8266_RTOS_SDK#761]
### Environment

- **Development Kit**:        NodeMCU 1.0 (ESP-12E Module)
- **IDF version**:                7ab9602e
- **Development Env**:       Make (4.2.1-1.2)
- **Operating System**:      Debian Buster (without GUI) on Virtualbox 6.0
- **Power Supply**:             USB

### Problem Description

While executing `make all` in $IDF_PATH/examples/get-started/hello_world compilation fails.

## Expected Behavior

Should compile without errors.

## Actual Behavior

```
/home/nabeel/esp/ESP8266_RTOS_SDK/components/esp8266/driver/ir_rx.c: In function 'ir_rx_intr_handler' :
/home/nabeel/esp/ESP8266_RTOS_SDK/components/esp8266/driver/ir_rx.c:59:5: error : missing braces around initializer [-Werror=missing-braces]
           static ir_rx_nec_data_t ir_data = {0};
           ^
/home/nabeel/esp/ESP8266_RTOS_SDK/components/esp8266/driver/ir_rx.c:59:5: error: (near initialization for 'ir_data.<anonymous>') [-Werror=missing-braces]
/home/nabeel/esp/ESP8266_RTOS_SDK/components/esp8266/driver/ir_rx.c: At top level"
cc1: warning " unrecognized command line option "-Wno-frame-address" [enabled by default]
cc1: some warnings are being treated as errors
make[1]: *** [/home/user/esp/ESP8266_RTOS_SDK/make/component_wrapper.mk:292: driver/ir_rx.o] Error 1
make: *** [/home/nabeel/Development/ESP8266_RTOS_SDK/make/project.mk:571: component-esp8266-build] Error 2

```
![Capture](https://user-images.githubusercontent.com/38636337/69196088-85ddb980-0b3e-11ea-98e1-af292ca9d7df.PNG)

## Steps to reproduce

Follow the step by step instructions on **README.md** until section **Compiling the Project**, execute `make all`

**Comment by k4r4c** [comment]
Problem seems to come from initializing the union type `ir_rx_nec_data_t`.
Changing the the line `static ir_rx_nec_data_t ir_data = {0};` in ir_rx.c to the following solved the problem for me:
```
static ir_rx_nec_data_t ir_data; 
ir_data.val = 0;  
```
