### ISSUE TITLE
CPU_160M_TICKS_PRT_MS (GIT8266O-323)

### ISSUE THREAD

**Issue by WallaceWilliam** [espressif/ESP8266_RTOS_SDK#762]
in components\esp8266\include\esp8266\eagle_soc.h define 
>106 #define CPU_160M_TICKS_PRT_MS       (CPU_FREQ_160MHZ / **_FREQ_1MHZ_**)
>107 #define CPU_80M_TICKS_PRT_MS        (CPU_FREQ_80MHz / FREQ_1KHZ)
>108
>109 #define CPU_160M_TICKS_PRT_US       (CPU_FREQ_160MHZ / FREQ_1MHZ)
>110 #define CPU_80M_TICKS_PRT_US        (CPU_FREQ_80MHz / FREQ_1MHZ)

please change
>106 #define CPU_160M_TICKS_PRT_MS       (CPU_FREQ_160MHZ / **_FREQ_1KHZ_**)

**Comment by donghengqaz** [comment]
Thanks for your report, and I will fix this issue as soon as possible.
