### ISSUE TITLE
http client 内存问题 (GIT8266O-333)

### ISSUE THREAD

**Issue by LiThirteen** [espressif/ESP8266_RTOS_SDK#770]
为什么每次运行http client  post请求后，在内存上都会缺失200多个字节，因为进行了多次短连接后发现的问题，但是停止后，内存又会恢复，请问这个原因是什么呢

**Comment by LiThirteen** [comment]
调试信息
![`W0E86{7@3PALFLEDK%O6M5](https://user-images.githubusercontent.com/37564450/69843761-e5a53480-12a3-11ea-983a-08d6c6fe2248.png)

**Comment by LiThirteen** [comment]
[0;32mI (231723) At_Uart: -------------------- heap1:27932 --------------------------[0m
[0;32mI (231723) Http_Clinet_PostData: hoststr = 192.168.10.10:8080 


[0;32mI (231753) Http_Clinet_PostData: HTTP_EVENT_ON_CONNECTED[0m

[0;32mI (232063) response: HTTP_EVENT_ON_HEADER, key=Transfer-Encoding, value=chunked[0m
[0;32mI (232073) response: HTTP_EVENT_ON_HEADER, key=Date, value=Fri, 29 Nov 2019 03:52:43 
[0;32mI (232083) Http_Clinet_PostData: HTTP_EVENT_ON_DATA, len=57[0m
[0;32mI (232093) response: {"code":200,"msg":"success","response":[],"success":true}[0m
[0;32mI (232113) Http_Clinet_PostData: HTTP_EVENT_ON_FINISH[0m
[0;32mI (232113) Http_Clinet_PostData: POST url-1 Status = 200, content_length = -1[0m
repLen:58, repbuf:{"code":200,"msg":"success","response":[],"success":true}
[0;32mI (232143) Http_Clinet_PostData: HTTP_EVENT_DISCONNECTED[0m
---------------238--------------
[0;32mI (232153) At_Uart: -------------------- heap2:27772 --------------------------[0m
停止发送post请求，大约1分钟
[0;32mI (315483) At_Uart: -------------------- heap1:46132 --------------------------[0m
[0;32mI (315983) Http_Clinet_PostData: HTTP_EVENT_ON_CONNECTED[0m
[0;32mI (317223) response: HTTP_EVENT_ON_HEADER, key=Content-Type, value=application/json;charset=UTF-8[0m
[0;32mI (317233) response: HTTP_EVENT_ON_HEADER, key=Transfer-Encoding, value=chunked[0m
[0;32mI (317243) response: HTTP_EVENT_ON_HEADER, key=Date, value=Fri, 29 Nov 2019 03:54:08 GMT[0m
[0;32mI (317253) Http_Clinet_PostData: HTTP_EVENT_ON_DATA, len=57[0m
[0;32mI (317263) response: {"code":200,"msg":"success","response":[],"success":true}[0m
[0;32mI (317283) Http_Clinet_PostData: HTTP_EVENT_ON_FINISH[0m
[0;32mI (317283) Http_Clinet_PostData: POST url-1 Status = 200, content_length = -1[0m


[0;32mI (317313) Http_Clinet_PostData: HTTP_EVENT_DISCONNECTED[0m
---------------239--------------
[0;32mI (317323) At_Uart: -------------------- heap2:46372 --------------------------

**Comment by lhespress** [comment]
`因为进行了多次短连接`：每次连接断开时，处于 TIME_WAIT 状态的连接需要等待 2MSL 时间，内存才会完全回收。可以通过 setsockopt 函数，启用 SO_LINGER 选项，参考 code 如下：

```
struct linger so_linger;
so_linger.l_onoff = 1;
so_linger.l_linger = 0;
setsockopt(sock, SOL_SOCKET, SO_LINGER, &so_linger, sizeof(so_linger));
```
当调用 close 函数时，套接字 sock 会立即中止，内存会被立即回收。

**Comment by LiThirteen** [comment]
感谢您的回复，以及您的解决方案。
