### ISSUE TITLE
Factory app, two OTA definitions 复位 (GIT8266O-347)

### ISSUE THREAD

**Issue by hqchen118** [espressif/ESP8266_RTOS_SDK#783]
## Environment

- Development Kit:ESP8266_RTOS_SDK
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): v3.2
    //bd6ea4393c7d2f059fc4decc70f1ec3eb3597268
- Development Env:      Make
- Operating System:     Ubuntu
- Power Supply:         USB

## Problem Description
在SDK提供的example中，运行make menuconfig，分区表选择Factory app, two OTA definitions，编译烧写到模组，模组不停复位。
(46) boot: ESP-IDF v3.2-dirty 2nd stage bootloader
I (46) boot: compile time 15:15:06
I (48) qio_mode: Enabling default flash chip QIO
I (50) boot: SPI Speed      : 40MHz
I (54) boot: SPI Mode       : QIO
I (58) boot: SPI Flash Size : 2MB
I (62) boot: Partition Table:
I (66) boot: ## Label            Usage          Type ST Offset   Length
I (73) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (81) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (88) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (96) boot:  3 ota_0            OTA app          00 10 00010000 000f0000
I (103) boot:  4 ota_1            OTA app          00 11 00110000 000f0000
I (111) boot: End of partition table
I (115) boot: No factory image, trying OTA 0
I (120) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x31314 (2p
I (196) esp_image: segment 1: paddr=0x0004132c vaddr=0x3ffe8000 size=0x0051c ( d
I (197) esp_image: segment 2: paddr=0x00041850 vaddr=0x3ffe851c size=0x0019c ( d
I (203) esp_image: segment 3: paddr=0x000419f4 vaddr=0x40100000 size=0x05ae0 ( d
I (220) boot: Loaded app from partition at offset 0x10000
assertion "nvs_flash_init() == 0" failed: file "startup.c", line 76, function: y
E (239) ABORT: Error found and abort!

**Comment by svenbieg** [comment]
The factory-app partition is still missing and the device fails to boot. I have to use a custom partition.csv file.
