### ISSUE TITLE
Unable to set SSL fragment length

### ISSUE THREAD

**Issue by vjrantal** [espressif/ESP8266_RTOS_SDK#82]
The function to set the fragment length is not exposed via the OpenSSL compatibility layer and the set value gets overwritten by `mbed_ssl_init`.

**Comment by donghengqaz** [comment]
You can configurate it at "menu" at the new branch(v3.0 or master):

Component config
    -> SSL
        -> Choose SSL/TLS library(mbedtls)
        -> (XXXXX)TLS maximum message content length
