### ISSUE TITLE
esp_wifi_internal_tx not present in libnet80211.a (GIT8266O-391)

### ISSUE THREAD

**Issue by mauricioagurto** [espressif/ESP8266_RTOS_SDK#822]
The function int esp_wifi_internal_tx(wifi_interface_t wifi_if, void *buffer, uint16_t len); declared in components/esp8266/include/internal/esp_wifi_internal.h is not present in the binary libnet80211.a.

**Comment by Junhao-Espressif** [comment]
Please use ``` esp_err_t esp_wifi_80211_tx(wifi_interface_t ifx, const void *buffer, int len, bool en_sys_seq);``` instead of ```int esp_wifi_internal_tx(wifi_interface_t wifi_if, void *buffer, uint16_t len);``` .
