### ISSUE TITLE
spi_flash_write/spi_flash_read question

### ISSUE THREAD

**Issue by ly0** [espressif/ESP8266_RTOS_SDK#9]
it seems the function can not write data to flash.
how can i store my data to flash?

**Comment by santanurahaman** [comment]
Hi,
I have tried the above solution for the same task and Its not working. I am not getting any output the code is sucking in spin_flash_write. i am using SDK version 0.9.4 and my code is. 

Can you please help?


char temp[128];

void ICACHE_FLASH_ATTR
save_server_params(const char* serverip, const char* port)
{
	char buff[25] = {0};
	int result = -1;
	uint8 serverSize = sizeof(serverip);
	uint8 portSize = sizeof(port);
	int size = 0;
	os_sprintf(temp,"[*] Save data: ServerIP=%s|%d, Port=%s|%d\n", serverip, port, serverSize, portSize);
	ets_uart_printf(temp);

	strcpy(buff, serverip);
	strcpy(buff + 17, port);

	result = spi_flash_write(0x3C000, (uint32*) buff, 25);
	os_sprintf(temp,">> %s",buff);
	ets_uart_printf(temp);
	os_sprintf(temp,"[*] write return %d %s(%d)-%s \n", result, __FILE__, __LINE__, __FUNCTION__);
	ets_uart_printf(temp);
}

void ICACHE_FLASH_ATTR
load_server_params()
{
	char buff[25] = {0};
	int result = -1;
	char ip[16],port[5];

	result = spi_flash_read(0x3C000, (uint32*)buff, 25);
	os_printf(">> %s",buff);

	os_sprintf(temp,"[*] read result %d %s(%d)-%s \n", result, __FILE__, __LINE__, __FUNCTION__);
	ets_uart_printf(temp);
	os_sprintf(ip, "%s", buff);
	ets_uart_printf(temp);
	os_sprintf(temp,"[*] serverIP=%s success %s(%d)-%s \n", ip, __FILE__, __LINE__, __FUNCTION__);
	ets_uart_printf(temp);
	os_sprintf(port, "%s", buff + 17);
	ets_uart_printf(temp);
	os_sprintf(temp,"[*] port=%s success %s(%d)-%s \n", port, __FILE__, __LINE__, __FUNCTION__);
	ets_uart_printf(temp);
}

**Comment by ly0** [comment]
@santanurahaman 
Your buffer size should be multiples of 4 bytes, if I remember correctly..
P.S. you should post your data within \`\`\` YOUR CODES \`\`\`, it makes easy to read.

**Comment by santanurahaman** [comment]
@ly0 
Thanks for the reply.

The data is 
serverip  = 192.168.10.112
port  = 8080
