### ISSUE TITLE
Tick length is not updated if CPU is switched to 160 MHz

### ISSUE THREAD

**Issue by rojer** [espressif/ESP8266_RTOS_SDK#90]
`configTICK_RATE_HZ` is 100, implying 10 ms ticks, but it is not updated if CPU frequency is changed to 160:

```
/* ticks are 10 ms, as expected */ 
system_update_cpu_freq(SYS_CPU_160MHZ);
/* now ticks are 5 ms */
```

**Comment by FayeY** [comment]
Hi, this issue should have been solved in the latest SDK, if it is not please feel free to reopen it.
