### ISSUE TITLE
PWM causes the software to watch the door trigger (GIT8266O-473)

### ISSUE THREAD

**Issue by SmartArduino** [espressif/ESP8266_RTOS_SDK#900]
I have port
https://github.com/espressif/ESP8266_RTOS_SDK/blob/126c5cf1f5ac285dfbfe3a140b1257e7938612b2/components/esp8266/driver/pwm.c
to esp-open-rtos.
It work well. However,
Every once in a while
PWM causes the software to watch the door trigger.
Is there Function feed soft watch dog?

**Comment by nsfilho** [comment]
I can be wrong, but I believe of who feeds watchdog task is the priority (FreeRTOS). If watchdog task stalled, will cause a don't feed for watchdog, resulting in restart.

Most than the way you implement your driver, it could be how your final application is wrote (about the priority perspective). In example, if you use priority MAX or Critical, can cause that if it is running for a long time (around some milleseconds).

Again, I'm not an expert, but I'm sharing my discoveries with you.

**Comment by dsptech** [comment]
Hi, 
the watchdog clear is performed by the the esp_internal_idle_hook() function (called from the idle task) .
(see: https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/freertos/port/esp8266/port.c)

The pwm driver is software but fully NMI driven instead, so, it should not cause any problems (at output frequencies that it can manage). 

A possible problem could be that an higher priority task does not go in wait, so the idle task is not longer able to clear the watchdog.
If you could share your code, we may be able to help you.
Regards.

**Comment by SmartArduino** [comment]
This issue has been resolved because flash SPI speed
