### ISSUE TITLE
Spurious retransmissions and socket write fail

### ISSUE THREAD

**Issue by bneumann** [espressif/ESP8266_RTOS_SDK#91]
Hi,

I am trying to use the SDK v1.5. So far it looks good to me I can connect to my WIFI, open a socket and there are no errors. But as soon as I try writing to a port where my server listens the ESP returns `ERRNO 103` which is (I think) `103 = Software caused connection abort`.

Here is the wireshark capture I made betwwen my server and the ESP. It looks like the ESP is not answering the the ACK of my server. 

[spurious_retransmission_port45657.zip](https://github.com/espressif/ESP8266_RTOS_SDK/files/833628/spurious_retransmission_port45657.zip)

I tried running servers on different systems but it doesn't matter if it is a linux or windows PC. The firewall settings are all correct and other clients can connect flawlessly.

Here is a gist of my [user_main.c](https://gist.github.com/bneumann/8ea9982badb2962c93aa96456704488c). The failing function is
```c
void ICACHE_FLASH_ATTR sendData(char *data)
{
	if (write(gsServerSocket, data, strlen(data)) < 0) {
		printf("C > send fail, error: %d\n", errno);
	}

	printf("C > send success\n");
}
```
The gServerCocket cannot be empty because the function can only be called if the socket connection has been established. 

And here is also the [UART log](https://gist.github.com/bneumann/22ffee1ff7cc0061aea51ff8b494770f) where I print the error code.

So my question is: Am I doing something wrong? I figured that I sometimes can write to a socket if I set the ESP in SoftAP+Station mode. But this is not what I want. Also it sometimes work if I spray the chip with coolant spray (Because I can you know) so maybe I am not using some magic calibration file or something.

**Comment by FayeY** [comment]
Hi, this issue should have been solved in the latest SDK, if it is not please feel free to reopen it.
