### ISSUE TITLE
v3.3 : where are the rtc_mem_read and rtc_mem_write functions ? (GIT8266O-488)

### ISSUE THREAD

**Issue by bonnefoi** [espressif/ESP8266_RTOS_SDK#915]
## Environment

- Development Kit:
- IDF version 54deb7b9
- Development Env:      vim/make
- Operating System:     Ubuntu
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description

Where are the ```rtc_mem_read``` and ```rtc_mem_write``` functions ?

**Comment by bonnefoi** [comment]
Helllo, this is exactly what I want !

I've tried your syntax : 
```
/portal.c:42:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'RTC_NOINIT_ATTR'
 uint32_t rtcStorage RTC_NOINIT_ATTR;
```

I've tried this syntax :
```
static RTC_NOINIT_ATTR uint32_t reset_count=0;
```
And the compiler gives me:
```
/portal.c:41:8: error: unknown type name 'RTC_NOINIT_ATTR'
 static RTC_NOINIT_ATTR uint32_t reset_count=0;
```
I use this version of the toolchain:
```
Toolchain version: crosstool-ng-1.22.0-100-ge567ec7
Compiler version: 5.2.0
```
Any ideas ?

**Comment by bonnefoi** [comment]
Finally, that works !
You have to manually add to the file ```esp_attr.h```, the following lines:
```
// Forces data into noinit section to avoid initialization after restart.
#define __NOINIT_ATTR _SECTION_ATTR_IMPL(".noinit", __COUNTER__)

// Forces data into RTC slow memory of .noinit section.
// Any variable marked with this attribute will keep its value
// after restart or during a deep sleep / wake cycle.
#define RTC_NOINIT_ATTR  _SECTION_ATTR_IMPL(".rtc_noinit", __COUNTER__)
```
and now the ESP8266 remembers some data between reset !

Thanks for your help !

**Comment by dsptech** [comment]
Hi @bonnefoi ,
I noticed now that you was asking about the v3.3. 
The v3.3 has not support for the NOINIT feature.  Before change the esp_attr header, you need to make sure the proper support by the linker, otherwise you may experience unwanted behaviors.
Regards.

**Comment by bonnefoi** [comment]
Hello,

You're right.

I've made the modifications because the linker knows about it:
```
components/esp8266/ld/esp8266.project.ld.in:     User data marked with RTC_NOINIT_ATTR will be placed
```

This is the information that lead me to modify the ``esp_attr.h``` file.

Thank you again,
Pierre-François.
