### ISSUE TITLE
Choice of passive/active wifi scanning

### ISSUE THREAD

**Issue by Dake01** [espressif/ESP8266_RTOS_SDK#95]
Hello,

Recently, the choice of Wifi scanning had been added on the esp32 (https://github.com/espressif/esp-idf/commit/c690447dd9abbcb805c7c4c2fb5a89d9296372e2). I am looking for is it technically possible to add this functionality on the architecture esp8266 ? If it is compliant, is the functionality expected soon ?

Thank for your clarifications on this 2 points.

**Comment by FayeY** [comment]
How about this [Passive Scan on ESP8266(AP Beacon)](http://bbs.espressif.com/viewtopic.php?f=31&p=12498#p12498)
