### ISSUE TITLE
When call xTaskCreate, unit of usStackDepth is byte or word? (GIT8266O-543)

### ISSUE THREAD

**Issue by itsmekingtiger** [espressif/ESP8266_RTOS_SDK#966]
## Environment

- Development Kit:
- IDF version:    `00fafb8d`
- Development Env:      `Make`
- Operating System:    `Ubuntu`
- Power Supply:         `USB`

## Problem Description

I can not sure asking this kind of question at here.
But my question on bbs is not accepted for a long time :(

When we create new task, via `xTaskCreate`,
In vanilla freeRTOS, the unit of `usStackDepth` is word.
And in ESP32, when we use `xTaskCreateStaticPinnedToCore`, the unit is byte.

Then how about ESP8266?
Is `xTaskCreate` redeclared or same as vanilla?

**Comment by dsptech** [comment]
Hi, 
usStackDepth is in byte units. Stack is allocated with (task.c):

`
    pxStack = ( StackType_t * ) pvPortMalloc( ( ( ( size_t ) usStackDepth ) * sizeof( StackType_t ) ) )
`

and StackType_t is (portmacro.h): uint8_t

Regards.
This is the same behavior of the ESP32 ESP-IDF (ESP8266_RTOS_SDK is a porting of that).
