### ISSUE TITLE
nothing after boot: Loaded app from partition at offset 0x10000 (GIT8266O-544)

### ISSUE THREAD

**Issue by ponpon1013** [espressif/ESP8266_RTOS_SDK#967]
## Environment

- Development Kit: WEMOS D1 MINI
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 7b40b23a

- Development Env:     Make
- Operating System:     Debian 10
- Power Supply:         USB

## Problem Description
I have just started learning how to use ESP8266_RTOS_SDK and I have compiled the Hello_Word example.
But it seems thath nothing happens after boot sequence. This id the same for others example ( WIFI station example)

//Detailed problem description goes here.
this what make monitor answers me:
make monitor
Toolchain path: /home/nicolas/esp/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc
Toolchain version: crosstool-ng-1.22.0-100-ge567ec7
Compiler version: 5.2.0
Python requirements from /home/nicolas/esp/ESP8266_RTOS_SDK/requirements.txt are satisfied.
MONITOR
--- idf_monitor on /dev/ttyUSB0 74880 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 4508, room 16 
tail 12
chksum 0x3b
ho 0 tail 12 room 4
load 0x3ffe8408, len 24, room 12 
tail 12
chksum 0xd2
ho 0 tail 12 room 4
load 0x3ffe8420, len 3492, room 12 
tail 8
chksum 0x8b
I (46) boot: ESP-IDF v3.2-595-g7b40b23a 2nd stage bootloader
I (46) boot: compile time 16:17:18
I (46) boot: SPI Speed      : 80MHz
I (52) boot: SPI Mode       : QIO
I (58) boot: SPI Flash Size : 4MB
I (64) boot: Partition Table:
I (70) boot: ## Label            Usage          Type ST Offset   Length
I (81) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (93) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (104) boot:  2 factory          factory app      00 00 00010000 000f0000
I (116) boot: End of partition table
I (122) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x1c5dc (116188) map
0x40210010: _stext at ??:?

I (206) esp_image: segment 1: paddr=0x0002c5f4 vaddr=0x4022c5ec size=0x05af4 ( 23284) map
I (221) esp_image: segment 2: paddr=0x000320f0 vaddr=0x3ffe8000 size=0x0061c (  1564) load
I (223) esp_image: segment 3: paddr=0x00032714 vaddr=0x40100000 size=0x00a50 (  2640) load
I (233) esp_image: segment 4: paddr=0x0003316c vaddr=0x40100a50 size=0x04a84 ( 19076) load
I (257) boot: Loaded app from partition at offset 0x10000

and after nothing

### Steps to repropduce

1. make menuconfig
     1.1 Boot Loader config-> Boot loader init SPI flash option removed. ( if I put the option I have   a boot: load partition table error!)
2. make -j4 flash
3. make monitor

Thank for your helpp and I apoligise if it is rookie error. I can't find somebody with my problem

**Comment by shengli001842** [comment]
I'm using Nodemcu just like you, I have found the problem. Please set: 
Serial flasher config  --->         
         Flash SPI mode (QIO)  --->     Flash SPI mode (DIO)  
Maybe the SPI Flash model is different


Error screenshot 
![image](https://user-images.githubusercontent.com/71212652/93015883-a015e600-f5ef-11ea-9164-a68240537827.png)

Run screenshots correctly
![image](https://user-images.githubusercontent.com/71212652/93016006-86c16980-f5f0-11ea-991d-6bea154a0c6c.png)

**Comment by ponpon1013** [comment]
Tahnks a lot.
It works also for me.
My problem is solved
