### ISSUE TITLE
Question about os_printft

### ISSUE THREAD

**Issue by gustavomassa** [espressif/ESP8266_RTOS_SDK#98]
Hello, I would like to understand the os_printf:

```
/* NOTE: don't use printf_opt in irq handler, for test */
#define os_printf(fmt, ...) do {    \
        static const char flash_str[] ICACHE_RODATA_ATTR STORE_ATTR = fmt;  \
        printf(flash_str, ##__VA_ARGS__);   \
    } while(0)
```

Where inside the flash the variable flash_str is being saved? What address?
If I use the same logic to save another string into the flash:
` static const char flashString[] ICACHE_RODATA_ATTR STORE_ATTR = "TEST";`
How can I read the flashString variable? If I read it directly it results in a fatal exception(3).
I can copy the content of the flashString to another buffer using memcpy, but I would like to read it directly without memcpy.

Thank you

**Comment by donghengqaz** [comment]
The string is saved at flash. And you can not handle the not 4-byte aligned data. Becasue it may case  loadstore exception.

And you can use v2.x.x version, we add loadstore exception handle to make it easy to use.
