### ISSUE TITLE
gdb stub not working with xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64 (GIT8266O-565)

### ISSUE THREAD

**Issue by hiperiondev** [espressif/ESP8266_RTOS_SDK#988]
xtensa-lx106-elf-gdb respond:

(gdb) target remote /dev/ttyUSB0
Remote debugging using /dev/ttyUSB0
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
Remote replied unexpectedly to 'vMustReplyEmpty': timeout

This stop debugging with eclipse

**Comment by hiperiondev** [comment]
Solved

**Comment by szekelyisz** [comment]
> Solved

Can you provide details please? I'm facing the same issue.
